'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {apiFetch,apiJson} from '../../../../lib/api';
import {apiErrorMessage,matchLabels as MATCH,draftLabels as STATE,proposalStatusLabels as STATUS,fieldLabels as FIELD,reasonKindLabels,pendingLabels as PENDING,operationLabels as OPERATION,evidenceTypeLabels as EVIDENCE,evidenceFields,coverageNote,allowedOperations,allowedEvidenceTypes,label,fieldList as fields} from './ux';
import s from './workspace.module.css';
import base from '../page.module.css';

type Reason={field:string;kind:'supporting'|'conflicting'|'missing'|'ambiguous';reason:string};
type Candidate={document_ids:number[];supporting_fields:string[];conflicting_fields:string[];missing_fields:string[];reasons:Reason[];qualified?:boolean;structure?:string};
type Doc={id:number;file_name:string;kind:string;uuid:string;issuer:string;rfc_emisor:string;issue_date:string|null;total:string|null;currency:string|null;metodo_pago:string|null;parse_error?:string|null;fields?:Record<string,{value:unknown;status:string;source_field:string;parser:string}>};
type Pending={id:number;code:string;what_is_missing:string;why_it_blocks:string;resolver:string;status:string;revision:number;movement_id:number|null;document_id:number|null;source:string};
type Proposal={id:number;revision:number;match_type:string;structure:string;status:string;requires_human_review:boolean;draft_state:string;movement:{id:number;sequence:number;date:string;amount:string;supplier:string;bank_reference:string;case_id:number|null};selected_document_ids:number[];confirmed_document_ids:number[];candidates:Candidate[];reasons:Reason[];supporting_fields:string[];conflicting_fields:string[];missing_fields:string[];pendings:Pending[];documents:Doc[];decided_by:string|null;decision_note:string};
type Draft={state:string;flags:string[];amounts:{bank:string;cfdi:string|null;difference:string|null;taxes:Record<string,string|null>};antecedents:{operations:number;conflict:boolean;accounts:{statement:string}[];notice:string}|null;memory:{supplier:{key:string;content:string;conditions:string}[];general:{key:string;content:string}[];conflicts:string[]}|null;suggested_account:{account:string;subaccount:string;detail_account:string;basis:string}|null;notice:string};
type Detail=Proposal&{draft:Draft;candidate_documents:Doc[];links:{id:number;document_id:number;confirmed_by:string;confirmed_at:string;reason:string}[]};
type Overview={period:{id:number;label:string;client_name:string;status:string};run:{id:number;status:string;summary:Record<string,number|string>;metrics:Record<string,number>;finished_at:string|null;requested_by:string|null;scope?:string;scope_notice?:string}|null;counts:Record<string,number>;proposals:Proposal[];count:number;page:number;page_size:number;pendings:Pending[];pending_count:number;pending_by_code:Record<string,number>;confirmed_links:number;previews:{id:number;status:string;items:number;revision:number}[];permissions:{manage:boolean};capabilities:{adapter:string;capability:string;status:string;note:string}[]};
type Money={status:string;bank:string;cfdi:string|null;difference:string|null};
type Preview={id:number;status:string;revision:number;evaluation:{movement_id:number;sequence:number;supplier:string;operation:string;amount:Money;existing_amount:Money;selected_amount:Money;resulting_amount:Money;existing_document_ids:number[];released_document_ids:number[];resulting_document_ids:number[];problems:{code:string;reason:string}[];will_apply:boolean;already_confirmed:number[];documents:{id:number;uuid:string;total:string|null}[]}[];expires_at:string;result?:{applied:unknown[];skipped:{movement_id:number}[]}};
async function read<T>(r:Response):Promise<T>{if(!r.ok)throw new Error(apiErrorMessage(await r.json().catch(()=>null),r.status));return r.json();}

export default function AutomationPanel({periodId,onFile}:{periodId:number;onFile:(url:string)=>void}){
 const root=`/api/carova/workspace/automation/periods/${periodId}/`;
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[page,setPage]=useState(1);
 const [open,setOpen]=useState<Detail|null>(null),[operation,setOperation]=useState<'ADD'|'REPLACE'|'RELEASE'>('ADD'),[batch,setBatch]=useState<Record<number,number[]>>({}),[preview,setPreview]=useState<Preview|null>(null),[search,setSearch]=useState<{results:Doc[];count:number;truncated:boolean}|null>(null),[extra,setExtra]=useState<number[]>([]);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const q=new URLSearchParams({page:String(page)});if(filter)q.set('match_type',filter);const result=await read<Overview>(await apiFetch(root+'?'+q,{signal}));if(!signal?.aborted)setData(result);}catch(e){if(!signal?.aborted)setError((e as Error).message);}},[root,page,filter]);
 useEffect(()=>{const ctl=new AbortController();void load(ctl.signal);return()=>ctl.abort();},[load]);
 async function act(fn:()=>Promise<void>,ok=''){setBusy(true);setError('');setNotice('');try{await fn();if(ok)setNotice(ok);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const run=(force:boolean)=>act(async()=>{await read(await apiJson(root+'run/','POST',{force}));},'Lote procesado. Nada se asoció automáticamente: revisa, acepta o corrige cada propuesta.');
 const openProposal=(id:number)=>act(async()=>{setOpen(await read<Detail>(await apiFetch(root+`proposals/${id}/`)));setExtra([]);setSearch(null);});
 function decide(p:Proposal|Detail,action:'accept'|'reject'|'correct',documentIds?:number[]){return async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason')||'');await act(async()=>{await read(await apiJson(root+`proposals/${p.id}/`,'POST',{action,reason,revision:p.revision,document_ids:documentIds}));setOpen(null);},action==='reject'?'Propuesta rechazada; el movimiento sigue pendiente de CFDI.':'Relación registrada con evidencia. No se contabilizó nada.');};}
 const toggle=(p:Proposal,docs:number[])=>setBatch(b=>{const n={...b};if(n[p.movement.id])delete n[p.movement.id];else n[p.movement.id]=docs;return n;});
 const preparePreview=()=>act(async()=>{const op=allowedOperations(!!data?.permissions.manage).includes(operation)?operation:'ADD';const items=Object.entries(batch).map(([movement_id,document_ids])=>({movement_id:Number(movement_id),document_ids,operation:op}));setPreview(await read<Preview>(await apiJson(root+'previews/','POST',{items})));});
 function confirmPreview(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!preview)return;const reason=String(new FormData(e.currentTarget).get('reason')||'');void act(async()=>{const r=await read<Preview>(await apiJson(root+`previews/${preview.id}/`,'POST',{revision:preview.revision,reason}));setPreview(null);setBatch({});setNotice(`Lote confirmado: ${r.result?.applied.length??0} asociaciones registradas, ${r.result?.skipped.length??0} omitidas porque el estado resultante era incompatible.`);});}
 const cancelPreview=()=>act(async()=>{if(preview)await read(await apiJson(root+`previews/${preview.id}/`,'POST',{action:'cancel'}));setPreview(null);});
 const exportFile=(format:'xlsx'|'csv')=>act(async()=>{const r=await read<{url:string;rows:number;coverage?:string;truncated?:boolean}>(await apiJson(root+'export/','POST',{format}));onFile(r.url);setNotice(`Archivo ${format.toUpperCase()} generado con ${r.rows} filas (borrador sin validez contable). ${r.coverage??''}`.trim());});
 // R8: un pendiente se cierra con evidencia tipificada, no con un identificador suelto.
 function resolvePending(p:Pending){return async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const reason=String(fd.get('reason')||'');const kind=String(fd.get('evidence_type')||'HUMAN_NOTE');const value=String(fd.get('evidence_value')||'').trim();const field=evidenceFields[kind]??'note';const payload:Record<string,unknown>={reason,revision:p.revision};if(value)payload[field]=field.endsWith('_id')?Number(value):value;const exception=String(fd.get('authorized_exception')||'').trim();if(exception&&field!=='authorized_decision')payload.authorized_decision=exception;await act(async()=>{await read(await apiJson(root+`pendings/${p.id}/`,'POST',payload));},'Pendiente resuelto con la evidencia indicada.');};}
 // RA-P1-04/05: sólo se ofrecen las acciones que el servidor aceptará para este rol.
 const manage=!!data?.permissions.manage;
 const evidenceFieldset=<><label>Tipo de evidencia<select name="evidence_type" defaultValue="HUMAN_NOTE">{allowedEvidenceTypes(manage).map(k=><option key={k} value={k}>{EVIDENCE[k]}</option>)}</select></label><label>Evidencia (nota, localizador o id)<input name="evidence_value" required maxLength={500}/></label>{manage&&<label>Excepción autorizada (sólo si el documento es de otro periodo o no es el del pendiente): motivo<input name="authorized_exception" maxLength={500}/></label>}</>
 function doSearch(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const q=new URLSearchParams();for(const k of ['uuid','rfc','supplier','amount','date','period','state'])if(fd.get(k))q.set(k,String(fd.get(k)));void act(async()=>{setSearch(await read(await apiFetch(root+'search/?'+q)));});}
 const summary=data?.run?.summary;const docFile=(id:number)=>root+`documents/${id}/file/`;
 const batchCount=Object.keys(batch).length;
 return <section className={s.section}>
  <h3>Automatización de egresos · banco ↔ CFDI</h3>
  <p>El sistema lee CFDI y movimientos, propone relaciones con razones y deja lo demás como pendiente explicado. Ninguna relación se confirma sola; ninguna póliza se registra en un sistema contable. AUTO_CLEAR: apagado.</p>
  {error&&<p role="alert" className={s.error}>{error}</p>}{notice&&<p role="status" className={s.success}>{notice}</p>}
  <div className={s.toolbar}><button className={base.primary} disabled={busy} onClick={()=>void run(false)}>{data?.run?'Procesar de nuevo (si cambió algo)':'Procesar periodo'}</button>{data?.run&&<button disabled={busy} onClick={()=>void run(true)}>Forzar reproceso</button>}<button disabled={busy||!data?.run} onClick={()=>void exportFile('xlsx')}>Exportar Excel</button><button disabled={busy||!data?.run} onClick={()=>void exportFile('csv')}>Exportar CSV</button><button disabled={busy} onClick={()=>void load()}>Actualizar</button></div>
  {busy&&<p role="status" className={s.loading}>Trabajando…</p>}
  {summary&&<div className={s.quickNav} aria-label="Resumen del lote">{[['Movimientos','TOTAL_MOVEMENTS'],['Exactas por revisar','AUTO_MATCHED'],['Fuertes','STRONG'],['Ambiguas','AMBIGUOUS'],['Sin CFDI','MISSING_CFDI'],['Conflictos','CONFLICT'],['Sin soporte','MISSING_SUPPORT'],['Periodo por confirmar','PERIOD_REVIEW'],['Ya confirmadas','ALREADY_CONFIRMED'],['CFDI sin movimiento que lo reclame','DOCUMENTS_WITHOUT_MOVEMENT'],['Pendientes','PENDINGS']].map(([label,key])=><span key={key}><strong>{summary[key]??0}</strong> {label}</span>)}</div>}
  {data?.run?.scope_notice&&<small role="note">{data.run.scope_notice}</small>}{data?.run&&<small>Lote {data.run.id} · {data.run.status} · {data.run.finished_at?new Date(data.run.finished_at).toLocaleString('es-MX'):''} · {data.run.metrics?.duration_ms} ms · {data.run.metrics?.queries} consultas · {data.confirmed_links} relaciones confirmadas por personas</small>}
  {!data?.run&&data&&<p>Todavía no se ha procesado este periodo. Registra el estado de cuenta, sus movimientos y los CFDI, y pulsa “Procesar periodo”.</p>}
  {data?.run&&<>
   <div className={s.toolbar} aria-label="Filtrar propuestas">{[['','Todas'],['EXACT_MATCH','Exactas'],['STRONG_MATCH','Fuertes'],['AMBIGUOUS','Ambiguas'],['CONFLICT','Conflictos'],['NO_MATCH','Sin CFDI'],['INSUFFICIENT_EVIDENCE','Evidencia insuficiente']].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>{setFilter(v);setPage(1);}}>{l}{v&&data.counts[v]?` (${data.counts[v]})`:''}</button>)}</div>
   {batchCount>0&&!preview&&<div className={s.toolbar}><strong>{batchCount} movimientos seleccionados</strong>{allowedOperations(manage).length>1?<label>Operación<select value={operation} onChange={e=>setOperation(e.target.value as 'ADD'|'REPLACE'|'RELEASE')}>{allowedOperations(manage).map(k=><option key={k} value={k}>{OPERATION[k]}</option>)}</select></label>:<small>{OPERATION.ADD}. Sustituir o liberar relaciones confirmadas requiere gerencia.</small>}<button className={base.primary} disabled={busy} onClick={()=>void preparePreview()}>Preparar vista previa</button><button onClick={()=>setBatch({})}>Limpiar selección</button></div>}
   {preview&&<form className={s.form} onSubmit={confirmPreview}><h3>Vista previa del lote · vence {new Date(preview.expires_at).toLocaleTimeString('es-MX')}</h3><p>La vista previa muestra el estado <strong>resultante</strong> de cada movimiento: lo ya relacionado, más lo seleccionado, menos lo que se libera.</p>{preview.evaluation.map(e=><p key={e.movement_id}>{e.will_apply?'✓':'✕'} Consecutivo {e.sequence} · {e.supplier||'sin proveedor'} · {label(OPERATION,e.operation)}<br/>Banco {e.resulting_amount.bank} · ya relacionado {e.existing_amount.cfdi??'—'} · se agrega {e.selected_amount.cfdi??'—'}{e.released_document_ids.length>0&&` · se libera ${e.released_document_ids.length} documento(s)`} · <strong>resultante {e.resulting_amount.cfdi??'importe desconocido'}</strong> ({e.resulting_amount.status==='EXACT'?'exacto':e.resulting_amount.status==='DIFFERENCE'?`diferencia ${e.resulting_amount.difference}`:'importe desconocido'})<br/>Documentos: {e.documents.map(d=>d.uuid||d.id).join(', ')}{e.problems.map(p=><span key={p.code+p.reason}> — {p.reason}</span>)}{e.already_confirmed.length>0&&' — ya confirmado antes'}</p>)}<label>Motivo / evidencia<textarea name="reason" required maxLength={4000}/></label><p>Confirmar registra quién relacionó qué documentos con qué pago. No contabiliza ni envía nada.</p><div className={s.toolbar}><button className={base.primary} disabled={busy}>Confirmar lote</button><button type="button" onClick={()=>void cancelPreview()}>Cancelar vista previa</button></div></form>}
   <div className={s.grid}>{data.proposals.map(p=>{const docs=p.confirmed_document_ids.length?p.confirmed_document_ids:p.selected_document_ids;const selectable=p.status==='PROPOSED'&&docs.length>0;return <article key={p.id} className={p.match_type==='CONFLICT'||p.match_type==='AMBIGUOUS'?s.provisional:s.card}>
    <div className={s.meta}><span>Consecutivo {p.movement.sequence} · {p.movement.date}</span><span>{p.movement.amount} MXN</span></div>
    <h4>{p.movement.supplier||'Sin proveedor en banco'}</h4><small>{p.movement.bank_reference}</small>
    <p><strong>{label(MATCH,p.match_type)}</strong> · {p.structure} · {label(STATUS,p.status)} · borrador: {label(STATE,p.draft_state)}</p>
    <small>Coincide: {fields(p.supporting_fields)} · Conflicto: {fields(p.conflicting_fields)} · Falta: {fields(p.missing_fields)}</small>
    {p.documents.map(d=><p key={d.id}>{d.file_name} · {d.issuer||d.rfc_emisor||'emisor desconocido'} · {d.total??'importe ilegible'} {d.currency||''} · {d.issue_date||'sin fecha'} <button onClick={()=>onFile(docFile(d.id))}>Abrir CFDI</button></p>)}
    {p.pendings.length>0&&<small>Pendientes: {p.pendings.map(x=>label(PENDING,x.code)).join(' · ')}</small>}
    <div className={s.toolbar}><button onClick={()=>void openProposal(p.id)}>Ver razones, antecedente y borrador</button>{selectable&&<label className={s.check}><input type="checkbox" checked={!!batch[p.movement.id]} onChange={()=>toggle(p,docs)}/>Incluir en lote</label>}</div>
   </article>;})}</div>
   {data.count>data.page_size&&<div className={s.toolbar}><button disabled={page===1} onClick={()=>setPage(page-1)}>Anteriores</button><span>{page} / {Math.ceil(data.count/data.page_size)} · {data.count} movimientos</span><button disabled={page*data.page_size>=data.count} onClick={()=>setPage(page+1)}>Siguientes</button></div>}
   {open&&<div className={s.form}><div className={s.toolbar}><h3>Consecutivo {open.movement.sequence} · {open.movement.supplier||'sin proveedor'} · {open.movement.amount}</h3><button onClick={()=>setOpen(null)}>Cerrar</button></div>
    <p><strong>{label(MATCH,open.match_type)}</strong> · {label(STATUS,open.status)} {open.decided_by&&`· ${open.decided_by}: ${open.decision_note}`}</p>
    <h4>Por qué</h4><ul>{open.reasons.map((r,i)=><li key={i}>[{label(reasonKindLabels,r.kind)} · {label(FIELD,r.field)}] {r.reason}</li>)}</ul>
    <h4>Candidatos</h4>{open.candidates.length===0&&<p>Sin candidatos con importe exacto.</p>}{open.candidates.map((c,i)=><details key={i} open={i===0}><summary>{c.qualified?'Candidato válido':'Descartado'} · documentos {c.document_ids.join(', ')} · coincide: {fields(c.supporting_fields)} · conflicto: {fields(c.conflicting_fields)}</summary><ul>{c.reasons.map((r,j)=><li key={j}>{r.reason}</li>)}</ul>{open.status==='PROPOSED'&&<form onSubmit={decide(open,'correct',c.document_ids)}><label>Motivo<input name="reason" required maxLength={4000}/></label><button disabled={busy||c.conflicting_fields.includes('already_associated')}>Relacionar con estos documentos</button></form>}</details>)}
    {open.candidate_documents.length>0&&<p>{open.candidate_documents.map(d=><button key={d.id} onClick={()=>onFile(docFile(d.id))}>Abrir {d.uuid||d.file_name}</button>)}</p>}
    <h4>Borrador de póliza · {label(STATE,open.draft.state)}</h4>
    <p>Banco {open.draft.amounts.bank} · CFDI {open.draft.amounts.cfdi??'—'} · diferencia {open.draft.amounts.difference??'no calculable'} · IVA trasladado {open.draft.amounts.taxes.iva_trasladado??'—'} · retenciones {open.draft.amounts.taxes.retenciones??'—'}</p>
    {open.draft.suggested_account?<p>Antecedente de cuenta: {open.draft.suggested_account.account}{open.draft.suggested_account.subaccount&&` → ${open.draft.suggested_account.subaccount}`}{open.draft.suggested_account.detail_account&&` → ${open.draft.suggested_account.detail_account}`} — {open.draft.suggested_account.basis} No es una decisión.</p>:<p>{open.draft.antecedents?.conflict?'Antecedentes contradictorios: la cuenta requiere criterio profesional.':'Sin antecedente verificado para este proveedor.'}</p>}
    {open.draft.antecedents&&open.draft.antecedents.accounts.length>0&&<ul>{open.draft.antecedents.accounts.map((a,i)=><li key={i}>{a.statement}</li>)}</ul>}
    {open.draft.memory&&(open.draft.memory.supplier.length>0||open.draft.memory.general.length>0||open.draft.memory.conflicts.length>0)&&<><h4>Criterios aprobados vigentes</h4><ul>{[...open.draft.memory.supplier,...open.draft.memory.general].map(m=><li key={m.key}><strong>{m.key}</strong>: {m.content}</li>)}{open.draft.memory.conflicts.map(k=><li key={k}>Conflicto de criterio en {k}: requiere resolución humana; no se aplica ninguna variante.</li>)}</ul></>}
    {open.pendings.length>0&&<><h4>Pendientes de este movimiento</h4>{open.pendings.map(p=><details key={p.id}><summary>{label(PENDING,p.code)} · {p.what_is_missing}</summary><p>Por qué bloquea: {p.why_it_blocks}</p><p>Quién resuelve: {p.resolver}</p><p>Origen: {p.source}</p><form onSubmit={resolvePending(p)}><label>Cómo se resolvió<input name="reason" required maxLength={4000}/></label>{evidenceFieldset}<button disabled={busy}>Marcar resuelto</button></form></details>)}</>}
    {open.status==='PROPOSED'&&<div className={s.formGrid}>{['EXACT_MATCH','STRONG_MATCH'].includes(open.match_type)&&<form onSubmit={decide(open,'accept')}><label>Motivo<input name="reason" required maxLength={4000} defaultValue="Revisé el CFDI y coincide con el pago"/></label><button className={base.primary} disabled={busy}>Aceptar relación</button></form>}<form onSubmit={decide(open,'reject')}><label>Motivo<input name="reason" required maxLength={4000}/></label><button disabled={busy}>Rechazar propuesta</button></form></div>}
    <details><summary>Buscar otro CFDI para corregir (UUID, RFC, proveedor, importe, fecha)</summary><form onSubmit={doSearch} className={s.formGrid}><label>UUID<input name="uuid"/></label><label>RFC<input name="rfc"/></label><label>Proveedor<input name="supplier"/></label><label>Importe exacto<input name="amount" type="number" step="0.01"/></label><label>Fecha<input name="date" type="date"/></label><label>Periodo (AAAA-MM)<input name="period"/></label><label>Estado<select name="state"><option value="">Todos</option><option value="unassociated">Sin asociar</option><option value="associated">Asociados</option></select></label><button disabled={busy}>Buscar</button></form>
     {search&&<><p>{search.count} documentos · {coverageNote(search)}</p>{search.results.map(d=><p key={d.id}><label className={s.check}><input type="checkbox" checked={extra.includes(d.id)} onChange={()=>setExtra(x=>x.includes(d.id)?x.filter(i=>i!==d.id):[...x,d.id])}/>{d.file_name} · {d.issuer||d.rfc_emisor} · {d.total??'?'} · {d.issue_date||'sin fecha'} · {d.metodo_pago||''}</label><button onClick={()=>onFile(docFile(d.id))}>Abrir</button></p>)}{extra.length>0&&open.status==='PROPOSED'&&<form onSubmit={decide(open,'correct',extra)}><label>Motivo<input name="reason" required maxLength={4000}/></label><button className={base.primary} disabled={busy}>Relacionar con {extra.length} documento(s) seleccionado(s)</button></form>}</>}
    </details>
    {open.links.length>0&&<><h4>Relaciones confirmadas</h4>{open.links.map(l=><p key={l.id}>Documento {l.document_id} · {l.confirmed_by} · {new Date(l.confirmed_at).toLocaleString('es-MX')} · {l.reason}</p>)}</>}
    <small>{open.draft.notice}</small>
   </div>}
   <h4>Pendientes abiertos del periodo ({data.pending_count})</h4>
   <small>{Object.entries(data.pending_by_code).map(([k,v])=>`${label(PENDING,k)}: ${v}`).join(' · ')||'Ninguno'}</small>
   <div className={s.grid}>{data.pendings.slice(0,30).map(p=><article key={p.id} className={s.card}><strong>{label(PENDING,p.code)}</strong><p>{p.what_is_missing}</p><small>Por qué bloquea: {p.why_it_blocks}</small><small>Quién resuelve: {p.resolver}</small><small>Origen: {p.source}</small>{p.document_id&&<button onClick={()=>onFile(docFile(p.document_id!))}>Abrir documento</button>}<form onSubmit={resolvePending(p)}><label>Cómo se resolvió<input name="reason" required maxLength={4000}/></label>{evidenceFieldset}<button disabled={busy}>Marcar resuelto</button></form></article>)}</div>
   {data.pending_count>30&&<p>Se muestran 30 de {data.pending_count} pendientes; usa las propuestas para ver el resto por movimiento.</p>}
   <details><summary>Qué no hace este motor (integraciones externas)</summary><ul>{data.capabilities.filter(c=>c.status!=='IMPLEMENTED_LOCAL').map(c=><li key={c.capability}>{c.capability}: {c.status} — {c.note}</li>)}</ul></details>
  </>}
 </section>;
}
