'use client';
import {useState} from 'react';
import {apiFetch,apiJson} from '@/lib/api';
import Modal from '@/components/panel/Modal';
import FormField from '@/components/panel/FormField';
import {apiErrorMessage} from './ux';
type Preview={preview_token:string;allowed:boolean;blockers:string[];account:string;period:string;file:string;movements:number;associations:number;calculated_runs:number;reconciliations:number;explanation:string;downstream_objects:Record<string,number>};
export default function BankWithdrawal({periodId,importId,onComplete}:{periodId:number;importId:number;onComplete:()=>void}){
 const [open,setOpen]=useState(false),[p,setP]=useState<Preview|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const url=`/api/carova/workspace/bank/periods/${periodId}/imports/${importId}/withdraw/`;
 async function review(){setOpen(true);setBusy(true);setP(null);setReason('');setConfirmed(false);setError('');try{const r=await apiFetch(url);const d=await r.json();if(!r.ok)throw new Error(apiErrorMessage(d,r.status));setP(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!p)return;setBusy(true);try{const r=await apiJson(url,'POST',{reason,confirmed,preview_token:p.preview_token});if(!r.ok)throw new Error(apiErrorMessage(await r.json(),r.status));setOpen(false);onComplete();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button type="button" onClick={review}>Retirar importación</button><Modal open={open} title="Retirar importación bancaria" onClose={()=>!busy&&setOpen(false)}><form className="uploadForm" onSubmit={save}>{p&&<><p>{p.explanation}</p><dl><dt>Cuenta / periodo</dt><dd>{p.account} · {p.period}</dd><dt>Archivo</dt><dd>{p.file}</dd><dt>Movimientos conservados</dt><dd>{p.movements}</dd><dt>Asociaciones afectadas</dt><dd>{p.associations}</dd><dt>Conciliaciones / cálculos</dt><dd>{p.reconciliations} / {p.calculated_runs}</dd><dt>Dependencias finales</dt><dd>{p.downstream_objects.active_collections} cobros activos · {p.downstream_objects.authorized_workpapers} papeles autorizados · {p.downstream_objects.closed_cases} pólizas cerradas</dd></dl>{p.blockers.map(x=><p key={x} role="alert">{x}</p>)}<FormField label="Motivo del retiro" required><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} required/></FormField><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo el retiro y la necesidad de recalcular/revisar.</label><button className="cc-btn cc-btn--solid" disabled={busy||!p.allowed||!confirmed||reason.trim().length<5}>Confirmar retiro</button></>}{error&&<p role="alert">{error}</p>}</form></Modal></>;
}
