'use client';
import {useEffect,useState,useRef,type FormEvent} from 'react';
import {apiFetch,apiJson} from '../../../../lib/api';
import {apiErrorMessage} from './ux';
import AutomationPanel from './AutomationPanel';
import BankPanel from './BankPanel';
import IvaPanel from './IvaPanel';
import AccountingPanel from './AccountingPanel';
import type {Overview} from './types';
import {periodDefaults,periodYearOptions,PERIOD_MONTHS,serializePeriodCreation} from './periodCreation';
import s from './workspace.module.css';
import base from '../page.module.css';
type Summary={open_cases:number;waiting:number;responses:number;escalated:number;bank_pending:number;bank_missing:boolean;iva_open:number;differences_open:number;vat_ready:boolean;ready_for_review:boolean;partner_pending:boolean;communications:number;grants_pending:number;responsible_ids:number[]};
type Row={id:number;client_id:number;label:string;client_name:string;status:string;revision:number;summary?:Summary};
type Field={key:string;label:string;type?:string;options?:[string,string][];optional?:boolean};
type Command={action:string;label:string;fields:Field[];group?:string};
type Section={title:string;group?:string;rows:{title:string;details:string[];special_type?:string;file_url?:string;attention?:string;items?:{id:number;case_id:number;title:string;description:string;draft:string;evidence:{label:string;file_url:string}[]}[]}[]};
type Detail=Row&{commands?:Command[];sections?:Section[];permissions:{manage:boolean;partner:boolean};grants:{id:number;granted_to_name:string;revoked_at:string|null;partner_at:string|null;expires_at:string}[];timeline:{id:number;actor:string;action:string;reason:string;timestamp:string}[];cases:{id:number;reference:string;status:string;workflow_label?:string}[]};
const root='/api/carova/workspace/periods/';
const paymentLabels:Record<string,string>={UNKNOWN:'Por confirmar',NOT_APPLICABLE:'No aplica',REP_PRESENT:'REP recibido',REP_PENDING:'REP pendiente',NONE:'Sin operación especial'};
async function read<T>(r:Response):Promise<T>{if(!r.ok)throw new Error(apiErrorMessage(await r.json().catch(()=>null),r.status));return r.json();}
const labels:Record<string,string>={OPEN:'En proceso',REVIEWED:'Revisado',CLOSED:'Periodo cerrado',CAPTURADA:'Capturada',TERMINADA:'Terminada',CERRADA:'Póliza cerrada',CANCELADA:'Cancelada'};
const groups=['Contexto y cierre','Recepción','Automatización','Bancos / Conciliación','IVA','Contabilidad','Seguimiento','Revisión mensual','Socio y salida'];
function Cards({section,onFile}:{section:Section;onFile:(url:string)=>void}){
 const [page,setPage]=useState(1),[special,setSpecial]=useState('');
 const rows=section.rows.filter(r=>!special||r.special_type===special),pages=Math.max(1,Math.ceil(rows.length/30)),current=Math.min(page,pages);
 return <section><h3>{section.title}</h3>{section.rows.some(r=>r.special_type)&&<label>Filtrar operaciones especiales<select value={special} onChange={e=>{setSpecial(e.target.value);setPage(1);}}><option value="">Todas</option>{['RETENCIONES','NOTA_CREDITO','ANTICIPO','PAGO_PARCIAL','PAGO_AGRUPADO','MONEDA_EXTRANJERA'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label>}<div className={s.grid}>{rows.slice((current-1)*30,current*30).map((r,i)=><article className={r.attention?s.provisional:s.card} key={i}>{r.attention&&<strong>{r.attention}</strong>}<strong>{r.title.replaceAll('_',' ')}</strong>{r.details.filter(Boolean).map((v,j)=><p key={j}>{v.replaceAll('_',' ')}</p>)}{r.items&&<details><summary>Consultar borrador y evidencia de esta versión</summary>{r.items.map(item=><section key={item.id}><h4>{item.title}</h4><p>{item.description}</p><p>{item.draft||'Sin borrador registrado.'}</p><a href={`/panel/carova/egresos/${item.case_id}?${new URLSearchParams(typeof window==='undefined'?'':window.location.search)}`}>Abrir caso y contexto</a>{item.evidence.map(e=><p key={e.file_url}><button onClick={()=>onFile(e.file_url)}>Abrir evidencia: {e.label}</button></p>)}</section>)}{!r.items.length&&<p>No hay aclaraciones visibles dentro de tu asignación.</p>}</details>}{r.file_url&&<button onClick={()=>onFile(r.file_url!)}>Abrir archivo recibido</button>}</article>)}</div>{!rows.length&&<p>No hay registros en esta sección.</p>}{pages>1&&<div className={s.toolbar}><button disabled={current===1} onClick={()=>setPage(current-1)}>Registros anteriores</button><span>{current} / {pages} · {rows.length} registros</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Más registros</button></div>}</section>;
}
export default function PeriodPanel({overview}:{overview:Overview}){
 const [group,setGroup]=useState(overview.permissions.authorize?'Socio y salida':'Contexto y cierre'),[casePage,setCasePage]=useState(1);const requestId=useRef(0);
 const [rows,setRows]=useState<Row[]>([]),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState<number|null>(null),[command,setCommand]=useState<Command|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[count,setCount]=useState(0),[reportPackage,setReportPackage]=useState('');
 async function load(id=selected){const result=await read<{results:Row[];count:number}>(await apiFetch(root+'?page='+page));setRows(result.results);setCount(result.count);if(id)setDetail(await read<Detail>(await apiFetch(root+id+'/')));}
 useEffect(()=>{const ctl=new AbortController();void(async()=>{try{const id=Number(new URLSearchParams(window.location.search).get('accounting_period'));if(id){const selectedDetail=await read<Detail>(await apiFetch(root+id+'/',{signal:ctl.signal}));if(!ctl.signal.aborted){setSelected(id);setDetail(selectedDetail);const q=new URLSearchParams(window.location.search);const report=q.get('package_report')||'';if(/^[1-9]\d*$/.test(report)){setReportPackage(report);setGroup('Recepción');setCommand(selectedDetail.commands?.find(c=>c.action==='package_report')||null);}else if(groups.includes(q.get('section')||''))setGroup(q.get('section')!);}}const r=await read<{results:Row[];count:number}>(await apiFetch(root+'?page='+page,{signal:ctl.signal}));if(!ctl.signal.aborted){setRows(r.results);setCount(r.count);}}catch(e){if(!ctl.signal.aborted)setError(String(e instanceof Error?e.message:e));}})();return()=>ctl.abort();},[page]);
 async function choose(id:number){const version=++requestId.current;setSelected(id);setDetail(null);setCommand(null);setCasePage(1);setError('');const q=new URLSearchParams(window.location.search);q.set('accounting_period',String(id));if(groups.includes(q.get('section')||''))setGroup(q.get('section')!);window.history.replaceState(null,'','?'+q);window.dispatchEvent(new PopStateEvent('popstate'));try{const result=await read<Detail>(await apiFetch(root+id+'/'));if(version===requestId.current)setDetail(result);}catch(e){if(version===requestId.current)setError((e as Error).message);}}
 async function openFile(url:string){try{const r=await apiFetch(url);if(!r.ok)throw new Error('El archivo no está disponible en tu contexto.');const blob=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=blob;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(blob),60000);}catch(e){setError((e as Error).message);}}
 const [calendar,setCalendar]=useState(periodDefaults);
 function create(){setCalendar(periodDefaults());setError('');setCommand({action:'create',label:'Crear periodo',fields:[{key:'engagement_id',label:'Cliente / Encargo',options:overview.contexts.map(c=>[String(c.id),`${c.cliente__name} · ${c.nombre}`])},{key:'year',label:'Año',options:periodYearOptions()},{key:'month',label:'Mes',options:PERIOD_MONTHS.map((label,index)=>[String(index+1),label])},{key:'supervisor_id',label:'Gerente responsable',options:overview.users.filter(u=>['manager','partner'].includes(u.role)).map(u=>[String(u.id),u.name])}]});}
 const users=overview.users.map(u=>[String(u.id),u.name] as [string,string]);
 const commands:Command[]=[
 ...(detail?.permissions.manage?[{action:'review',label:'Revisión y autorización para imprimir',fields:[]},{action:'close',label:'Cerrar y bloquear periodo',fields:[]},{action:'grant',label:'Conceder corrección temporal',fields:[{key:'granted_to_id',label:'Usuario autorizado',options:users},{key:'starts_at',label:'Inicio',type:'datetime-local'},{key:'expires_at',label:'Expiración',type:'datetime-local'}]},{action:'revoke',label:'Retirar permiso',fields:[{key:'grant_id',label:'Permiso',options:detail.grants.map(g=>[String(g.id),g.granted_to_name] as [string,string])}]}]:[]),
 ...(detail?.permissions.partner?[{action:'endorse',label:'Respaldar corrección',fields:[{key:'grant_id',label:'Permiso',options:detail.grants.map(g=>[String(g.id),g.granted_to_name] as [string,string])}]}]:[]),...(detail?.commands??[])];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!command)return;setBusy(true);setError('');const fd=new FormData(e.currentTarget);const body:Record<string,unknown>={action:command.action,revision:detail?.revision};for(const [key,val] of fd.entries()){if(val==='')continue;body[key]=val;}for(const f of command.fields){if(f.type==='checkbox')body[f.key]=fd.has(f.key);if(f.type==='multi')body[f.key]=fd.getAll(f.key);}try{const isNew=command.action==='create';if(isNew)Object.assign(body,serializePeriodCreation(fd,overview));await read(await apiJson(isNew?root:root+selected+'/', 'POST',body));setCommand(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section><div className={s.toolbar}><h2>Periodos contables</h2>{overview.permissions.manage&&<button onClick={create}>Crear periodo</button>}</div>{error&&<p role="alert" className={s.error}>{error}</p>}
 <div className={s.grid}>{rows.map(p=><button key={p.id} className={s.card} onClick={()=>void choose(p.id)}>{p.client_name} · {p.label}<br/>{labels[p.status]||p.status}</button>)}</div>{!rows.length&&<p>Todavía no hay periodos. Los paquetes anteriores se vinculan al registrar trabajo.</p>}<div className={s.toolbar}><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page}</span><button disabled={page*30>=count} onClick={()=>setPage(page+1)}>Siguiente</button></div>
 {detail&&<><h3>{detail.client_name} · {detail.label} — {labels[detail.status]||detail.status}</h3><p>El cierre del periodo no significa que el servicio mensual haya terminado.</p><div className={s.toolbar} aria-label="Secciones del periodo">{groups.map(g=><button key={g} aria-pressed={group===g} onClick={()=>{setGroup(g);setCommand(null);const q=new URLSearchParams(window.location.search);q.set('section',g);window.history.replaceState(null,'','?'+q);window.dispatchEvent(new PopStateEvent('popstate'));}}>{g}</button>)}</div><h3>{group}</h3><div className={s.toolbar}><button onClick={()=>void load()}>Actualizar periodo</button>{commands.filter(c=>(c.group||'Contexto y cierre')===group).map(c=><button key={c.action} onClick={()=>setCommand(c)}>{c.label}</button>)}</div></>}
 {command&&<form className={s.form} onSubmit={submit}><h3>{command.label}</h3><div className={s.formGrid}>{command.fields.map(f=><label key={f.key}>{f.label}{command.action==='create'&&(f.key==='year'||f.key==='month')?<select name={f.key} aria-label={f.label} value={calendar[f.key]} onChange={e=>setCalendar({...calendar,[f.key]:Number(e.target.value)})} required>{f.options?.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:f.options?<select name={f.key} aria-label={command.action==='create'?f.label:undefined} defaultValue={f.key==='package_id'?reportPackage||undefined:undefined} multiple={f.type==='multi'} required={!f.optional}><option value="">Selecciona</option>{f.options.map(([value,label])=><option key={value} value={value}>{paymentLabels[label]||label}</option>)}</select>:f.type==='textarea'?<textarea name={f.key} maxLength={4000} required={!f.optional}/>:<input name={f.key} type={['integer','decimal'].includes(f.type||'')?'number':f.type||'text'} step={f.type==='integer'?'1':['number','decimal'].includes(f.type||'')?'0.01':undefined} required={!f.optional&&f.type!=='checkbox'}/>}</label>)}<label>{command.action==='create'?'Nota del periodo':'Motivo / evidencia de la acción'}<textarea name="reason" required maxLength={4000}/></label></div><button disabled={busy} className={base.primary}>{busy?'Guardando…':command.action==='create'?'Crear periodo':'Guardar cambio'}</button><button type="button" onClick={()=>setCommand(null)}>Cancelar</button></form>}
 {detail&&<>{group==='Contexto y cierre'&&<><h3>Pólizas del periodo</h3>{detail.cases.slice((casePage-1)*30,casePage*30).map(c=><p key={c.id}><a href={`/panel/carova/egresos/${c.id}?tab=Periodos&accounting_period=${detail.id}`}>{c.reference||'Operación'} · {c.workflow_label||labels[c.status]||c.status.replaceAll('_',' ')}</a></p>)}{detail.cases.length>30&&<div className={s.toolbar}><button disabled={casePage===1} onClick={()=>setCasePage(casePage-1)}>Pólizas anteriores</button><span>{casePage} / {Math.ceil(detail.cases.length/30)}</span><button disabled={casePage*30>=detail.cases.length} onClick={()=>setCasePage(casePage+1)}>Más pólizas</button></div>}</>}{group==='Automatización'&&<AutomationPanel key={detail.id} periodId={detail.id} onFile={url=>void openFile(url)}/>}{group==='Bancos / Conciliación'&&<BankPanel key={'bank'+detail.id} periodId={detail.id} onFile={url=>void openFile(url)}/>}{group==='IVA'&&<IvaPanel key={'iva'+detail.id} periodId={detail.id} onFile={url=>void openFile(url)}/>}{group==='Contabilidad'&&<AccountingPanel key={'cg'+detail.id} periodId={detail.id} onFile={url=>void openFile(url)}/>}{detail.sections?.filter(section=>section.group===group).map(section=><Cards key={detail.id+section.title} section={section} onFile={url=>void openFile(url)}/>)}{['Contexto y cierre','Socio y salida'].includes(group)&&<><h3>Permisos extraordinarios</h3>{detail.grants.map(g=><p key={g.id}>{g.granted_to_name} · {g.revoked_at?'Retirado':new Date(g.expires_at).getTime()<=Date.now()?'Expirado':g.partner_at?'Respaldado por socio':'Pendiente de respaldo'} · Expira {new Date(g.expires_at).toLocaleString('es-MX')}</p>)}</>}<details><summary>Historial del periodo (últimas 100 acciones)</summary>{detail.timeline.map(t=><p key={t.id}>{new Date(t.timestamp).toLocaleString('es-MX')} · {t.actor} · {t.reason}</p>)}</details></>}
 </section>;
}

export function PeriodOverview({filters}:{filters:{client:string;period:string;responsible:string}}){
 const [periods,setPeriods]=useState<Row[]>([]),[error,setError]=useState(''),[page,setPage]=useState(1),[count,setCount]=useState(0);
 useEffect(()=>{const ctl=new AbortController();void(async()=>{try{const data=await read<{results:Row[];count:number}>(await apiFetch(root+'?page='+page,{signal:ctl.signal}));if(!ctl.signal.aborted){setPeriods(data.results);setCount(data.count);}}catch(e){if(!ctl.signal.aborted)setError((e as Error).message);}})();return()=>ctl.abort();},[page]);
 const shown=periods.filter(p=>(!filters.client||String(p.client_id)===filters.client)&&(!filters.period||p.label===filters.period)&&(!filters.responsible||p.summary?.responsible_ids.includes(Number(filters.responsible))));
 return <section><h2>Revisión mensual del equipo</h2>{error&&<p role="alert">{error}</p>}<div className={s.grid}>{shown.map(p=>{const x=p.summary;if(!x)return null;return <article className={s.card} key={p.id}><h3>{p.client_name} · {p.label}</h3><strong>{p.status==='CLOSED'?'Periodo cerrado':x.ready_for_review?'Controles reunidos para revisión de cierre':'Pendientes antes del cierre'}</strong><p>{x.open_cases} pólizas sin cierre · {x.waiting} esperando cliente · {x.responses} respuestas por revisar · {x.escalated} escalados</p><p>Banco: {x.bank_missing?'sin fuente registrada':x.bank_pending?`${x.bank_pending} conciliaciones pendientes o desactualizadas`:'conciliación vigente revisada'}</p><p>IVA: {x.iva_open} diferencias abiertas · {x.vat_ready?'constancia previa registrada':'constancia previa pendiente'}</p><p>{x.communications} listados esperan autorización del Socio · {x.grants_pending} permisos esperan respaldo</p><p>{x.partner_pending?'Revisión superior pendiente':p.status==='CLOSED'?'Revisión superior registrada':'Revisión superior posterior al cierre'}</p><a href={`/panel/carova/egresos?tab=Periodos&accounting_period=${p.id}`}>Revisar este periodo</a></article>;})}</div>{page*30<count&&<button onClick={()=>setPage(page+1)}>Ver más periodos</button>}{page>1&&<button onClick={()=>setPage(page-1)}>Periodos anteriores</button>}</section>;
}
