'use client';
import Link from 'next/link';
import Alert from '../panel/Alert';
import {useSearchParams,useRouter} from 'next/navigation';
import {useCallback,useEffect,useRef,useState} from 'react';
import {usePanelUser} from '../../lib/PanelUserContext';
import {request,route,refPath,download,encoded,PayrollFailure} from '../../lib/payroll/client';
import {allowed,privileged,publicRef,object,rows,text,label,type Data,type Surface,type Field,type FormSpec,type Option} from '../../lib/payroll/model';
import PayrollFormDialog from './PayrollFormDialog';
import styles from './Payroll.module.css';
const titles:Record<Surface,string>={home:'Nómina',employer:'Empleador',employee:'Trabajador',period:'Periodo',run:'Corrida de nómina',social:'Seguridad social',import:'Evidencia importada',reconciliation:'Conciliación'};
const names:Record<string,string>={ref:'Referencia',employee_ref:'Trabajador',name:'Nombre',employee_code:'Código',rfc:'RFC',curp:'CURP',nss:'NSS',status:'Estado',state:'Estado',currentness:'Vigencia',physical_integrity:'Integridad',generation:'Generación',version:'Versión',revision:'Revisión',effective_from:'Vigente desde',effective_to:'Vigente hasta',amount:'Importe',unit:'Unidad',currency:'Moneda',sbc_amount:'SBC declarado',sbc_provenance:'Origen del SBC',sbc_source:'Fuente del SBC',reason:'Razón',approved_by:'Aprobado por',approved_at:'Aprobado el',start:'Inicio',end:'Fin',payment_date:'Fecha de pago',period_type:'Tipo de periodo',calculation_scope:'Alcance',scope_reason:'Razón del alcance',code:'Código',kind:'Tipo',rule:'Regla',position:'Puesto',work_schedule:'Jornada declarada',salary_type:'Tipo salarial',source_kind:'Origen',source_reference:'Referencia de fuente',source_version:'Versión de fuente',source_sha256:'SHA de la fuente',fingerprint:'Huella del material',sha256:'SHA de bytes',parser_code:'Parser técnico',parser_version:'Versión del parser',uploaded_by:'Importado por',uploaded_at:'Importado el',official_format_status:'Formato oficial',row_index:'Fila de fuente',component_code:'Componente',field:'Campo',carova_value:'Valor CAROVA',external_value:'Valor externo',difference:'Diferencia',gross:'Percepciones',deductions:'Deducciones',net:'Neto interno configurado',employee_amount:'Importe trabajador',employer_amount:'Importe empleador',total:'Total',employee_total:'Total trabajador',employer_total:'Total empleador',social_total:'Total configurado',resolution_history:'Historia de resolución',resolution:'Resolución',actor:'Actor',at:'Fecha',details:'Detalle',snapshot:'Material de origen',components:'Componentes',provenance:'Origen',identifiers:'Identificadores',quantity:'Cantidad',base:'Base',rate:'Tasa configurada',concept:'Concepto',lines:'Líneas',source:'Fuente',totals:'Importes internos',calculation_causes:'Material faltante',approval_causes:'Para aprobación',comparison:'Comparación',open_differences:'Diferencias abiertas',resolved_differences:'Diferencias resueltas',effective_fingerprint:'Huella efectiva',auto_correction:'Corrección automática',auto_approval:'Aprobación automática',employer_version:'Versión patronal',rule_set:'Reglas aplicadas',employment:'Empleo',compensation:'Compensación',incidents:'Incidencias',required_concepts:'Conceptos requeridos',required_identifiers:'Identificadores requeridos',employee:'Trabajador',pay_units:'Unidades de pago',filename:'Nombre seguro',readiness:'Preparación',counts:'Conteos completos',workers:'Trabajadores',sources:'Fuentes',reconciliations:'Conciliaciones',manifest_sha256:'SHA del manifest'};
const options=(values:string[]):Option[]=>values.map(value=>({value,label:label(value)}));
const field=(name:string,title?:string,type:Field['type']='text',required=true,initial?:unknown):Field=>({name,label:title||names[name]||name,type,required,initial});
const select=(name:string,title:string,values:string[],required=true):Field=>({...field(name,title,'select',required),options:options(values)});
const reason=()=>field('reason','Razón documentada','textarea');
const dates=()=>[field('effective_from'),field('effective_to',undefined,'date',false),field('supersedes_ref','Versión precedente (referencia opaca)','text',false),reason()].map(f=>f.name==='effective_from'?{...f,type:'date' as const}:f);
function Facts({value,keys}:{value:Data;keys:string[]}){return <dl className={styles.facts}>{keys.filter(k=>value[k]!==undefined).map(k=><div key={k}><dt>{names[k]||k}</dt><dd className={k.includes('sha')||k.includes('fingerprint')?styles.hash:undefined}>{label(value[k])}</dd></div>)}</dl>;}
function Material({value,depth=0}:{value:unknown;depth?:number}){
  if(value===null||value===undefined)return <>—</>;
  if(depth>5)return <span>{text(value)}</span>;
  if(Array.isArray(value))return value.length?<ul className={styles.list}>{value.map((v,i)=><li key={i}><Material value={v} depth={depth+1}/></li>)}</ul>:<>Sin material.</>;
  if(typeof value==='object')return <dl>{Object.entries(object(value)).map(([k,v])=><div key={k}><dt className={styles.muted}>{names[k]||k}</dt><dd><Material value={v} depth={depth+1}/></dd></div>)}</dl>;
  return <>{typeof value==='boolean'?(value?'Sí':'No'):label(value)}</>;
}
function Causes({value}:{value:unknown}){return rows(value).length?<ul className={styles.list}>{rows(value).map((cause,i)=><li key={i}>{label(cause.code)} {publicRef(cause.employee_ref)&&<Link className={styles.link} href={`/panel/nomina/empleados/${cause.employee_ref}`}>Ver trabajador</Link>}<small className={styles.muted}> ({text(cause.code)})</small></li>)}</ul>:<p className={styles.muted}>Sin causas pendientes en esta consulta.</p>;}
function Pager({name,value,onPage}:{name:string;value:Data;onPage:(name:string,offset:number)=>void}){const offset=typeof value.offset==='number'?value.offset:0;return <div className={styles.toolbar}><button className={styles.button} disabled={offset===0} onClick={()=>onPage(name,Math.max(0,offset-20))}>Anterior</button><span className={styles.muted}>Página {Math.floor(offset/20)+1}</span><button className={styles.button} disabled={!value.has_more && rows(value.results).length<20} onClick={()=>onPage(name,offset+20)}>Siguiente</button></div>;}
function failure(error:unknown){if(error instanceof PayrollFailure)return `${error.message===error.code?(error.status===403?'Tu acceso no permite esta acción':error.status===404?'El recurso no está disponible':error.status===400?'Revisa los datos declarados':'No se pudo completar la acción'):error.message}${error.field?` · Campo: ${names[error.field]||error.field}`:''} (${error.code})${error.status===409?' Vuelve a consultar antes de decidir nuevamente.':''}`;return error instanceof Error?error.message:'No fue posible conectar. Vuelve a consultar.';}

export default function PayrollScreen({surface,resourceRef}:{surface:Surface;resourceRef?:string}){
  const {user,loading:sessionLoading}=usePanelUser();const search=useSearchParams();const router=useRouter();
  const employerParam=search.get('employer');const employer=surface==='employer'?resourceRef:publicRef(employerParam)?employerParam:undefined;
  const [offsets,setOffsets]=useState<Record<string,number>>({});const [generation,setGeneration]=useState('');const [reload,setReload]=useState(0);
  const key=`${user?.id}:${user?.organization_id}:${surface}:${resourceRef}:${employer}:${search.get('period_offset')}:${generation}:${JSON.stringify(offsets)}:${reload}`;
  const [loaded,setLoaded]=useState<{key:string;data:Data}>({key:'',data:{}});const [error,setError]=useState<{key:string;message:string}>({key:'',message:''});
  const [form,setForm]=useState<{key:string;spec:FormSpec}|null>(null);const [formError,setFormError]=useState('');const [busy,setBusy]=useState(false);const [preview,setPreview]=useState<{key:string;value:Data}|null>(null);
  const active=useRef<AbortController|null>(null);
  const internal=allowed(user),manager=privileged(user);
  const pageQuery=useCallback((name:string)=>`?limit=20&offset=${offsets[name]||0}`, [offsets]);
  useEffect(()=>{
    const controller=new AbortController();active.current=controller;
    async function load(){
      await Promise.resolve();if(!controller.signal.aborted)setBusy(false);
      if(!internal || surface!=='home'&&!publicRef(resourceRef))return;
      const get=(tail:string)=>request(route(tail),'GET',undefined,controller.signal);
      const pack:Data={};
      try{
        if(surface==='home')pack.employers=await get('employers/'+pageQuery('employers'));
        if(surface==='employer'){
          const all=await Promise.all([get('employers/'),get(`employers/${resourceRef}/employees/${pageQuery('employees')}`),get(`employers/${resourceRef}/concepts/${pageQuery('concepts')}`),get(`ui/employers/${resourceRef}/periods/${pageQuery('periods')}`),get(`social/employers/${resourceRef}/employer_versions/${pageQuery('profiles')}`),get(`social/employers/${resourceRef}/rule_sets/${pageQuery('rules')}`)]);
          [pack.employers,pack.employees,pack.concepts,pack.periods,pack.profiles,pack.rules]=all;
        }
        if(surface==='employee'){
          [pack.header,pack.employment,pack.compensation]=await Promise.all([get(`employees/${resourceRef}/`),get(`employees/${resourceRef}/employment/${pageQuery('employment')}`),get(`employees/${resourceRef}/compensation/${pageQuery('compensation')}`)]);
        }
        if(surface==='period'){
          [pack.header,pack.runs,pack.incidents,pack.imports]=await Promise.all([(employer?get(`ui/employers/${employer}/periods/?limit=100&offset=${Number(search.get('period_offset'))||0}`).then(v=>rows(v.results).find(p=>p.ref===resourceRef)||{}):get(`periods/${resourceRef}/`)),get(`ui/periods/${resourceRef}/runs/${pageQuery('runs')}`),get(`periods/${resourceRef}/incidents/${pageQuery('incidents')}`),get(`social/periods/${resourceRef}/imports/${pageQuery('imports')}`)]);
        }
        if(surface==='run'||surface==='social'){
          const root=surface==='run'?`runs/${resourceRef}/`:`social/runs/${resourceRef}/`;
          [pack.header,pack.results,pack.history,pack.related]=await Promise.all([get(surface==='run'?`ui/${root}`:root+'readiness/'),get(`ui/${root}employees/${pageQuery('results')}${generation?'&generation='+encodeURIComponent(generation):''}`),get(`ui/${root}history/${pageQuery('history')}`),get(surface==='run'?`social/payrolls/${resourceRef}/runs/${pageQuery('related')}`:root+`reconciliations/${pageQuery('related')}`)]);
        }
        if(surface==='import')pack.header=await get(`ui/social/imports/${resourceRef}/records/${pageQuery('records')}`);
        if(surface==='reconciliation')pack.header=await get(`ui/social/reconciliations/${resourceRef}/differences/${pageQuery('differences')}`);
        if(employer && surface==='period'){
          [pack.employees,pack.concepts]=await Promise.all([get(`employers/${employer}/employees/?limit=100`),get(`employers/${employer}/concepts/?limit=100`)]);
        }
        if(surface==='social')pack.imports=await get(`social/periods/${object(pack.header).period_ref}/imports/${pageQuery('imports')}`);
        if(surface==='reconciliation'){
          const parent=await get(`social/runs/${object(pack.header).run_ref}/readiness/`);pack.imports=await get(`social/periods/${parent.period_ref}/imports/${pageQuery('imports')}`);
        }
        if(!controller.signal.aborted){setLoaded({key,data:pack});setError({key,message:''});}
      }catch(e){if(!controller.signal.aborted){setLoaded({key,data:{}});setError({key,message:failure(e)});}}
    }
    void load();return()=>controller.abort();
  },[key,internal,surface,resourceRef,employer,generation,pageQuery,search]);
  const data=loaded.key===key?loaded.data:{};const header=object(data.header);const formSpec=form?.key===key?form.spec:null;
  const withContext=(path:string)=>path+(employer?`?employer=${employer}${path.includes('/periodos/')?'&period_offset='+String(offsets.periods||0):''}`:'');
  const open=(spec:FormSpec)=>{setFormError('');setForm({key,spec});};
  const onPage=(name:string,offset:number)=>setOffsets(v=>({...v,[name]:offset}));
  const refresh=()=>{setForm(null);setPreview(null);setReload(n=>n+1);};
  const employeeOptions=rows(object(data.employees).results).map(e=>({value:text(e.ref),label:`${text(e.employee_code)} · ${text(e.name)}`}));
  const conceptOptions=rows(object(data.concepts).results).map(c=>({value:text(c.ref),label:`${text(c.code)} · v${text(c.version)}`}));
  const evidenceOptions=rows(object(data.imports).results).filter(x=>x.physical_integrity==='CURRENT').map(x=>({value:text(x.ref),label:`${text(x.kind)} · ${text(x.filename)}`}));
  const rosterFields:Field[]=[{...field('employee_ref','Trabajador',employeeOptions.length?'select':'text'),options:employeeOptions},field('pay_units','Unidades de pago'),select('unit','Unidad',['DAY','HOUR','PERIOD'])];
  function action(actionName:string){const root=surface==='social'?'social/runs':'runs';const fields:Field[]=actionName==='review'?[select('decision','Decisión',['ACCEPT','RETURN']),reason()]:['approve','void'].includes(actionName)?[reason()]:[];open({title:{calculate:'Calcular',submit:'Enviar a revisión',review:'Revisar o devolver',approve:'Aprobar internamente',void:'Anular corrida'}[actionName]||actionName,path:refPath(root,resourceRef!,actionName+'/?response=compact'),fields,fixed:{expected_revision:header.revision},confirmed:['approve','void'].includes(actionName)});}
  async function submit(body:Data){if(!formSpec || busy)return;const controller=active.current;setBusy(true);setFormError('');
    try{
      if(body.content_base64 instanceof File){body={...body,content_base64:await encoded(body.content_base64),filename:'evidencia.json'};}
      if(formSpec.previewPath){
        const material:Data=formSpec.path.includes('employer_versions')?{registration:body.registration,classification:body.classification}:{handler:body.handler,incident_policy:body.incident_policy,required_identifiers:body.required_identifiers,components:body.components};
        const normalized=await request(formSpec.previewPath,'POST',{kind:formSpec.path.includes('employer_versions')?'employer_versions':'rule_sets',material},controller?.signal);
        const keep=['code','effective_from','effective_to','supersedes_ref','reason','source_kind','source_reference','source_version'];body={...Object.fromEntries(keep.filter(k=>body[k]!==undefined).map(k=>[k,body[k]])),material:normalized.material,source_sha256:normalized.source_sha256};
      }
      if(formSpec.kind==='download'){await download(formSpec.path,resourceRef!,'CAROVA_SIDEIMSS_PREPARATION_PACKAGE',body,controller?.signal);if(!controller?.signal.aborted){setForm(null);setPreview(null);setReload(n=>n+1);}return;}
      const result=await request(formSpec.path,formSpec.method||'POST',body,controller?.signal);
      if(controller?.signal.aborted)return;
      setForm(null);
      if(formSpec.kind==='preview'){setPreview({key,value:result});return;}
      const ref=result.ref;
      let target='';
      if(publicRef(ref)){
        if(/\/employers\/[^/]+\/employees\//.test(formSpec.path))target='empleados';
        else if(/\/employers\/[^/]+\/periods\//.test(formSpec.path))target='periodos';
        else if(/\/social\/payrolls\/[^/]+\/runs\//.test(formSpec.path))target='seguridad-social';
        else if(/\/periods\/[^/]+\/runs\//.test(formSpec.path))target='corridas';
        else if(formSpec.path.includes('/imports/'))target='importaciones';
        else if(formSpec.path.includes('/reconciliations/'))target='conciliaciones';
      }
      if(target)router.push(withContext(`/panel/nomina/${target}/${ref}`));else refresh();
    }catch(e){if(!controller?.signal.aborted){setFormError(failure(e));if(e instanceof PayrollFailure&&[403,404,409].includes(e.status)){setForm(null);setError({key,message:failure(e)});setLoaded({key,data:{}});}}}
    finally{if(!controller?.signal.aborted)setBusy(false);}
  }
  const table=(title:string,name:string,columns:string[],target?:string,extra?:(row:Data)=>React.ReactNode)=>{const envelope=object(data[name]);const list=rows(envelope.results);return <section className={styles.section} key={name}><h2>{title}</h2>{list.length?<table className={styles.table}><thead><tr>{columns.map(c=><th scope="col" key={c}>{names[c]||c}</th>)}<th scope="col">Detalle</th></tr></thead><tbody>{list.map((row,i)=><tr key={text(row.ref)||i}>{columns.map(c=><td key={c}>{label(row[c])}</td>)}<td>{target&&publicRef(row.ref)&&<Link className={styles.link} href={withContext(`/panel/nomina/${target}/${row.ref}`)}>Abrir</Link>}{extra?.(row)}</td></tr>)}</tbody></table>:<p className={styles.empty}>No hay {title.toLowerCase()} disponibles en esta página.</p>}<Pager name={name} value={envelope} onPage={onPage}/></section>;};
  function version(kind:'employment'|'compensation'){
    const last=rows(object(data[kind]).results).sort((a,b)=>Number(b.version)-Number(a.version))[0];
    const fields=kind==='employment'?[field('position'),field('work_schedule'),select('salary_type','Tipo salarial',['FIXED','VARIABLE','MIXED']),select('status','Estado laboral',['ACTIVE','ENDED'],false)]:[field('amount'),select('unit','Unidad',['DAY','HOUR','PERIOD']),field('sbc_amount','SBC declarado','text',false),select('sbc_provenance','Origen del SBC',['NOT_DECLARED','DECLARED']),field('sbc_source','Fuente del SBC','text',false)];
    open({title:kind==='employment'?'Crear versión laboral':'Crear versión de compensación',path:refPath('employees',resourceRef!,kind+'/'),fields:[...dates().map(f=>f.name==='supersedes_ref'?{...f,initial:last?.ref}:f),...fields],confirmed:true});
  }
  function ssVersion(kind:'employer_versions'|'rule_sets'){
    const specific:Field[]=kind==='employer_versions'?[field('registration','Registro declarado'),field('classification','Clasificación declarada')]:[select('handler','Regla configurada',['SBC_UNITS_RATES','UNCONFIGURED']),select('incident_policy','Política de incidencias',['NO_EFFECT','UNCONFIGURED']),{...field('required_identifiers','Identificadores requeridos','refs'),options:options(['nss','rfc','curp'])},{...field('components','Componentes declarados','records'),columns:[field('component_code','Código'),field('label','Nombre'),select('unit','Unidad',['DAY','HOUR','PERIOD']),field('employee_rate','Tasa trabajador configurada'),field('employer_rate','Tasa empleador configurada')]}];
    open({title:kind==='employer_versions'?'Versionar perfil patronal':'Versionar reglas internas',path:refPath('social/employers',resourceRef!,kind+'/'),previewPath:refPath('ui/social/employers',resourceRef!,'configuration-preview/'),fields:[field('code'),...dates(),select('source_kind','Origen declarado',['INTERNAL_CONFIGURED','DECLARED','OFFICIAL_IMPORTED']),field('source_reference'),field('source_version'),...specific],confirmed:true});
  }
  function packageAction(kind:'preview'|'download'){open({title:kind==='preview'?'Preparación SIDEIMSS':'Descargar paquete interno SIDEIMSS',path:refPath(kind==='preview'?'ui/social/runs':'social/runs',resourceRef!,kind==='preview'?'preparation/':'sideimss_export/'),fields:[{...field('reconciliation_refs','Conciliaciones vigentes','refs'),options:rows(object(data.related).results).map(x=>({value:text(x.ref),label:`${text(x.ref)} · ${label(x.currentness)} · abiertas ${text(x.open_differences)}`}))}],kind});}
  if(sessionLoading)return <section className={styles.root} aria-busy="true">Cargando sesión…</section>;
  if(!internal)return <section className={styles.root}><h1>Nómina</h1><p role="alert">Tu acceso no permite operar Nómina.</p></section>;
  if(surface!=='home'&&!publicRef(resourceRef))return <section className={styles.root}><h1>Nómina</h1><p role="alert">El recurso no está disponible.</p></section>;
  const pending=loaded.key!==key&&error.key!==key;
  return <section className={styles.root} aria-busy={pending||busy}>
    <header className={styles.header}><div>{surface!=='home'&&<Link className={styles.link} href="/panel/nomina">Nómina</Link>}{employer&&surface!=='employer'&&<> · <Link className={styles.link} href={`/panel/nomina/empleadores/${employer}`}>Empleador</Link></>}<h1>{titles[surface]}</h1></div><button className={styles.button} onClick={refresh} disabled={busy}>Volver a consultar</button></header>
    <Alert title="Preparación interna del despacho" tone="warning"><p>Aprobado significa aprobado internamente; no equivale a pago, timbrado ni presentación IMSS/SUA/SIDEIMSS. Reglas oficiales no configuradas.</p></Alert>
    <details><summary>Cómo preparar el trabajo</summary><ol><li>Configura trabajador y material declarado.</li><li>Crea periodo y corrida con población explícita.</li><li>Calcula, revisa y aprueba internamente.</li><li>Prepara seguridad social con reglas configuradas.</li><li>Importa y concilia evidencias técnicas; prepara los JSON internos.</li></ol></details>
    {pending&&<p role="status">Cargando material autorizado…</p>}{error.key===key&&error.message&&<p role="alert" className={styles.alert}>{error.message}</p>}
    {loaded.key===key&&Object.keys(data).length>0&&<>
    {surface==='home'&&<>{table('Empleadores','employers',['name'],'empleadores')}<p className={styles.muted}>Abre un empleador para consultar trabajadores, periodos, corridas y seguridad social. Los empleadores corresponden a clientes existentes autorizados.</p></>}
    {surface==='employer'&&<>
      <p>{text(rows(object(data.employers).results).find(x=>x.ref===resourceRef)?.name)}</p>
      <div className={styles.toolbar}><button className={styles.button} onClick={()=>open({title:'Añadir trabajador',path:refPath('employers',resourceRef!,'employees/'),fields:[field('employee_code'),field('name'),field('rfc',undefined,'text',false),field('curp',undefined,'text',false),field('nss',undefined,'text',false)]})}>Añadir trabajador</button>{manager&&<><button className={styles.button} onClick={()=>open({title:'Crear periodo',path:refPath('employers',resourceRef!,'periods/'),fields:[field('start',undefined,'date'),field('end',undefined,'date'),field('payment_date',undefined,'date'),select('period_type','Tipo de periodo',['WEEKLY','BIWEEKLY','SEMI_MONTHLY','MONTHLY','EXTRA']),select('calculation_scope','Alcance',['INTERNAL_CONFIGURED','REGULATORY_PENDING']),field('required_concepts','Códigos requeridos, separados por coma','list'),{...field('required_identifiers','Identificadores requeridos','refs',false),options:options(['rfc','curp','nss'])},field('scope_reason','Razón del alcance','textarea')],confirmed:true})}>Crear periodo</button><button className={styles.button} onClick={()=>open({title:'Versionar concepto',path:refPath('employers',resourceRef!,'concepts/'),fields:[field('code'),field('name'),...dates(),select('kind','Tipo',['PERCEPTION','DEDUCTION','OTHER']),select('net_effect','Efecto interno',['ADD','SUBTRACT','INFORMATIONAL']),select('rule','Regla configurada',['COMPENSATION_UNITS','DECLARED_AMOUNT','QUANTITY_RATE','UNCONFIGURED']),select('unit','Unidad',['DAY','HOUR','PERIOD','UNIT','AMOUNT']),field('rate','Tasa configurada','text',false),select('source_kind','Origen',['INTERNAL_CONFIGURATION','DECLARED_VALUE','OFFICIAL_REFERENCE']),field('source_reference'),field('source_version')],confirmed:true})}>Versionar concepto</button><button className={styles.button} onClick={()=>ssVersion('employer_versions')}>Perfil patronal</button><button className={styles.button} onClick={()=>ssVersion('rule_sets')}>Reglas de seguridad social</button></>}</div>
      {table('Trabajadores','employees',['employee_code','name','status'],'empleados')}{table('Periodos','periods',['start','end','status','calculation_scope'],'periodos')}{table('Conceptos','concepts',['code','version','rule','effective_from'])}
      {(['profiles','rules'] as const).map(name=>table(name==='profiles'?'Perfiles patronales':'Reglas configuradas',name,['code','version','status','effective_from'],undefined,row=><><details><summary>Material y origen</summary><Material value={row}/></details>{manager&&row.status==='APPROVED'&&<button className={styles.button} onClick={()=>open({title:'Retirar versión',path:refPath(name==='profiles'?'social/employer_versions':'social/rules',text(row.ref),'withdraw/'),fields:[reason()],fixed:{expected_revision:row.revision},confirmed:true})}>Retirar</button>}</>))}
    </>}
    {surface==='employee'&&<>
      <section className={styles.section}><Facts value={header} keys={['employee_code','name','status','rfc','curp','nss']}/><div className={styles.toolbar}><button className={styles.button} onClick={()=>open({title:'Actualizar perfil',path:refPath('employees',resourceRef!),method:'PATCH',fixed:{expected_revision:header.revision},fields:[field('name',undefined,'text',true,header.name),field('rfc',undefined,'text',false,header.rfc),field('curp',undefined,'text',false,header.curp),field('nss',undefined,'text',false,header.nss),{...select('status','Estado',['ACTIVE','INACTIVE']),initial:header.status}],confirmed:true})}>Actualizar perfil</button>{manager&&<><button className={styles.button} onClick={()=>version('employment')}>Versión laboral</button><button className={styles.button} onClick={()=>version('compensation')}>Compensación / SBC declarado</button></>}</div></section>
      {table('Versiones laborales','employment',['version','effective_from','effective_to','position','status'],undefined,r=><details><summary>Origen y aprobación</summary><Material value={r}/></details>)}{table('Compensaciones','compensation',['version','effective_from','amount','unit','sbc_amount','sbc_provenance'],undefined,r=><details><summary>Origen y aprobación</summary><Material value={r}/></details>)}<p className={styles.muted}>La vigencia depende del periodo. Consulta incidencias y participación desde el periodo y su corrida; no se infiere un SBC ni se altera historia aprobada.</p>
    </>}
    {surface==='period'&&<>
      <section className={styles.section}><Facts value={header} keys={['start','end','payment_date','period_type','status','calculation_scope','scope_reason']}/><Material value={{required_concepts:header.required_concepts,required_identifiers:header.required_identifiers}}/></section>
      <div className={styles.toolbar}><button className={styles.button} onClick={()=>open({title:'Crear corrida con población explícita',path:refPath('periods',resourceRef!,'runs/?response=compact'),fields:[{...field('employees','Población seleccionada','records'),columns:rosterFields}]})}>Crear corrida</button><button className={styles.button} onClick={()=>open({title:'Registrar incidencia',path:refPath('periods',resourceRef!,'incidents/'),fields:[{...field('employee_ref','Trabajador',employeeOptions.length?'select':'text'),options:employeeOptions},{...field('concept_ref','Concepto',conceptOptions.length?'select':'text'),options:conceptOptions},select('kind','Tipo',['INPUT','ABSENCE','DISABILITY','VACATION','OVERTIME','BONUS','COMMISSION','ADJUSTMENT','DISCOUNT']),field('date','Fecha','date'),select('unit','Unidad',['DAY','HOUR','PERIOD','UNIT','AMOUNT']),field('quantity','Cantidad','text',false),field('amount','Importe declarado','text',false),field('origin_reference','Referencia del origen'),field('note','Nota','textarea',false)]})}>Registrar incidencia</button><button className={styles.button} onClick={()=>open({title:'Importar evidencia técnica',path:refPath('social/periods',resourceRef!,'imports/?response=compact'),fixed:{parser_code:'CAROVA_CANONICAL_EXTERNAL_V1'},fields:[select('kind','Tipo',['SUA','EMA','EBA']),field('source_reference'),{...field('content_base64','JSON técnico CAROVA','file'),help:'Hasta 2 MiB. No admite un archivo oficial SUA ni otro formato.'}],confirmed:true})}>Importar JSON técnico</button></div>
      {table('Corridas','runs',['state','generation','revision'],'corridas')}{table('Incidencias','incidents',['concept_code','kind','date','quantity','amount','state'],undefined,r=>r.state==='CONFIRMED'&&<button className={styles.button} onClick={()=>open({title:'Anular incidencia',path:refPath('incidents',text(r.ref),'void/'),fixed:{expected_revision:r.revision},fields:[reason()],confirmed:true})}>Anular</button>)}{table('Evidencias importadas','imports',['kind','filename','physical_integrity'],'importaciones')}
    </>}
    {(surface==='run'||surface==='social')&&<>
      <section className={styles.section}><Facts value={header} keys={['state','currentness','generation','revision','currency','approved_by','approved_at']}/><h2>Importes internos</h2><Facts value={object(header.totals)} keys={Object.keys(object(header.totals))}/><h3>Material y revisión</h3><Causes value={header.calculation_causes}/><h3>Para aprobación</h3><Causes value={header.approval_causes}/></section>
      <div className={styles.toolbar}>{['DRAFT','CALCULATED'].includes(text(header.state))&&<><button className={styles.button} disabled={!header.calculation_ready} onClick={()=>action('calculate')}>Calcular</button>{surface==='run'&&<button className={styles.button} onClick={()=>open({title:'Cambiar población',path:refPath('runs',resourceRef!,'?response=compact'),method:'PATCH',fixed:{expected_revision:header.revision},fields:[{...field('employees','Población','records',true,header.roster),columns:rosterFields}],confirmed:true})}>Cambiar población</button>}</>}{header.state==='CALCULATED'&&<button className={styles.button} disabled={header.currentness!=='CURRENT'} onClick={()=>action('submit')}>Enviar a revisión</button>}{header.state==='PENDING_REVIEW'&&<button className={styles.button} onClick={()=>action('review')}>Revisar / devolver</button>}{manager&&header.state==='PENDING_REVIEW'&&<button className={styles.button} disabled={!header.approval_ready} onClick={()=>action('approve')}>Aprobar internamente</button>}{manager&&header.state!=='VOID'&&<button className={styles.button} onClick={()=>action('void')}>Anular</button>}</div>
      <section className={styles.section}><h2>Resultados por trabajador</h2>{surface==='social'&&<details><summary>Reglas aplicadas y provenance</summary><Material value={object(data.results).configuration}/></details>}<label htmlFor="payroll-generation">Generación</label><select id="payroll-generation" value={generation} onChange={e=>{setGeneration(e.target.value);setOffsets(v=>({...v,results:0}));}}><option value="">Actual</option>{rows(object(data.history).results).map(x=><option value={text(x.generation)} key={text(x.generation)}>Generación {text(x.generation)} · {label(x.selection_label)}</option>)}</select><p><span className={styles.badge}>{label(object(data.results).currentness)}</span></p>{rows(object(data.results).results).length?rows(object(data.results).results).map(result=><article key={text(result.ref)}><h3>{text(object(object(result.snapshot).employee).name)} · <Link className={styles.link} href={withContext(`/panel/nomina/empleados/${result.employee_ref}`)}>Trabajador</Link></h3><Facts value={object(result.totals)} keys={Object.keys(object(result.totals))}/><details><summary>Líneas, componentes y material de origen</summary><Material value={{lines:result.lines,components:result.components,snapshot:result.snapshot}}/></details></article>):<p className={styles.empty}>Sin resultados; consulta el material faltante antes de calcular.</p>}<Pager name="results" value={object(data.results)} onPage={onPage}/></section>
      {table('Historia de cálculo','history',['generation','at','actor','fingerprint'])}
      {surface==='run'&&<>{header.state==='APPROVED'&&<button className={styles.button} onClick={()=>open({title:'Crear seguridad social',path:refPath('social/payrolls',resourceRef!,'runs/?response=compact'),fields:[field('employer_code','Código de perfil patronal'),field('rule_code','Código de reglas configuradas')]})}>Preparar seguridad social</button>}{table('Seguridad social','related',['state','currentness','generation'],'seguridad-social')}</>}
      {surface==='social'&&<>
        {table('Conciliaciones','related',['currentness','open_differences','resolved_differences'],'conciliaciones')}{table('Fuentes del periodo','imports',['kind','filename','physical_integrity'],'importaciones')}
        <div className={styles.toolbar}><button className={styles.button} onClick={()=>open({title:'Crear conciliación',path:refPath('social/runs',resourceRef!,'reconciliations/?response=compact'),fields:[{...field('source_refs','Fuentes del mismo periodo','refs'),options:evidenceOptions}]})}>Crear conciliación</button><button className={styles.button} onClick={()=>packageAction('preview')}>SIDEIMSS PREPARATION</button><button className={styles.button} disabled={header.state!=='APPROVED'||rows(header.calculation_causes).length>0} onClick={async()=>{const controller=active.current;setBusy(true);try{await download(refPath('social/runs',resourceRef!,'sua_export/'),resourceRef!,'CAROVA_SUA_PREPARATION_DATA',undefined,controller?.signal);}catch(e){if(!controller?.signal.aborted){setLoaded({key,data:{}});setError({key,message:failure(e)});}}finally{if(!controller?.signal.aborted)setBusy(false);}}}>Descargar preparación SUA · JSON interno</button><button className={styles.button} onClick={()=>packageAction('download')}>Descargar preparación SIDEIMSS · JSON interno</button></div>
      </>}
    </>}
    {surface==='import'&&<section className={styles.section}><Facts value={header} keys={['kind','filename','status','physical_integrity','sha256','parser_code','parser_version','uploaded_by','uploaded_at','official_format_status']}/><h2>Filas normalizadas</h2>{rows(header.results).length?rows(header.results).map(row=><details key={text(row.ref)}><summary>Fila {text(row.row_index)} · {text(row.component_code)} · {label(row.currentness)}</summary><Material value={row}/></details>):<p className={styles.empty}>Sin filas normalizadas.</p>}<Pager name="records" value={header} onPage={onPage}/></section>}
    {surface==='reconciliation'&&<section className={styles.section}><Facts value={header} keys={['currentness','open_differences','resolved_differences','comparison','effective_fingerprint']}/><Causes value={header.causes}/><h2>Diferencias</h2><p className={styles.muted}>La conciliación no modifica ni aprueba automáticamente la nómina. Las identidades ambiguas requieren revisión explícita.</p>{rows(header.results).length?<table className={styles.table}><thead><tr>{['kind','component_code','carova_value','external_value','difference','state'].map(c=><th key={c} scope="col">{names[c]}</th>)}<th scope="col">Resolución</th></tr></thead><tbody>{rows(header.results).map(row=><tr key={text(row.ref)}>{['kind','component_code','carova_value','external_value','difference','state'].map(c=><td key={c}>{label(row[c])}</td>)}<td><details><summary>Fuente, detalle e historia</summary><Material value={{source_refs:row.source_refs,details:row.details,resolution_history:row.resolution_history}}/></details>{manager&&row.state==='OPEN'&&header.currentness==='CURRENT'&&<button className={styles.button} onClick={()=>open({title:'Documentar resolución',path:refPath('social/differences',text(row.ref),'resolve/?response=compact'),fixed:{expected_revision:row.revision},fields:[select('resolution','Decisión',['REQUEST_EVIDENCE',...(['VALUE_DIFFERENCE','MISSING_IN_EXTERNAL','MISSING_IN_CAROVA'].includes(text(row.kind))?['CONFIRM_DOCUMENTED_VARIANCE']:[])]),reason(),{...field('evidence_refs','Evidencia vigente del periodo','refs'),options:evidenceOptions}],confirmed:true})}>Documentar resolución</button>}</td></tr>)}</tbody></table>:<p className={styles.empty}>Sin diferencias en esta página.</p>}<Pager name="differences" value={header} onPage={onPage}/>{table('Evidencias disponibles','imports',['kind','filename','physical_integrity'],'importaciones')}</section>}
    </>}
    {preview?.key===key&&<section className={styles.section} role="status"><h2>SIDEIMSS PREPARATION</h2><Facts value={preview.value} keys={['readiness','official_format_status','manifest_sha256']}/><Material value={preview.value.counts}/><Causes value={preview.value.causes}/>{preview.value.causes_truncated===true&&<p>Se muestran las primeras 100 causas de {text(preview.value.cause_count)}; la preparación considera todas.</p>}</section>}
    {formSpec&&<PayrollFormDialog key={formSpec.title} spec={formSpec} busy={busy} error={formError} onClose={()=>setForm(null)} onSubmit={submit}/>}
  </section>;
}
