import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
// Execute the production client with a controlled shared apiFetch seam. No new dependency.
const source=fs.readFileSync(new URL('../lib/payroll/client.ts',import.meta.url),'utf8').replace(/import[^;]+;/g,'');
const model=await import('../lib/payroll/model.ts');let calls=[],response;
const fake=async(path,options)=>{calls.push({path,options});return response;};
const exports={};const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
new Function('exports','apiFetch','object','publicRef','label',compiled)(exports,fake,model.object,model.publicRef,model.label);
const ref='f336d034-d3db-4543-9ac3-53890e4e0502';
test('Payroll client preserves decimal strings and explicit compact mutation',async()=>{response=new Response('{}',{status:200});const body={employees:[{employee_ref:ref,pay_units:'15.000000',unit:'DAY'}]};await exports.request(`/api/carova/payroll/periods/${ref}/runs/?response=compact`,'POST',body);assert.deepEqual(JSON.parse(calls.at(-1).options.body),body);assert.equal(calls.at(-1).options.method,'POST');});
test('Payroll client fails closed for paths and numeric refs',async()=>{for(const path of ['https://evil.test','/api/other/','/api/carova/payroll/../secret','/api/carova/payroll/runs/1/'])await assert.rejects(()=>exports.request(path));assert.throws(()=>exports.refPath('runs','1'));});
test('Payroll 409 remains typed, no mutation retry and support code retained',async()=>{calls=[];response=new Response(JSON.stringify({code:'CALCULATION_STALE',causes:[{code:'SOURCE_CHANGED'}]}),{status:409});await assert.rejects(()=>exports.request(`/api/carova/payroll/runs/${ref}/approve/`,'POST',{}),e=>e instanceof exports.PayrollFailure&&e.status===409&&e.code==='CALCULATION_STALE');assert.equal(calls.length,1);});
test('Payroll downloads use GET SUA / POST SIDEIMSS, canonical safe name and revoke URL',async()=>{let revoked=[],appended=[],clicks=0;global.document={body:{appendChild(a){appended.push(a);}},createElement(){return {click(){clicks++;},remove(){}};}};const create=URL.createObjectURL,revoke=URL.revokeObjectURL;URL.createObjectURL=()=> 'blob:synthetic';URL.revokeObjectURL=u=>revoked.push(u);
try{response=new Response('{}');await exports.download(`/api/carova/payroll/social/runs/${ref}/sua_export/`,ref,'CAROVA_SUA_PREPARATION_DATA');assert.equal(calls.at(-1).options.method,'GET');assert.equal(appended[0].download,`CAROVA_SUA_PREPARATION_DATA_${ref}.json`);response=new Response('{}');await exports.download(`/api/carova/payroll/social/runs/${ref}/sideimss_export/`,ref,'CAROVA_SIDEIMSS_PREPARATION_PACKAGE',{reconciliation_refs:[ref]});assert.equal(calls.at(-1).options.method,'POST');assert.equal(clicks,2);assert.deepEqual(revoked,['blob:synthetic','blob:synthetic']);}finally{URL.createObjectURL=create;URL.revokeObjectURL=revoke;delete global.document;}});
test('Payroll upload rejects unsupported format and oversized file before encoding',async()=>{await assert.rejects(()=>exports.encoded(new File(['x'],'evidence.xls')));await assert.rejects(()=>exports.encoded(new File([new Uint8Array(2097153)],'evidence.json')));assert.equal(await exports.encoded(new File(['{}'],'evidence.json')),'e30=');});
