'use client';
import Link from 'next/link';
import CatalogActivation from './CatalogActivation';
import {useCallback,useEffect,useState} from 'react';
import PageHeader from '@/components/panel/PageHeader';
import StatusBadge from '@/components/panel/StatusBadge';
import {audit} from '@/lib/audit/client';
import {inbox,label} from '@/lib/audit/model';
import type {Engagement} from '@/lib/audit/model';
import './audit.css';
export default function ContextScreen({reference}:{reference:string}){
 const [data,setData]=useState<Engagement|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('all');
 const [defs,setDefs]=useState<{ref:string;code:string;name:string;version:number}[]>([]),[actors,setActors]=useState<{ref:string;name:string}[]>([]);
 const reload=useCallback(async()=>{const d=await audit.engagement(reference);setData(d);const catalog=await audit.definitions();setDefs(catalog.definitions);if(d.can_manage)setActors((await audit.bootstrap()).actors);},[reference]);
 useEffect(()=>{let active=true;audit.engagement(reference).then(async d=>{if(!active)return;setData(d);setDefs((await audit.definitions()).definitions);if(d.can_manage)setActors((await audit.bootstrap()).actors);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[reference]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await reload();}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar.');await reload().catch(()=>setData(null));}finally{setBusy(false);}}
 return <section className="audit"><Link href="/panel/encargos">Encargos</Link><PageHeader title={data?`Auditoría · ${data.name}`:'Auditoría'} description={data?`${data.client} · ${data.start} — ${data.end}`:'Contexto y papeles de trabajo'}/>{error&&<div role="alert" className="audit-error">{error}</div>}{!data&&!error&&<p role="status">Cargando contexto autorizado…</p>}{data&&<>
 {!data.contexts.length&&<section><h2>Contexto de auditoría</h2><p>No hay un contexto disponible en tu alcance.</p>{data.can_manage&&<button disabled={busy} onClick={()=>run(()=>audit.context({engagement_ref:reference,period_start:data.start,period_end:data.end,fiscal_year:Number(data.end.slice(0,4))}))}>Crear contexto para este periodo</button>}</section>}
 {data.contexts.map(c=><div key={c.ref} className="audit"><section><h2>Periodo auditado · {c.fiscal_year}</h2><p>{c.period_start} — {c.period_end} · {label(c.status)}</p><div className="audit-grid">{['PREPARER','REVIEWER','AUTHORIZER'].map(role=><div key={role}><strong>{label(role)}</strong><p>{c.team.filter(a=>a.role===role).map(a=>a.name).join(', ')||'Sin asignar'}</p></div>)}</div>
 {data.can_manage&&<details><summary>Asignaciones profesionales</summary><p>Tres personas distintas. El servidor valida cada asignación.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.assign(c.ref,{actor_ref:f.get('actor'),role:f.get('role'),active:true}));}}><label>Persona<select name="actor" required><option value="">Selecciona</option>{actors.filter(a=>!c.team.some(t=>t.ref===a.ref)).map(a=><option key={a.ref} value={a.ref}>{a.name}</option>)}</select></label><label>Función<select name="role">{['PREPARER','REVIEWER','AUTHORIZER'].map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><button disabled={busy}>Asignar</button></form></details>}
 </section><nav aria-label="Bandejas Audit"><button onClick={()=>setTab('all')} aria-pressed={tab==='all'}>Papeles disponibles</button>{c.roles.includes('REVIEWER')&&<button onClick={()=>setTab('review')} aria-pressed={tab==='review'}>Supervisión</button>}{c.roles.includes('AUTHORIZER')&&<button onClick={()=>setTab('authorize')} aria-pressed={tab==='authorize'}>Autorización</button>}</nav>
 <section><h2>{tab==='review'?'Bandeja de supervisión':tab==='authorize'?'Bandeja de autorización':'Papeles de trabajo'}</h2><p className="audit-muted">Avance basado en cobertura y pendientes comprobados. Sólo se muestran papeles accesibles.</p><div className="audit-grid">{inbox(c.papers,tab).map(p=><article key={p.ref}><h3><Link href={`/panel/auditoria/${p.ref}`}>{p.code} · {p.name}</Link></h3><p>{label(p.variant)} · {label(p.fund)} · {p.section==='GENERAL'?'General':p.section} · {p.instance}</p><StatusBadge label={label(p.status)} tone={p.state==='STALE'?'yellow':p.status==='AUTHORIZED'?'green':'blue'}/><p>{label(p.state)} · Revisión de edición {p.revision}</p><dl><dt>Elaboró</dt><dd>{p.preparer}</dd><dt>Revisó / asignado</dt><dd>{p.team.filter(t=>t.role==='REVIEWER').map(t=>t.name).join(', ')||'Sin asignar'}</dd><dt>Autorizó / asignado</dt><dd>{p.team.filter(t=>t.role==='AUTHORIZER').map(t=>t.name).join(', ')||'Sin asignar'}</dd><dt>Hallazgos</dt><dd>{p.findings?.length??'No disponibles'}</dd><dt>Pendientes</dt><dd>{p.procedures?.filter(x=>!x.complete).length??'Actualizar revisión'}</dd></dl>{p.samples?.map(s=><p key={s.ref}>Seleccionados: {s.coverage.selected_count} · Revisados: {s.coverage.reviewed_count} · Cobertura revisada: {s.coverage.reviewed_coverage_percentage??'No determinable'}%</p>)}</article>)}</div>{!inbox(c.papers,tab).length&&<p>No hay papeles disponibles en esta bandeja.</p>}</section>
 {c.roles.includes('PREPARER')&&<section><h2>Nuevo A-20</h2>{!defs.some(d=>d.code==='A-20')?<div><p>Activa el catálogo aprobado para crear A-20/A-21 en esta organización.</p><CatalogActivation onComplete={()=>void reload()}/></div>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.create(c.ref,{definition_ref:f.get('definition'),fund_key:f.get('fund'),section_key:'GENERAL',instance_key:f.get('instance')}));}}><label>Definición aprobada<select name="definition">{defs.filter(d=>d.code==='A-20').map(d=><option key={d.ref} value={d.ref}>{d.code} · {d.name} · v{d.version}</option>)}</select></label><label>Fondo<select name="fund"><option value="RF">Recursos Fiscales</option><option value="PARTICIPACIONES">Participaciones Federales</option></select></label><label>Identificación del papel<input name="instance" required maxLength={80}/></label><button disabled={busy}>Crear A-20</button></form>}</section>}
 </div>)}
 </>}</section>;
}
