'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import PageHeader from '@/components/panel/PageHeader';
import StatusBadge from '@/components/panel/StatusBadge';
import {audit,AuditError} from '@/lib/audit/client';
import {label,safeDownload,sourceName} from '@/lib/audit/model';
import type {Paper,Source,Artifact} from '@/lib/audit/model';
import ProcedureEditor from './ProcedureEditor';
import './audit.css';
import PresentationAction from '@/components/presentation/PresentationAction';
export default function PaperScreen({reference}:{reference:string}){
 const [p,setP]=useState<Paper|null>(null),[sources,setSources]=useState<Source[]>([]),[exports,setExports]=useState<Artifact[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[item,setItem]=useState('');
 const load=useCallback(async()=>{const row=await audit.paper(reference);const [s,a]=await Promise.all([audit.sources(row.context_ref),audit.exports(reference)]);return {row,s:s.sources,a:a.artifacts};},[reference]);
 const reload=useCallback(async()=>{const d=await load();setP(d.row);setSources(d.s);setExports(d.a);},[load]);
 useEffect(()=>{let active=true;load().then(d=>{if(active){setP(d.row);setSources(d.s);setExports(d.a);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[load]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await reload();}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar.');if(e instanceof AuditError){try{await reload();}catch{setP(null);setSources([]);setExports([]);}}}finally{setBusy(false);}}
 const selected=item||p?.samples?.flatMap(s=>s.items)[0]?.ref||'';
 const selectedItem=p?.samples?.flatMap(s=>s.items).find(i=>i.ref===selected);
 const base=p?.items?.find(i=>i.ref===selected)?.source;
 return <section className="audit"><Link href={p?`/panel/encargos/${p.engagement_ref}/auditoria`:'/panel/encargos'}>Volver al encargo</Link><PageHeader title={p?`${p.code} · ${p.name}`:'Papel de trabajo'} description={p?`${label(p.fund)} · ${p.section==='GENERAL'?'General':p.section} · ${p.instance}`:'Consulta de revisión autorizada'}/>{error&&<div role="alert" className="audit-error">{error}<p>Si este papel depende de A-20: el A-20 fuente debe estar autorizado y vigente. Si cambió, A-21 requiere una nueva revisión.</p></div>}{!p&&!error&&<p role="status">Comprobando alcance, evidencia y vigencia…</p>}{p&&<>
 <section><div className="audit-actions"><StatusBadge label={label(p.status)} tone={p.state==='STALE'?'yellow':p.status==='AUTHORIZED'?'green':'blue'}/><strong>{label(p.state)}</strong><span>Versión de edición {p.revision}</span><button disabled={busy} onClick={()=>run(reload)}>Actualizar</button></div>{p.state==='STALE'||p.status==='NEEDS_REVIEW'?<p className="audit-banner">Este papel cambió después de la revisión y debe revisarse nuevamente. Las decisiones históricas no acreditan el material actual.</p>:null}<div className="audit-grid">{['PREPARER','REVIEWER','AUTHORIZER'].map(role=><p key={role}><strong>{label(role)} / asignado</strong><br/>{role==='PREPARER'?p.preparer:p.team.filter(t=>t.role===role).map(t=>t.name).join(', ')||'Sin asignar'}</p>)}</div>{p.revision_ref&&<details><summary>Referencia exacta de revisión</summary><code>{p.revision_ref}</code></details>}</section>
 {p.code==='A-21'&&<section><h2>Dependencia del A-20</h2>{p.parents.map(r=><p key={r.revision_ref}><Link href={`/panel/auditoria/${r.paper_ref}/revision/${r.revision_ref}?from=${p.ref}`}>Abrir A-20 fuente</Link> · Revisión exacta {r.version} · Estado del vínculo: verificado al cargar<small><code>{r.revision_ref}</code></small></p>)}<p>Esta cédula conserva la revisión exacta de su padre; no sigue automáticamente una revisión posterior.</p>{p.vertical?.observations.map(f=><article key={f.ref}><h3>{f.condition}</h3><p>{f.criterion} · {label(f.status)}</p></article>)}</section>}
 {p.samples?.map(s=><section key={s.ref}><h2>Muestra · {s.key}</h2><div className="audit-grid">{[['universe','Universo declarado'],['selected','Seleccionados'],['reviewed','Revisados']].map(([key,title])=><article key={key}><h3>{title}</h3><p>{s.coverage[key+'_count']} elementos</p><p>Importe: {s.coverage[key+'_amount']??'No determinado'} {s.coverage.currency}</p>{key!=='universe'&&<p>Cobertura de importe: {s.coverage[key+'_coverage_percentage']??'No determinable'}%</p>}</article>)}</div><p className="audit-notice">Seleccionado no significa revisado. La cobertura revisada depende de procedimientos, evidencia y assertions vigentes.</p><div className="audit-actions">{s.items.map(i=><button key={i.ref} className={selected===i.ref?'audit-selected':''} onClick={()=>setItem(i.ref)}>{p.items?.find(x=>x.ref===i.ref)?.source.reference||'Elemento'} · {i.selected?'Seleccionado':'No seleccionado'}</button>)}</div>{p.actions.edit&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.mutate(p,{action:'sample_item',sample_ref:s.ref,source_ref:f.get('source'),selected:f.get('selected')==='on',reason:f.get('reason')}));}}><label>Expediente del universo<select name="source" required><option value="">Selecciona</option>{sources.filter(x=>x.kind==='CASE'&&!p.samples?.some(sample=>sample.items.some(i=>i.source_ref===x.ref))).map(x=><option key={x.ref} value={x.ref}>{sourceName(x)}</option>)}</select></label><label className="audit-check"><input type="checkbox" name="selected"/>Seleccionar para revisión</label><label>Motivo material de selección<input name="reason" required/></label><button disabled={busy}>Agregar elemento al universo</button></form>}</section>)}
 {p.actions.edit&&p.code==='A-20'&&<section><h2>Preparar muestra y procedimientos</h2>{!p.samples?.length&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.mutate(p,{action:'sample',sample_key:f.get('key'),currency:'MXN',reason:f.get('reason')}));}}><label>Clave de muestra<input name="key" required/></label><label>Alcance y método declarado<textarea name="reason" required/></label><button disabled={busy}>Crear muestra declarada</button></form>}<button disabled={busy} onClick={()=>run(()=>audit.action(p,'initialize-checks',{}))}>Inicializar procedimientos de los seleccionados</button></section>}
 {base&&<section><h2>Elemento de muestra</h2><dl><dt>Referencia interna CAROVA</dt><dd>{base.reference}</dd><dt>Concepto</dt><dd>{base.title}</dd><dt>Fecha</dt><dd>{base.date}</dd><dt>Importe fuente</dt><dd>{base.amount??'No determinado'}</dd></dl>{p.item_checks?.filter(c=>c.ref===selected).map(c=><details key={c.ref} open><summary>Campos contrastados con fuentes y assertions</summary><div className="audit-grid">{Object.entries(c.fields).map(([k,v])=><div key={k}><strong>{label(k)}</strong><p>{label(v.state)}{v.values?.map((x,n)=><small key={n}>{String(x.value??'No determinado')}</small>)}</p></div>)}</div></details>)}{p.actions.edit&&selectedItem&&<form key={p.revision} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.mutate(p,{action:'sample_select',ref:selected,selected:f.get('selected')==='on',reason:f.get('reason')}));}}><label className="audit-check"><input name="selected" type="checkbox" defaultChecked={selectedItem.selected}/>Seleccionado</label><label>Motivo material<input name="reason" defaultValue={selectedItem.reason} required/></label><p className="audit-banner">Cambiar selección o motivo retira las decisiones profesionales afectadas. Volver a seleccionar no las restaura.</p><button disabled={busy}>Actualizar selección</button></form>}</section>}
 {p.procedures&&<section><h2>Procedimientos y evidencia</h2>{p.procedures.filter(e=>p.code==='A-21'||e.target==='ITEM:'+selected.replaceAll('-','')).map(e=><ProcedureEditor key={e.ref} p={p} e={e} sources={sources} busy={busy} run={run}/>)}</section>}
 <section><h2>Fuentes disponibles · metadatos seguros</h2><details><summary>Ver fuentes en el alcance del encargo</summary>{sources.map(s=><article key={s.ref}><strong>{sourceName(s)}</strong><p>{label(s.kind)} · {s.metadata.mime||s.metadata.fields?.issuer_name||s.metadata.title}</p>{s.metadata.sha256&&<small>SHA-256: <code>{s.metadata.sha256}</code> · {s.metadata.size} bytes</small>}{s.download_url&&<button disabled={busy} onClick={()=>run(()=>audit.sourceDownload(s))}>Consultar documento</button>}{s.metadata.fields?.uuid&&<small>UUID fiscal: {s.metadata.fields.uuid}</small>}</article>)}</details></section>
 <section><h2>Hallazgos · estado actual</h2>{!p.findings?.length&&<p>No hay hallazgos disponibles. Esto por sí solo no acredita revisión completa.</p>}{p.findings?.map(f=><article key={f.ref}><h3>{f.condition}</h3><StatusBadge label={label(f.status)} tone={f.status==='CANDIDATE'?'yellow':'blue'}/><p>{f.criterion}</p><p>Procedimiento: {label(p.procedures?.find(e=>e.ref===f.execution_ref)?.code)} · Evidencia: {p.evidence?.find(e=>e.ref===f.evidence_ref)?.purpose||'Soporte vinculado'}</p><p>{f.amount??'Sin importe determinado'} {f.currency}</p>{p.actions.decide&&<form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void run(()=>audit.mutate(p,{action:'finding_decision',ref:f.ref,status:d.get('decision'),comment:d.get('comment')}));}}><label>Decisión de supervisión<select name="decision" required><option value="">Selecciona</option><option value="CONFIRMED">Confirmar</option><option value="DISMISSED">Descartar</option></select></label><label>Fundamento<textarea name="comment" required/></label><button disabled={busy}>Registrar decisión</button></form>}<details><summary>Historial de decisiones · no equivale a vigencia</summary>{f.history?.map((h,n)=><div className="audit-history" key={n}><p>{label(h.kind||h.status)} · {h.actor} · {h.timestamp}</p><p>{h.comment}</p>{h.base_revision_ref&&<small>Revisión: <code>{h.base_revision_ref}</code></small>}{h.material_fingerprint&&<small>Material: <code>{h.material_fingerprint}</code></small>}</div>)}</details></article>)}</section>
 {p.vertical&&<section><h2>Conclusión · {label(p.vertical.assessment)}</h2><h3>Borrador del sistema</h3><p>{p.vertical.draft.text}</p><h3>{label(p.vertical.conclusion_mode)}</h3>{p.actions.edit?<form key={p.revision} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.mutate(p,{action:'content',conclusion:f.get('conclusion')}));}}><label>Conclusión humana<textarea name="conclusion" defaultValue={p.conclusion} required/></label><button disabled={busy}>Guardar conclusión</button></form>:<p>{p.conclusion||'Sin conclusión humana'}</p>}</section>}
 <section><h2>Revisión y autorización</h2>{!p.ready&&<div className="audit-banner"><p>Faltan requisitos para enviar a revisión:</p><ul>{p.pending_reasons?.map((reason,n)=><li key={n}>{reason}</li>)}{!p.samples?.length&&p.code==='A-20'&&<li>Muestra y procedimientos inicializados.</li>}{p.procedures?.filter(e=>!e.complete).map(e=><li key={e.ref}>{label(e.code)}: {label(e.pending||'INCOMPLETE')}</li>)}{p.findings?.filter(f=>f.status==='CANDIDATE').map(f=><li key={f.ref}>Decisión del hallazgo: {f.condition}</li>)}</ul></div>}{['SUBMIT','REVIEW','RETURN','AUTHORIZE','REOPEN'].filter(a=>p.actions[a]).map(a=><form key={a} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.transition(p,a,String(f.get('reason'))));}}><label>Motivo de «{label(a)}»<textarea name="reason" required/></label><button disabled={busy}>{label(a)}</button></form>)}{p.events?.map(e=><p key={e.ref}>{label(e.decision)} · {e.actor} · {e.timestamp} · {e.reason} · {e.current?'Vigente':'Histórico'}</p>)}</section>
 <section><h2>Archivos PDF / XLSX</h2>{['DRAFT','RETURNED','NEEDS_REVIEW'].includes(p.status)&&<p className="audit-banner">BORRADOR / NO AUTORIZADO. Un archivo de trabajo no representa autorización profesional.</p>}{p.actions.export&&<div className="audit-actions">{['PDF','XLSX'].map(format=><button key={format} disabled={busy} onClick={()=>run(()=>audit.action(p,'exports',{format,revision_ref:p.revision_ref}))}>Generar {format}</button>)}</div>}{exports.map(a=><article key={a.ref}><strong>{a.name}</strong><p>{label(a.state)} · {a.manifest?.format} · {a.manifest?.generated_at} · {label(a.manifest?.review_state)}</p>{a.state==='HISTORICAL'&&<p>Existe un archivo histórico, pero el papel cambió o el archivo ya no es verificable como actual.</p>}<small>Revisión: <code>{a.revision_ref||a.manifest?.revision_ref}</code></small>{a.sha256&&<small>SHA-256: <code>{a.sha256}</code> · {a.size} bytes</small>}{safeDownload(a)&&<button disabled={busy} onClick={()=>run(()=>audit.download(a))}>Descargar {a.manifest?.format}</button>}{safeDownload(a)&&a.manifest?.format==='PDF'&&a.manifest?.review_state==='AUTHORIZED'&&<PresentationAction source={{kind:'auditoria',ref:a.ref}}/>}</article>)}</section>
 {p.actions.a21&&<section><h2>Crear A-21 desde esta revisión autorizada</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>audit.a21(p,String(f.get('instance'))));}}><label>Identificación A-21<input name="instance" required/></label><button disabled={busy}>Crear A-21 con padre exacto</button></form></section>}{p.related.map(r=><Link key={r.ref} href={`/panel/auditoria/${r.ref}`}>Abrir {r.code} · {r.name}</Link>)}
 </>}</section>;
}
