'use client';
import {useState} from 'react';
import {audit} from '@/lib/audit/client';
import {label,sourceName} from '@/lib/audit/model';
import type {Paper,Procedure,Source} from '@/lib/audit/model';
export type Run=(work:()=>Promise<unknown>)=>Promise<void>;
export default function ProcedureEditor({p,e,sources,busy,run}:{p:Paper;e:Procedure;sources:Source[];busy:boolean;run:Run}){
 const spec=p.procedure_specs[e.code],links=p.evidence?.filter(l=>l.execution_ref===e.ref)||[];
 const [mode,setMode]=useState(''),[outcome,setOutcome]=useState('');
 const fields=Object.entries(p.vertical?.field_contract||{}).filter(([k,f])=>f.procedure===e.code&&k!=='CASE_REFERENCE');
 return <details><summary>{label(e.code)} · {e.complete?'Completo':label(e.pending||'INCOMPLETE')}</summary><p>{label(e.completion)} · {label(e.evaluation.state)} · {label(e.outcome)}</p>{spec?.external&&!e.complete&&<p className="audit-banner">Verificación externa pendiente. Registra el resultado y soporte obtenido por el auditor; esta pantalla no consulta servicios externos.</p>}<p>{e.evaluation.reason}</p>
 <h4>Evidencia vinculada</h4>{links.length?links.map(l=><p key={l.ref}>{label(l.kind)} · {sourceName(sources.find(s=>s.ref===l.source_ref)||{ref:l.source_ref,kind:l.kind,metadata:{}})} · {label(l.evaluation.state)} · {l.purpose} {p.actions.edit&&<button disabled={busy} onClick={()=>run(()=>audit.mutate(p,{action:'evidence_unlink',ref:l.ref}))}>Retirar vínculo</button>}</p>):<p>No hay soporte vinculado.</p>}
 {e.assertion&&<details><summary>Assertion humana registrada</summary><p>{e.assertion.reason} · {e.assertion.timestamp}</p><dl>{Object.entries(e.assertion.fields||{}).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{String(v??'No determinado')}</dd></div>)}</dl></details>}
 {p.actions.edit&&<><form onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);const source=sources.find(s=>s.ref===f.get('source'));if(!source)return;void run(()=>audit.mutate(p,{action:'evidence',execution_ref:e.ref,evidence_key:f.get('key'),purpose:f.get('purpose'),source_kind:source.kind,source_ref:source.ref,state:'VALUE',value:true,reason:f.get('purpose')}));}}><label>Fuente disponible<select name="source" required><option value="">Selecciona un soporte</option>{sources.filter(s=>spec.source_types.includes(s.kind)).map(s=><option key={s.ref} value={s.ref}>{label(s.kind)} · {sourceName(s)}</option>)}</select></label><label>Clave de vínculo<input name="key" defaultValue={links.some(l=>l.key==='SUPPORT')?'':'SUPPORT'} required/></label><label>Propósito del soporte<input name="purpose" required/></label><button disabled={busy}>Vincular evidencia</button></form>
 <form key={`${e.ref}-${p.revision}`} onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);const values:Record<string,unknown>={};if(mode==='VALUE'||mode==='PROVEN_ABSENT')for(const [k,s] of fields){const raw=String(f.get(k)||'');if(raw!=='')values[k]=s.type==='boolean'?raw==='true':raw;}void run(()=>audit.action(p,'assertions',{execution_ref:e.ref,state:mode,value:mode==='VALUE'?true:null,outcome:mode==='NOT_APPLICABLE'?'NOT_APPLICABLE_DEMONSTRATED':mode==='UNKNOWN'?'UNKNOWN':outcome,reason:f.get('reason'),fields:values}));}}>
 <h4>Constatación humana</h4><label>Aplicabilidad y evidencia<select required value={mode} onChange={ev=>setMode(ev.target.value)}><option value="">Selecciona una decisión explícita</option><option value="VALUE">Aplica · valor demostrado</option><option value="PROVEN_ABSENT">Aplica · ausencia demostrada</option>{spec.conditional&&<option value="NOT_APPLICABLE">No aplica demostrado</option>}<option value="UNKNOWN">No se puede determinar</option></select></label>{['VALUE','PROVEN_ABSENT'].includes(mode)&&<><label>Resultado profesional<select required value={outcome} onChange={ev=>setOutcome(ev.target.value)}><option value="">Selecciona</option><option value="NO_FINDING_DEMONSTRATED">Sin observación demostrada</option><option value="WITH_FINDING">Con hallazgo</option><option value="UNKNOWN">No determinado</option></select></label><div className="audit-grid">{fields.map(([k,s])=><label key={k}>{label(k)}{Boolean(s.automatic)&&<small>También contrastado con la fuente; no sobreescribe su valor.</small>}{s.type==='boolean'?<select name={k} defaultValue=""><option value="">No determinado</option><option value="true">Sí</option><option value="false">No</option></select>:<input name={k} type={s.type==='date'?'date':'text'} inputMode={s.type==='decimal'?'decimal':undefined} defaultValue={String(e.assertion?.fields?.[k]??'')}/>}</label>)}</div></>}
 <label>Comentario / fundamento humano<textarea name="reason" required/></label><button disabled={busy||!mode}>Registrar assertion</button><p className="audit-muted">El servidor registra autor, fecha y vínculo con evidencia. No se firma ni revisa automáticamente.</p></form>
 {links.length>0&&<details><summary>Registrar hallazgo candidato</summary><form onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);void run(()=>audit.mutate(p,{action:'finding',finding_key:f.get('key'),execution_ref:e.ref,evidence_ref:f.get('evidence'),condition:f.get('condition'),criterion:f.get('criterion'),amount:f.get('amount')||null,currency:f.get('amount')?'MXN':'',population_context:f.get('population'),comment:f.get('comment')}));}}><label>Clave<input name="key" required/></label><label>Condición<textarea name="condition" required/></label><label>Criterio<textarea name="criterion" required/></label><label>Soporte<select name="evidence">{links.map(l=><option key={l.ref} value={l.ref}>{l.key} · {l.purpose}</option>)}</select></label><label>Importe observado (opcional)<input name="amount" inputMode="decimal"/></label><label>Contexto de muestra<input name="population" required/></label><label>Comentario<textarea name="comment" required/></label><button disabled={busy}>Crear candidato</button></form></details>}
 </>}
 </details>;
}
