'use client';
import {useState} from 'react';
import {apiFetch,apiJson} from '../../../../lib/api';
import s from './page.module.css';
type Package={id:number;package_id:string;version:number;status:string;revision:number;digest:string;authentication:string;created_at:string;valid_until:string|null;applicability:string;manifest:unknown;files?:Record<string,string>};
async function parsed<T>(r:Response):Promise<T>{const v=await r.json();if(!r.ok)throw new Error(JSON.stringify(v));return v;}
export default function KnowledgePanel(){
 const [items,setItems]=useState<Package[]>([]),[selected,setSelected]=useState<Package|null>(null),[note,setNote]=useState(''),[days,setDays]=useState(90),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const d=await parsed<{results:Package[];truncated:boolean}>(await apiFetch('/api/carova/brain/knowledge/'));setItems(d.results);if(d.truncated)setError('Sólo se muestran las últimas 30 versiones.');}
 async function perform(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function upload(file:File){if(file.size>262144)throw new Error('El paquete supera 256 KiB.');const value=JSON.parse(await file.text());setSelected(await parsed<Package>(await apiJson('/api/carova/brain/knowledge/','POST',value)));await load();}
 async function open(id:number){setSelected(await parsed<Package>(await apiFetch(`/api/carova/brain/knowledge/${id}/`)));setNote('');}
 async function decide(decision:string){if(!selected)return;setSelected(await parsed<Package>(await apiJson(`/api/carova/brain/knowledge/${selected.id}/decision/`,'POST',{decision,revision:selected.revision,digest:selected.digest,note,days})));await load();}
 return <details className={s.history}><summary>Watch · Actualizaciones para revisión</summary><p>Importación manual. Watch no recibe expedientes ni consultas internas. La aprobación de distribución no activa el paquete en este despacho. No se aplican reglas fiscales automáticamente.</p><button disabled={busy} onClick={()=>void perform(load)}>Ver actualizaciones</button><label>Importar paquete público JSON<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void perform(()=>upload(f));e.target.value='';}}/></label>{error&&<p role="alert">{error}</p>}{items.map(p=><button key={p.id} disabled={busy} onClick={()=>void perform(()=>open(p.id))}>{p.package_id} · v{p.version} · {p.status}</button>)}{selected&&<article><h3>{selected.package_id} · v{selected.version}</h3><p>Estado: {selected.status} · autenticación: {selected.authentication}</p><p>Un hash sin autenticación de distribución no acredita origen. HMAC acredita integridad con clave compartida, nunca aprobación del gobierno ni exactitud legal.</p><p>{selected.applicability}</p><details><summary>Manifiesto, fechas y fuentes</summary><pre className={s.technical}>{JSON.stringify(selected.manifest,null,2)}</pre></details>{Object.entries(selected.files||{}).map(([name,text])=><section key={name}><h4>{name}</h4><pre className={s.messageText}>{text}</pre></section>)}{['REVIEW_PENDING','APPROVED'].includes(selected.status)&&<><label>Criterio de aplicación o motivo<textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><label>Vigencia de la aprobación en días<input type="number" min={1} max={366} value={days} onChange={e=>setDays(Number(e.target.value))}/></label>{selected.status==='REVIEW_PENDING'?<><button disabled={busy||!note.trim()} onClick={()=>void perform(()=>decide('approve'))}>Aprobar esta versión para el despacho</button><button disabled={busy||!note.trim()} onClick={()=>void perform(()=>decide('reject'))}>Rechazar esta versión</button></>:<button disabled={busy||!note.trim()} onClick={()=>void perform(()=>decide('withdraw'))}>Retirar esta versión</button>}</>}</article>}</details>;
}
