'use client';
import {useState} from 'react';
import {apiFetch,apiJson} from '../../../../lib/api';
import s from './page.module.css';
type Memory={id:number;key:string;content:string;conditions:string;scope:string;status:string;revision:number;version:number;digest:string;valid_until:string;origin:string;author_id:number;approver_id:number|null};
async function parsed<T>(r:Response):Promise<T>{const v=await r.json();if(!r.ok)throw new Error(v.detail?JSON.stringify(v.detail):JSON.stringify(v));return v;}
export default function MemoryPanel({conversationId,clientId}:{conversationId?:number;clientId?:number}){
 const [rows,setRows]=useState<Memory[]>([]),[conflicts,setConflicts]=useState<string[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[proposal,setProposal]=useState<Memory|null>(null),[content,setContent]=useState(''),[key,setKey]=useState('reporte.formato'),[conditions,setConditions]=useState('Al preparar reportes del alcance seleccionado'),[scope,setScope]=useState('USER'),[share,setShare]=useState(false),[days,setDays]=useState(90),[replace,setReplace]=useState('');
 async function load(){const d=await parsed<{results:Memory[];retrieval:{conflicts:string[]};truncated:boolean}>(await apiFetch('/api/carova/brain/memory/'+(clientId?'?client_id='+clientId:'')));setRows(d.results);setConflicts(d.retrieval.conflicts);setLoaded(true);if(d.truncated)setError('Lista parcial: sólo las últimas 100 propuestas.');}
 async function perform(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function propose(){if(!conversationId)throw new Error('Abre o inicia una conversación para conservar la procedencia.');const m=await parsed<Memory>(await apiJson('/api/carova/brain/memory/','POST',{conversation_id:conversationId,key,content,conditions,scope,share,days,...(replace?{replaces_id:Number(replace)}:{})}));setProposal(m);await load();}
 async function decide(m:Memory,decision:string){await parsed(await apiJson(`/api/carova/brain/memory/${m.id}/decision/`,'POST',{decision,revision:m.revision,digest:m.digest}));setProposal(null);await load();}
 return <details className={s.history}><summary>Memoria privada · Qué recuerda CAROVA</summary><p>Historial y documentos no se convierten en reglas automáticamente. Sólo los criterios aprobados y vigentes se recuperan; nunca autorizan acciones ni cambian controles.</p><button disabled={busy} onClick={()=>void perform(load)}>Qué recuerda</button>{conflicts.length>0&&<p role="alert">Criterios contradictorios: {conflicts.join(', ')}. Ninguna variante se aplica hasta resolverlos.</p>}{error&&<p role="alert">{error}</p>}
 <details><summary>Proponer corrección</summary><form className={s.controls} onSubmit={e=>{e.preventDefault();void perform(propose);}}><label>Clave del criterio<input value={key} maxLength={80} onChange={e=>setKey(e.target.value)}/></label><label>Qué guardar<textarea value={content} maxLength={2000} required onChange={e=>setContent(e.target.value)}/></label><label>Cuándo aplica<input value={conditions} maxLength={600} required onChange={e=>setConditions(e.target.value)}/></label><label>Alcance del criterio<select value={scope} onChange={e=>setScope(e.target.value)}><option value="USER">Sólo para mí</option><option value="CLIENT">Cliente seleccionado · responsable autorizado</option><option value="ORGANIZATION">Despacho · responsable autorizado</option></select></label><label>Vigencia en días<input type="number" min={1} max={366} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>Sustituye criterio ID (opcional)<input type="number" min={1} value={replace} onChange={e=>setReplace(e.target.value)}/></label>{scope!=='USER'&&<label><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/> Autorizo compartir este contenido en el alcance elegido</label>}<button disabled={busy||!conversationId}>Preparar propuesta de memoria</button></form></details>
 {proposal&&<p>Propuesta {proposal.id} guardada sin activar. Revisa el contenido exacto, ámbito y vigencia antes de aprobar.</p>}
 {loaded&&!rows.length&&<p>No hay memoria disponible en este alcance.</p>}{rows.map(m=><article key={m.id}><h3>Criterio {m.id} · {m.key} · v{m.version}</h3><p>{m.content}</p><p>{m.conditions}</p><p>{m.scope} · {m.status} · vigente hasta {m.valid_until.slice(0,10)}</p><p>{m.origin} · autor {m.author_id} · aprobador {m.approver_id||'pendiente'}</p>{m.status==='PROPOSED'&&<button disabled={busy} onClick={()=>void perform(()=>decide(m,'approve'))}>Aprobar criterio {m.id}</button>}{['PROPOSED','APPROVED'].includes(m.status)&&<button disabled={busy} onClick={()=>void perform(()=>decide(m,'revoke'))}>Revocar criterio {m.id}</button>}</article>)}</details>;
}
