'use client';
import {useCallback,useEffect,useState, type FormEvent} from 'react';
import {apiFetch,apiJson,downloadFile} from '../../../../lib/api';
import {internalPath,readable,quickActions} from './ux';
import s from './page.module.css';
import MemoryPanel from './MemoryPanel';
import KnowledgePanel from './KnowledgePanel';
type Context={client_id?:number;engagement_id?:number;period_id?:number;case_ids?:number[];document_ids?:number[]};
type Source={kind:string;id:number;label:string;url:string;locator?:string;snippet?:string};
type Preview={id:number;revision:number;tool:string;arguments:Record<string,unknown>;effect:string;status?:string;expires_at:string};
type Result={text:string;rows:Record<string,unknown>[];sources:Source[];metrics?:Record<string,unknown>;files?:{id:number;name:string;url:string;ticket?:string}[];preview?:Preview;truncated?:boolean};
type Message={id:number;role:string;content:string;response:{results?:{tool:string;result?:Result;error?:string}[]}};
type Job={id:number;status:string;error:string;progress:{step:number;tool:string;status:string}[]};
type Conversation={id:number;title:string;archived:boolean;history_truncated:boolean;context:Context;messages:Message[];jobs:Job[]};
type Options={features?:{ecosystem:boolean;can_manage:boolean};provider:{notice:string;external_enabled:boolean};clients:{id:number;name:string}[];periods:{id:number;client_id:number;engagement_id:number;label:string;engagement:string}[];documents:{id:number;name:string;client_id:number;engagement_id:number}[]};
const ROOT='/api/carova/brain/';
const names:Record<string,string>={get_expense_period_summary:'Estado del periodo',get_expense_pending_items:'Pendientes',get_unclosed_policies:'Pólizas pendientes',get_vat_review:'Cruce IVA',get_expense_exceptions:'Diferencias abiertas',get_bank_reconciliation:'Banco contra registros',summarize_team_activity:'Actividad registrada',compare_documents:'Comparación documental',get_old_outstanding_balances:'Saldos por comprobar',create_clarification_draft:'Crear aclaraciones',close_accounting_period:'Cerrar periodo'};
const labels:Record<string,string>={content:'Criterio',conditions:'Cuándo aplica',scope:'Alcance',valid_until:'Vigente hasta',source:'Fuente',fetched_at:'Fecha de consulta',fixture:'Prueba sintética',applicability:'Aplicación revisada',recipient:'Destinatario',report_type:'Tipo de reporte',case_ids:'Pólizas incluidas',targets:'Registros incluidos',note:'Motivo / texto',tool:'Acción',action:'Acción',decision:'Decisión',explanation:'Motivo',statement:'Estado de cuenta',movement_count:'Movimientos',bank_total:'Total banco',linked_policy_total_once:'Pólizas vinculadas',difference:'Diferencia',unmatched_movements:'Sin vincular',snapshot_current:'Versión vigente',reviewed:'Revisada',xml:'IVA CFDI/XML',expenses:'IVA gastos',deductible:'Deducible',non_deductible:'No deducible',open_differences:'Diferencias abiertas',provisional_recorded:'Constancia previa',escalated:'Escalados',attention:'Revisión',method:'Método',rep:'REP',special:'Operación especial',name:'Nombre',kind:'Tipo',version:'Versión',id:'ID',reference:'Póliza',title:'Descripción',amount:'Importe',status:'Estado',next_action:'Siguiente acción',client:'Cliente',responsible:'Responsable',date:'Fecha',account:'Cuenta',work:'Obra',missing:'Faltante',document_count:'Documentos',open_issues:'Aclaraciones',difference_vat:'Diferencia IVA',difference_expenses:'Diferencia gastos',open_cases:'Pólizas sin cerrar',waiting:'Esperando cliente',responses:'Respuestas recibidas',bank_pending:'Banco pendiente',bank_missing:'Sin fuente bancaria',iva_open:'Diferencias IVA abiertas',differences_open:'Diferencias abiertas',vat_ready:'Constancia previa IVA',ready_for_review:'Preparado para revisión',partner_pending:'Revisión superior pendiente',communications:'Comunicaciones pendientes',grants_pending:'Permisos pendientes',employee:'Persona',description:'Descripción',minutes:'Minutos',hours:'Horas',count:'Registros',start:'Desde',end:'Hasta',field:'Dato',left:'Documento 1',right:'Documento 2',result:'Resultado',document_id:'Documento',locator:'Ubicación',text:'Texto',age_days:'Antigüedad (días)',origin:'Origen'};
async function data<T>(response:Response):Promise<T>{const json=await response.json();if(!response.ok)throw new Error(typeof json.detail==='string'?json.detail:JSON.stringify(json));return json;}
function Rows({rows}:{rows:Record<string,unknown>[]}){if(!rows.length)return null;const keys=Array.from(new Set(rows.flatMap(Object.keys))).filter(k=>!['responsible_ids','period_id','untrusted_data'].includes(k)&&!rows.some(r=>typeof r[k]==='object'&&r[k]!==null&&!(Array.isArray(r[k])&&(r[k] as unknown[]).every(v=>typeof v!=='object'))));if(rows.some(r=>'reference' in r))keys.splice(0,keys.length,...['reference','amount','status','responsible','missing'].filter(k=>keys.includes(k)));if(rows.some(r=>'conditions' in r&&'scope' in r))keys.splice(0,keys.length,...['id','content','conditions','scope','status','valid_until'].filter(k=>keys.includes(k)));else if(rows.some(r=>'package_id' in r&&'locator' in r))keys.splice(0,keys.length,...['source','text','locator','fetched_at','fixture','applicability'].filter(k=>keys.includes(k)));return <div className={s.table} tabIndex={0} aria-label="Tabla de resultados"><table><thead><tr>{keys.map(k=><th key={k}>{labels[k]||k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{names[readable(r[k])]||({'EQUAL':'Coincide','DIFFERENT':'Diferente','INCOMPLETE':'Falta información','confirm':'Confirmada','cancel':'Cancelada'} as Record<string,string>)[readable(r[k])]||readable(r[k])}</td>)}</tr>)}</tbody></table></div>;}
export default function Assistant(){
 const [options,setOptions]=useState<Options|null>(null),[context,setContext]=useState<Context>({}),[conversation,setConversation]=useState<Conversation|null>(null),[history,setHistory]=useState<{id:number;title:string}[]>([]),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[historySearch,setHistorySearch]=useState(''),[showArchived,setShowArchived]=useState(false),[historyLimited,setHistoryLimited]=useState(false),[conversationTitle,setConversationTitle]=useState('');
 const refresh=useCallback(async(id:number)=>{const c=await data<Conversation>(await apiFetch(ROOT+`conversations/${id}/`));setConversation(c);setContext(c.context);setConversationTitle(c.title);return c;},[]);
 const loadHistory=useCallback(async(q='',archived=false)=>{const result=await data<{results:{id:number;title:string}[];truncated:boolean}>(await apiFetch(ROOT+'conversations/?'+new URLSearchParams({q,archived:String(archived)})));setHistory(result.results);setHistoryLimited(result.truncated);},[]);
 useEffect(()=>{let active=true;void(async()=>{try{const opts=await data<Options>(await apiFetch(ROOT+'options/'));if(!active)return;setOptions(opts);await loadHistory();const params=new URLSearchParams(window.location.search);const period=opts.periods.find(p=>String(p.id)===params.get('accounting_period'));if(period)setContext({client_id:period.client_id,engagement_id:period.engagement_id,period_id:period.id});const id=params.get('conversation');if(id&&/^\d+$/.test(id))await refresh(Number(id));}catch(e){if(active)setError(String(e));}})();return()=>{active=false;};},[loadHistory,refresh]);
 const running=conversation?.jobs.some(j=>['QUEUED','RUNNING'].includes(j.status));
 useEffect(()=>{if(!running||!conversation)return;const timer=setInterval(()=>{void refresh(conversation.id).catch(e=>setError(String(e)));},1200);return()=>clearInterval(timer);},[running,conversation,refresh]);
 async function send(text:string){if(!text.trim()||busy||running||conversation?.archived)return;setBusy(true);setError('');try{const result=await data<{conversation_id:number}>(await apiJson(ROOT+'conversations/','POST',{prompt:text,conversation_id:conversation?.id,context}));setPrompt('');window.history.replaceState(null,'',`?conversation=${result.conversation_id}`);await refresh(result.conversation_id);await loadHistory();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();await send(prompt);}
 async function confirm(preview:Preview,decision:string){if(!conversation)return;setBusy(true);setError('');try{await data(await apiJson(ROOT+`conversations/${conversation.id}/confirm/${preview.id}/`,'POST',{revision:preview.revision,decision}));await refresh(conversation.id);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function changeConversation(update:{title?:string;archived?:boolean}){if(!conversation)return;setBusy(true);setError('');try{await data(await apiJson(ROOT+`conversations/${conversation.id}/`,'PATCH',update));await refresh(conversation.id);await loadHistory(historySearch,showArchived);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function file(path:string,name:string,ticket?:string){if(!internalPath(path)){setError('Enlace fuera del alcance permitido.');return;}setError('');try{if(ticket){const res=await apiFetch(path,{headers:{'X-Carova-Export-Ticket':ticket}});if(!res.ok)throw new Error('Descarga expirada o fuera de alcance. Reabre la conversación.');const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}else{const message=await downloadFile(path,name);if(message)setError(message);}}catch{setError('No se pudo descargar el archivo privado.');}}
 const period=options?.periods.find(p=>p.id===context.period_id),client=options?.clients.find(c=>c.id===context.client_id);
 return <main className={s.page}><header className={s.header}><div><h1>Asistente del despacho</h1><p>¿Qué quieres hacer?</p></div><a href="/panel/carova">Centro de trabajo</a></header>
 {options&&<p className={options.provider.external_enabled?s.error:s.privacy}>{options.provider.notice}</p>}
 <section className={s.context} aria-label="Contexto de la conversación"><div><strong>{client?.name||'Mi alcance autorizado'}</strong><p>{period?.label||'Sin periodo seleccionado'}{period?.engagement?` · ${period.engagement}`:''}</p></div><details><summary>Cambiar contexto o documentos</summary><div className={s.controls}><label>Cliente<select value={context.client_id||''} disabled={busy||running} onChange={e=>setContext(e.target.value?{client_id:Number(e.target.value)}:{})}><option value="">Mi alcance autorizado</option>{options?.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Periodo<select value={context.period_id||''} disabled={busy||running} onChange={e=>{const p=options?.periods.find(p=>p.id===Number(e.target.value));setContext(p?{client_id:p.client_id,engagement_id:p.engagement_id,period_id:p.id}:{client_id:context.client_id});}}><option value="">Seleccionar periodo</option>{options?.periods.filter(p=>!context.client_id||p.client_id===context.client_id).map(p=><option key={p.id} value={p.id}>{p.label} · {p.engagement}</option>)}</select></label><label>Documentos para esta consulta<select multiple value={(context.document_ids||[]).map(String)} onChange={e=>setContext({...context,document_ids:Array.from(e.target.selectedOptions,x=>Number(x.value))})}>{options?.documents.filter(d=>(!context.client_id||d.client_id===context.client_id)&&(!context.engagement_id||d.engagement_id===context.engagement_id)).map(d=><option key={d.id} value={d.id}>{d.id} · {d.name}</option>)}</select></label><p>También puedes indicar dos IDs: “Compara documentos 1 y 2”.</p></div></details></section>
 <details className={s.history}><summary>Conversaciones anteriores</summary><button disabled={busy||running} onClick={()=>{setConversation(null);setContext({});setConversationTitle('');window.history.replaceState(null,'','/panel/carova/assistant');}}>Nueva conversación</button>{options?.features?.ecosystem&&<form className={s.controls} onSubmit={e=>{e.preventDefault();void loadHistory(historySearch,showArchived).catch(e=>setError(String(e)));}}><label>Buscar conversaciones<input value={historySearch} maxLength={160} onChange={e=>setHistorySearch(e.target.value)}/></label><label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Mostrar archivadas</label><button type="submit">Buscar</button></form>}{historyLimited&&<p>Se muestran hasta 30 conversaciones. Acota la búsqueda para ver otras.</p>}{history.map(h=><button key={h.id} disabled={busy||running} onClick={()=>{setError('');void refresh(h.id).then(()=>window.history.replaceState(null,'',`?conversation=${h.id}`)).catch(e=>setError(String(e)));}}>{h.title}</button>)}</details>
 {conversation&&options?.features?.ecosystem&&<details className={s.history}><summary>Gestionar esta conversación</summary><label>Nombre de la conversación<input value={conversationTitle} maxLength={160} onChange={e=>setConversationTitle(e.target.value)}/></label><button disabled={busy||running||!conversationTitle.trim()} onClick={()=>void changeConversation({title:conversationTitle})}>Guardar nombre</button><button disabled={busy||running} onClick={()=>void changeConversation({archived:!conversation.archived})}>{conversation.archived?'Desarchivar conversación':'Archivar conversación'}</button></details>}
 {conversation?.archived&&<p>Esta conversación está archivada. Desarchívala para continuar.</p>}
 {conversation?.history_truncated&&<p>Se muestran los últimos 100 mensajes. El historial anterior se conserva.</p>}

 {options?.features?.ecosystem&&<MemoryPanel key={`${conversation?.id||0}:${context.client_id||0}`} conversationId={conversation?.id} clientId={context.client_id}/>}
 {options?.features?.ecosystem&&options.features.can_manage&&<KnowledgePanel/>}
 {!conversation&&<section className={s.welcome}><h2>Una conversación para trabajar</h2><p>Consulta tu información, compara documentos y prepara entregables con sus fuentes.</p><div className={s.quick}>{quickActions.map(q=><button key={q} disabled={busy} onClick={()=>void send(q)}>{q}</button>)}</div></section>}
 <section className={s.messages} aria-label="Conversación">{conversation?.messages.map(m=><article className={m.role==='user'?s.user:s.assistant} key={m.id}><strong>{m.role==='user'?'Tú':'CAROVA'}</strong><p className={s.messageText}>{m.content}</p>{m.response.results?.map((entry,index)=><section className={s.result} key={index}>{entry.error?<p role="alert" className={s.error}>{entry.error}</p>:entry.result&&<><h3>{names[entry.tool]||'Resultado'}</h3><p>{entry.result.text}</p>{entry.result.metrics&&<details><summary>Totales y alcance</summary><Rows rows={[entry.result.metrics]}/>{typeof entry.result.metrics.export_scope==='object'&&entry.result.metrics.export_scope!==null&&Object.entries(entry.result.metrics.export_scope).map(([k,v])=><p key={k}><strong>{k}: </strong>{readable(v)}</p>)}</details>}<Rows rows={entry.result.rows}/>{entry.result.truncated&&<p>Resultado parcial. Acota el filtro o solicita la siguiente página.</p>}{entry.result.sources.length>0&&<details><summary>Fuentes ({entry.result.sources.length})</summary>{entry.result.sources.map((ref,i)=><div className={s.source} key={i}>{ref.kind==='document'?<button onClick={()=>void file(ref.url,ref.label)}>{ref.label} · {ref.locator||'Documento'}</button>:internalPath(ref.url)?<a href={ref.url}>{ref.label}</a>:<span>{ref.label}</span>}{ref.snippet&&<blockquote>{ref.snippet}</blockquote>}</div>)}</details>}{entry.result.files?.map(f=><button className={s.primary} key={f.id} onClick={()=>void file(f.url,f.name,f.ticket)}>Descargar {f.name}</button>)}{entry.result.preview&&<div className={s.preview}><h4>Confirmar acción</h4><p>{entry.result.preview.effect}</p><Rows rows={[entry.result.preview.arguments]}/><p>Válido hasta {new Date(entry.result.preview.expires_at).toLocaleTimeString('es-MX')}</p>{!entry.result.preview.status||entry.result.preview.status==='waiting_confirmation'?<div className={s.actions}><button className={s.primary} disabled={busy||running} onClick={()=>void confirm(entry.result!.preview!,'confirm')}>Confirmar cambios</button><button disabled={busy||running} onClick={()=>void confirm(entry.result!.preview!,'cancel')}>Cancelar</button></div>:<p>Plan {entry.result.preview.status==='confirmed'?'confirmado':'atendido'}.</p>}</div>}<details><summary>Ver detalles</summary><p>Herramienta: {entry.tool}. Autorización verificada por el servidor.</p><pre className={s.technical}>{JSON.stringify(entry.result.rows,null,2)}</pre></details></>}</section>)}</article>)}</section>
 {(busy||running)&&<p role="status">CAROVA está consultando el alcance y preparando el resultado…</p>}{conversation?.jobs[0]&&<details className={s.history}><summary>Progreso de la solicitud · {conversation.jobs[0].status}</summary>{conversation.jobs[0].progress.map(p=><p key={p.step}>{p.step}. {names[p.tool]||p.tool} · {p.status}</p>)}{conversation.jobs[0].error&&<p>{conversation.jobs[0].error}</p>}</details>}
 {error&&<p className={s.error} role="alert">{error}</p>}<form className={s.composer} onSubmit={submit}><label htmlFor="brain-prompt">Pregúntale a CAROVA...</label><textarea id="brain-prompt" value={prompt} maxLength={4000} rows={3} disabled={busy||running||conversation?.archived} onChange={e=>setPrompt(e.target.value)} placeholder="Por ejemplo: ¿Qué falta para cerrar septiembre?"/><button className={s.primary} disabled={busy||running||conversation?.archived||!prompt.trim()} type="submit">Enviar</button><p>Las acciones sensibles requieren tu confirmación. Los archivos y las fuentes conservan tus permisos.</p></form></main>;
}
