"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {apiFetch,apiJson,downloadFile} from '../../../../lib/api';
import s from './page.module.css';

type Period={id:number;client_id:number;client:string;engagement_id:number;engagement:string;label:string};
type Item={document_id:number;filename:string;sha256:string;uuid:string|null;issuer:string|null;total:string|null;currency:string|null;parser_status:string;parse_error:string|null;relation_status:string;projection_limits:unknown[];identity:{duplicate_type:string;conflict_status:string;requires_human_review:boolean;document_ids:number[];reasons:string[]}};
type Result={results:Item[];document_count:number;normalization_version_count:number;page:number;pages:number;coverage:string;inventory:{xml:number;pdf:number;unique_uuids:number;conflicting_uuids:number;exact_duplicate_deliveries:number;without_uuid:number;parser_states:Record<string,number>}};
type Detail=Item & {fields:Record<string,unknown>;references:unknown[];relations:{id:number;document_id:number;related_document_id:number;status:string;revision:number;reason:string}[];versions:{parser_version:string;created_at:string}[]};
type Field={value:unknown;status:string;source_field:string;original_value:unknown;normalization:string;parser_version:string;parsed_at:string};
const ROOT='/api/carova/document-intelligence/';
const statuses:Record<string,string>={PARSED:'Parseado',PARTIAL:'Parcial',UNPARSED:'Sin interpretar',UNSUPPORTED:'No soportado',PARSE_ERROR:'Error de lectura',CONFLICT:'Conflicto'};
async function read<T>(response:Response):Promise<T>{const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body));return body as T;}

export default function Documents(){
 const [options,setOptions]=useState<Period[]>([]),[client,setClient]=useState(''),[periodId,setPeriodId]=useState('');
 const [filters,setFilters]=useState<Record<string,string>>({}),[applied,setApplied]=useState<Record<string,string>>({}),[page,setPage]=useState(1);
 const [result,setResult]=useState<Result|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState<number[]>([]);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
 const [files,setFiles]=useState<File[]>([]),[synthetic,setSynthetic]=useState(false),[reason,setReason]=useState('');
 const generation=useRef(0);
 const period=options.find(p=>String(p.id)===periodId);
 const params=new URLSearchParams({...applied,...(period?{client_id:String(period.client_id),engagement_id:String(period.engagement_id)}:{})}).toString();
 const base=period?`${ROOT}periods/${period.id}/`:'';
 const refresh=()=>setReload(x=>x+1);
 const clear=()=>{generation.current++;setResult(null);setDetail(null);setSelected([]);setPage(1);setLoading(false);setError('');setNotice('');};
 useEffect(()=>{let active=true;void(async()=>{try{const data=await read<{periods:Period[];truncated:boolean}>(await apiFetch(ROOT+'options/'));if(active){setOptions(data.periods);const requested=new URLSearchParams(window.location.search).get('period_id');const chosen=data.periods.find(p=>String(p.id)===requested);if(chosen){setClient(String(chosen.client_id));setPeriodId(String(chosen.id));}if(data.truncated)setNotice('Se muestran los primeros 500 periodos autorizados.');}}catch(e){if(active)setError(String(e));}})();return()=>{active=false;};},[]);
 useEffect(()=>{if(!base)return;let active=true;const token=++generation.current;setLoading(true);void(async()=>{try{const data=await read<Result>(await apiFetch(base+'?'+params+`&page=${page}&limit=30`));if(active&&generation.current===token)setResult(data);}catch(e){if(active)setError(String(e));}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[base,params,page,reload]);
 const open=useCallback(async(id:number,version?:string)=>{const token=generation.current;try{const data=await read<Detail>(await apiFetch(base+`documents/${id}/?`+params+(version?`&version=${encodeURIComponent(version)}`:'')));if(token===generation.current)setDetail(data);}catch(e){if(token===generation.current)setError(String(e));}},[base,params]);
 async function download(path:string,name:string){const message=await downloadFile(path,name);if(message)throw new Error(message);}
 async function task(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function upload(){await task(async()=>{if(!synthetic||!files.length||files.length>20)throw new Error('Confirma el origen sintético y selecciona de 1 a 20 archivos.');const form=new FormData();files.forEach(f=>form.append('files',f));form.append('synthetic','true');const data=await read<{results:{filename:string;status:string}[]}>(await apiFetch(base+'?'+params,{method:'POST',body:form}));setNotice(data.results.map(r=>`${r.filename}: ${statuses[r.status]||r.status}`).join(' · '));setSelected([]);refresh();});}
 async function exportFile(format:string){await task(async()=>{const data=await read<{url:string;name:string;rows:number}>(await apiJson(base+'exports/?'+params,'POST',{format,...(selected.length?{document_ids:selected}:{})}));await download(data.url+'?'+params,data.name);setNotice(`Archivo generado con ${data.rows} documentos. Una fila por archivo; importes en texto decimal exacto.`);});}
 async function propose(){await task(async()=>{if(selected.length!==2||!reason.trim())throw new Error('Selecciona dos documentos y describe la evidencia.');await read(await apiJson(base+'relations/?'+params,'POST',{document_ids:selected,reason}));setNotice('Relación propuesta. Abre el detalle y revisa ambos documentos antes de confirmarla.');refresh();setDetail(null);});}
 async function confirm(id:number,revision:number){await task(async()=>{await read(await apiJson(base+`relations/${id}/confirm/?`+params,'POST',{confirm:true,revision}));setNotice('Relación documental confirmada por una persona. No representa un pago.');refresh();setDetail(null);});}
 const clients=[...new Map(options.map(p=>[p.client_id,p.client])).entries()];
 const fieldRows=detail?Object.entries(detail.fields).filter(([,v])=>v&&typeof v==='object'&&!Array.isArray(v)&&'source_field' in v) as [string,Field][]:[];
 return <section className={s.page}>
  <header className={s.header}><div><p className={s.eyebrow}>Biblioteca documental</p><h1>Documentos</h1><p>Archivos, campos y fuentes verificables. Sin validación SAT ni decisiones contables.</p></div><Link href="/panel/carova/egresos">Volver a Egresos</Link></header>
  {error&&<p role="alert" className={s.error}>{error}</p>}{notice&&<p role="status" className={s.notice}>{notice}</p>}
  <section className={s.controls} aria-label="Contexto"><label>Cliente<select disabled={busy} value={client} onChange={e=>{clear();setClient(e.target.value);setPeriodId('');}}><option value="">Selecciona cliente</option>{clients.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Periodo de recepción<select disabled={busy||!client} value={periodId} onChange={e=>{clear();setPeriodId(e.target.value);}}><option value="">Selecciona periodo</option>{options.filter(p=>String(p.client_id)===client).map(p=><option key={p.id} value={p.id}>{p.label} · {p.engagement}</option>)}</select></label></section>
  {!period?<p className={s.empty}>Selecciona un cliente y periodo para consultar sus documentos autorizados.</p>:<>
   <details className={s.panel}><summary>Recibir archivos sintéticos</summary><p>XML, PDF, TXT, CSV o XLSX. Hasta 20 archivos por lote, 10 MiB por archivo. Los errores quedan visibles; los originales rechazados por el parser permanecen en cuarentena.</p><input aria-label="Archivos sintéticos" type="file" multiple accept=".xml,.pdf,.txt,.csv,.xlsx" disabled={busy} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><label className={s.check}><input type="checkbox" disabled={busy} checked={synthetic} onChange={e=>setSynthetic(e.target.checked)}/>Confirmo que estos archivos son sintéticos y no contienen datos reales.</label><button disabled={busy||!synthetic||!files.length} onClick={()=>void upload()}>Recibir y procesar</button></details>
   <form className={s.panel} onSubmit={e=>{e.preventDefault();clear();setApplied(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)));refresh();}}><div className={s.controls}>{[['q','Texto o nombre'],['uuid','UUID'],['rfc_emisor','RFC emisor'],['rfc_receptor','RFC receptor'],['total','Total exacto'],['currency','Moneda'],['date','Fecha CFDI'],['serie','Serie'],['folio','Folio'],['sha256','SHA256'],['references_uuid','Referencia a UUID']].map(([key,label])=><label key={key}>{label}<input value={filters[key]||''} disabled={busy} type={key==='date'?'date':'text'} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<label>Estado<select value={filters.status||''} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option>{Object.entries(statuses).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Conflictos<select value={filters.conflict||''} onChange={e=>setFilters({...filters,conflict:e.target.value})}><option value="">Todos</option><option value="CONFLICT">Con conflicto de UUID</option></select></label></div><button disabled={busy}>Buscar</button></form>
   {loading&&<p role="status">Consultando fuentes autorizadas…</p>}
   {result&&<><section className={s.metrics} aria-label="Inventario"><div><strong>{result.document_count}</strong>archivos</div><div><strong>{result.inventory.xml} / {result.inventory.pdf}</strong>XML / PDF</div><div><strong>{result.inventory.unique_uuids}</strong>UUID únicos</div><div><strong>{result.inventory.conflicting_uuids}</strong>UUID conflictivos</div><div><strong>{result.inventory.exact_duplicate_deliveries}</strong>entregas repetidas</div><div><strong>{result.normalization_version_count}</strong>versiones conservadas</div></section><p>{Object.entries(result.inventory.parser_states).map(([k,v])=>`${statuses[k]||k}: ${v}`).join(' · ')}</p>
   <div className={s.actions}><span>{selected.length} seleccionados</span><button disabled={busy} onClick={()=>void exportFile('xlsx')}>Exportar {selected.length?'selección':'filtros'} XLSX</button><button disabled={busy} onClick={()=>void exportFile('csv')}>Exportar {selected.length?'selección':'filtros'} CSV</button><button disabled={!selected.length} onClick={()=>setSelected([])}>Limpiar selección</button></div>
   <div className={s.table}><table><thead><tr><th>Seleccionar</th><th>Documento</th><th>UUID / emisor</th><th>Total declarado</th><th>Estado</th><th>Relación</th></tr></thead><tbody>{result.results.map(item=><tr key={item.document_id}><td><input type="checkbox" aria-label={`Seleccionar ${item.filename} ${item.document_id}`} checked={selected.includes(item.document_id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,item.document_id]:ids.filter(i=>i!==item.document_id))}/></td><td><button className={s.link} onClick={()=>void open(item.document_id)}>{item.filename}</button><small>#{item.document_id}</small></td><td><code>{item.uuid||'UUID no presente'}</code><small>{item.issuer||'Emisor no identificado'}</small></td><td>{item.total??'Desconocido'} {item.currency||''}</td><td>{statuses[item.parser_status]||item.parser_status}{item.identity.conflict_status==='CONFLICT'&&<strong className={s.error}>Conflicto de UUID</strong>}{item.parse_error&&<small>{item.parse_error}</small>}{item.projection_limits.length>0&&<small>Limitaciones visibles en detalle</small>}</td><td>{item.relation_status==='RELATED'?'Confirmada':item.relation_status==='PROPOSED'?'Propuesta':'Sin relación visible'}</td></tr>)}</tbody></table>{!result.results.length&&<p>No hay documentos con estos filtros.</p>}</div>
   <nav className={s.actions} aria-label="Paginación"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{result.coverage}</span><button disabled={page>=result.pages||loading} onClick={()=>setPage(p=>p+1)}>Siguiente</button></nav>
   <details className={s.panel}><summary>Proponer relación entre dos documentos</summary><p>Selecciona exactamente dos archivos. La semejanza del nombre es sólo un indicio.</p><label>Evidencia o motivo<textarea value={reason} disabled={busy} maxLength={4000} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||selected.length!==2||!reason.trim()} onClick={()=>void propose()}>Registrar propuesta para revisión humana</button></details></>}
  </>}
  {detail&&<section className={s.detail} aria-label="Detalle documental"><div className={s.actions}><h2>{detail.filename}</h2><button onClick={()=>setDetail(null)}>Cerrar detalle</button></div><p><code>{detail.sha256}</code></p><p>{detail.identity.reasons.join(' ')}</p><p>{detail.identity.document_ids.length} archivos en el grupo visible. {detail.identity.requires_human_review?'Requiere revisión humana.':''}</p><label>Versión de normalización<select value={(detail.fields.document_meta as {parser_version?:string})?.parser_version||''} onChange={e=>void open(detail.document_id,e.target.value)}>{detail.versions.map(v=><option key={v.parser_version}>{v.parser_version}</option>)}</select></label><div className={s.actions}><button disabled={busy} onClick={()=>void task(()=>download(base+`documents/${detail.document_id}/file/?`+params,detail.filename))}>Descargar original</button><button disabled={busy} onClick={()=>void task(async()=>{await read(await apiJson(base+`documents/${detail.document_id}/?`+params,'POST',{}));setDetail(null);refresh();})}>Procesar con la versión documental actual</button></div>
   <div className={s.table}><table><thead><tr><th>Campo</th><th>Valor / estado</th><th>Fuente</th><th>Transformación</th></tr></thead><tbody>{fieldRows.map(([name,f])=><tr key={name}><td>{name}</td><td>{f.value==null?'Desconocido':String(f.value)}<small>{f.status}</small></td><td><code>{f.source_field}</code><small>Original: {f.original_value==null?'No presente':String(f.original_value)}</small></td><td>{f.normalization}<small>{f.parser_version} · {f.parsed_at}</small></td></tr>)}</tbody></table></div>
   <h3>Relaciones documentales</h3>{detail.relations.length?detail.relations.map(r=><article className={s.panel} key={r.id}><p>Documentos #{r.document_id} ↔ #{r.related_document_id} · {r.status}</p><p>{r.reason}</p>{r.status==='RELACION_PENDIENTE'&&<button disabled={busy} onClick={()=>void confirm(r.id,r.revision)}>Confirmo que revisé ambos documentos y su relación</button>}</article>):<p>Sin relaciones visibles para tu alcance.</p>}
   <details><summary>Referencias a otros UUID</summary><pre>{JSON.stringify(detail.references,null,2)}</pre></details><details><summary>Conceptos, impuestos, complementos y provenance completo</summary><pre>{JSON.stringify(detail.fields,null,2)}</pre></details>
  </section>}
 </section>;
}
