export function bookPath(path:string):string{
 const [pathname]=path.split('?');
 if(!/^[a-z0-9-]+(?:\/[a-z0-9-]+)*\/$/i.test(pathname)||path.includes('#')||/[\r\n\\]/.test(path))throw new Error('Ruta de libros inválida.');
 return path;
}
export function bookQuery(filters:Record<string,string>):string{return new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,value])=>value!==''))).toString();}
const messages:Record<string,string>={UNBALANCED_ENTRY:'La póliza no cuadra. Revisa debe y haber antes de enviarla.',PERIOD_CLOSED:'El período está cerrado. Solicita una reapertura autorizada con razón.',SOURCE_STALE:'La fuente cambió. Retira la propuesta y prepárala con evidencia vigente.',SOURCE_CHANGED:'Los bytes de la fuente cambiaron. Revisa la evidencia original.',SOURCE_UNAVAILABLE:'No está disponible la fuente original. Revisa su almacenamiento.',PREVIEW_STALE:'El preview cambió. Revisa el mapeo y confirma otra vez.',PREVIEW_CONFIRMATION_REQUIRED:'Previsualiza y revisa todas las filas antes de confirmar.',POSTED_IMPORT_REQUIRES_REVERSAL:'Revierte las pólizas contabilizadas antes de retirar la importación.',REVISION_CONFLICT:'Otro usuario cambió el registro. Actualiza y revisa antes de confirmar.',ACCOUNT_NATURE_NOT_CONFIGURED:'Configura explícitamente la naturaleza de la cuenta.',UNPOSTED_ENTRIES_REQUIRE_REVIEW:'Hay pólizas pendientes. Revísalas o retíralas antes del cierre.',CLIENT_RFC_DOES_NOT_MATCH_XML:'El RFC del cliente debe corresponder al emisor o receptor del XML.',SAT_CREDENTIAL_REQUIRED:'Configura la e.firma del cliente mediante el formulario privado.',SAT_SECRET_STORE_NOT_CONFIGURED:'El almacén cifrado SAT aún requiere configuración del administrador.',CREDENTIAL_LOCAL_VALIDATION_FAILED:'Revisa RFC, vigencia, certificado, llave y contraseña.',CFDI_WITHDRAWN:'La fuente CFDI fue retirada. Usa evidencia vigente.'};
export function bookError(value:unknown):string{
 const flat=(x:unknown):string[]=>typeof x==='string'?[x]:Array.isArray(x)?x.flatMap(flat):x&&typeof x==='object'?Object.values(x).flatMap(flat):[];
 for(const code of flat(value)){if(messages[code])return messages[code];const known:Record<string,string>={PERIOD_REQUIRED:'Selecciona el período del libro antes de subir esta fuente.',PERIOD_CLIENT_MISMATCH:'El período debe pertenecer al cliente seleccionado.',INVALID_DATE:'Revisa la fecha y utiliza año, mes y día válidos.',EMPTY_FILE:'El archivo no contiene filas de datos.',UPLOAD_LIMIT:'Selecciona un archivo con datos de hasta 20 MB.',SAT_SYNC_RATE_LIMIT:'Ya hay suficientes solicitudes pendientes o recientes. Revisa el historial antes de solicitar otra.',SAT_RETRY_NOT_DUE:'El reintento aún está en espera. Consulta la hora del próximo intento.',SAT_EXPIRED_REQUEST_REQUIRES_NEW_SYNC:'La solicitud SAT venció. Conserva el historial y solicita de nuevo el rango.',SAT_CREDENTIAL_EXPIRED:'La e.firma está vencida. Configura credenciales vigentes.',REVERSAL_REQUIRES_REPLACEMENT:'Para corregir una reversa, prepara una póliza de reemplazo con razón y revisión.',INVALID_COLUMN_MAPPING:'Selecciona columnas existentes, sin repetir una misma columna.',UNKNOWN_MAPPING_FIELD:'El mapeo contiene un campo no admitido.',UNSUPPORTED_TEXT_ENCODING:'Exporta el archivo como UTF-8 o Windows-1252.',FORMULAS_REQUIRE_VALUES_EXPORT:'Exporta valores sin fórmulas antes de importar.',EXPORT_ONE_EXPLICIT_SHEET:'Exporta únicamente la hoja que necesitas importar.',EMPTY_WORKBOOK:'El archivo no contiene una hoja con datos.'};if(known[code])return known[code];}
 return 'No se pudo completar la operación. Revisa los datos, permisos y vigencia de las fuentes.';
}

const labels:Record<string,string>={
 READY_FOR_SAT_TIMBRADO:'Datos listos para captura manual externa',STRUCTURALLY_VALID:'Formato estructural válido; sin validación SAT',RECEIVER_DEFAULT:'Configuración del receptor',INVOICE:'Declarado en la factura',legal_name:'Razón social',tax_regime:'Régimen declarado',postal_code:'Código postal',cfdi_use:'Uso declarado',cfdi_use_source:'Origen del uso',rfc_validation:'Formato del RFC',version:'Versión',
 DEBIT:'Deudora',CREDIT:'Acreedora',ASSET:'Activo',LIABILITY:'Pasivo',EQUITY:'Capital',INCOME:'Ingreso',EXPENSE:'Gasto',UNMAPPED:'Sin clasificar',
 OPEN:'Abierto',CLOSED:'Cerrado',DRAFT:'Borrador',READY_FOR_REVIEW:'Por revisar',POSTED:'Contabilizada',REVERSED:'Reversada',WITHDRAWN:'Retirada',CURRENT:'Vigente',
 UPLOADED:'Recibida; falta mapeo',PREVIEW:'Previsualización',IMPORTED:'Importada',PENDING:'Pendiente de aprobación',APPROVED:'Aprobada internamente',
 CHART_OF_ACCOUNTS:'Catálogo de cuentas',TRIAL_BALANCE:'Saldos iniciales',AUXILIARY_LEDGER:'Auxiliar',JOURNAL_ENTRIES:'Pólizas',BANK_MOVEMENTS:'Movimientos bancarios',
 EMITTED:'Emitidos',RECEIVED:'Recibidos',CFDI:'XML de comprobantes',METADATA:'Datos de comprobantes',QUEUED:'En cola',REQUESTED:'Solicitud registrada',POLLING:'Esperando respuesta SAT',COMPLETE:'Ingestión completada',FAILED:'Error; requiere revisión',RETRY_WAIT:'Esperando reintento',REMOTE_UNCERTAIN:'Respuesta incierta; revisar antes de solicitar otra vez',
 CONFIGURED:'Configurada',NOT_CONFIGURED:'Sin configurar',EXPIRED:'Vencida',IMPLEMENTED_AWAITING_REAL_CREDENTIALS:'Validación real SAT pendiente',
 PENDING_CONFIGURATION:'Falta clasificar cuentas',MAPPED_INTERNAL:'Clasificación interna configurada',
 MATCH_CURRENT_LIST:'Coincidencia en publicación vigente; revisar',MATCH_HISTORICAL_LIST:'Coincidencia histórica; revisar',NO_MATCH_FOUND:'Sin coincidencia publicada',SOURCE_UNAVAILABLE:'Fuente no disponible',UNKNOWN:'RFC no válido para consulta',
 FISCAL_XML_ATTACHED:'XML externo vinculado',REQUIRES_REVIEW:'Diferencias; requiere revisión',NOT_PERFORMED:'Validación de firma no realizada',NOT_QUERIED:'Vigencia SAT no consultada',
 ENTRY_SUBMIT:'Enviada a revisión',ENTRY_POST:'Contabilizada',ENTRY_REVERSE:'Reversada',ENTRY_WITHDRAW:'Retirada',POSTING_SNAPSHOT:'Detalle de contabilización conservado',REVERSAL_POSTED:'Contrapóliza contabilizada',MAPPED:'Clasificación interna configurada',STALE:'No vigente; requiere revisión',ENTRY_CREATED:'Póliza preparada',ENTRY_SUBMITTED:'Enviada a revisión',ENTRY_POSTED:'Contabilizada',ENTRY_REVERSED:'Reversada',ENTRY_WITHDRAWN:'Propuesta retirada',
 HUMAN_CONFIGURATION:'Configuración del despacho',GENERAL:'General',OPENING:'Apertura',IMPORT:'Importación',
 SAT_NETWORK_TIMEOUT:'Sin respuesta de red',SAT_SYNC_FAILED:'Error técnico; revisar evidencia',SAT_AUTHORITY_REVOKED:'Autorización retirada',SAT_REQUEST_TERMINAL_6:'Solicitud vencida; requiere nueva sincronización',
 MISSING_REQUIRED_MAPPING:'Falta asignar una columna obligatoria',MISSING_REQUIRED_FIELD:'Falta un valor obligatorio',UNKNOWN_OR_INACTIVE_ACCOUNT:'Cuenta desconocida o inactiva',INVALID_DECIMAL:'Importe decimal inválido',INVALID_DECIMAL_FORMAT:'El importe no coincide con el formato elegido',INVALID_PRECISION_OR_RANGE:'Importe fuera de rango o con más de seis decimales',DUPLICATE_SOURCE_ROW:'Referencia de fila duplicada',UNKNOWN_PARENT:'Cuenta padre desconocida',DUPLICATE_CODE_IN_FILE:'Código de cuenta duplicado',EXISTING_ACCOUNT_REQUIRES_EXPLICIT_CONFIGURATION:'La cuenta ya existe; configúrala explícitamente',ZERO_ROW_OMITTED:'Fila en cero: no genera partida',OUT_OF_PERIOD:'Fecha fuera del período',BANK_CENTS_REQUIRED:'El movimiento debe tener importe positivo a dos decimales',BANK_DIRECTION_REQUIRED:'Indica un único cargo o abono',INVALID_SIDES:'La partida debe tener importe en un solo lado',
 ingested:'Importados',duplicates:'Duplicados',errors:'Errores',metadata:'Registros de datos',issuer_rfc:'RFC emisor',receiver_rfc:'RFC receptor',gross:'Bruto',net:'Neto',total:'Total',currency:'Moneda',period:'Período',date:'Fecha',series:'Serie',folio:'Folio',uuid:'UUID',field:'Campo',expected:'Esperado',actual:'Recibido',attributes:'Datos',kind:'Tipo',code:'Código',row:'Fila',description:'Descripción',source_row:'Fila original',
 MATCHED:'Coincidencia aritmética; revisar tratamiento',DIFFERENCE:'Diferencia; revisar',MISSING_ACCOUNTING:'Sin contrapartida contable',MISSING_CFDI:'Sin XML vigente',GROSS_AMOUNT:'Percepciones brutas',DEDUCTIONS_AMOUNT:'Deducciones',OTHER_PAYMENTS_AMOUNT:'Otros pagos',NET_AMOUNT:'Neto',PAYROLL_PERIOD_START:'Inicio del período',PAYROLL_PERIOD_END:'Fin del período',PAYROLL_PAYMENT_DATE:'Fecha de pago',EMPLOYEE_NOT_IN_CURRENT_RUN:'Trabajador fuera del cálculo vigente',UUID_REQUIRED:'Falta UUID de timbrado externo',I:'Ingreso',E:'Egreso',T:'Traslado',N:'Nómina',P:'Pago',true:'Sí',false:'No',
};
export function bookLabel(value:unknown):string { const key=String(value??'');const group=key.match(/^(ASSET|LIABILITY|EQUITY|INCOME|EXPENSE|UNMAPPED) \/ (.+)$/);return labels[key]||(group?`${labels[group[1]]} / ${group[2]}`:key); }
export function bookDisplay(value:unknown):string {
 if(value===null||value===undefined)return '';
 if(Array.isArray(value))return value.map(bookDisplay).filter(Boolean).join(' · ');
 if(typeof value==='object')return Object.entries(value).map(([key,item])=>`${bookLabel(key)}: ${bookDisplay(item)||'—'}`).join(' · ');
 return bookLabel(value);
}
