export const primaryNavigation=[{label:'Inicio',href:'/panel'},{label:'Clientes',href:'/panel/clientes'},{label:'Pendientes',href:'/panel/trabajo'},{label:'Equipo',href:'/panel/equipo'},{label:'Reportes',href:'/panel/reportes'}];
export function activeDestination(path:string){if(path==='/panel')return '/panel';if(path.startsWith('/panel/clientes'))return '/panel/clientes';if(path.startsWith('/panel/equipo')||path.startsWith('/panel/time-tracking'))return '/panel/equipo';if(path.startsWith('/panel/reportes'))return '/panel/reportes';if(path.startsWith('/panel/configuracion'))return '/panel/configuracion';return '/panel/trabajo';}
export function navigationFor(client:boolean){return client?[{label:'Inicio',href:'/panel'},{label:'Mis encargos',href:'/panel/encargos'},{label:'Solicitudes',href:'/panel/pbc'},{label:'Documentos',href:'/panel/documentos'}]:primaryNavigation;}
export function rangePreset(preset:string,today=new Date()){const end=new Date(today.getFullYear(),today.getMonth(),today.getDate());const start=new Date(end);if(preset==='last7')start.setDate(start.getDate()-6);if(preset==='previous'){start.setMonth(start.getMonth()-1,1);end.setDate(0);}if(preset==='week')start.setDate(start.getDate()-(start.getDay()+6)%7);if(preset==='month')start.setDate(1);const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return {desde:iso(start),hasta:iso(end)};}
export function reportQuery(values:Record<string,string>){const p=new URLSearchParams();Object.entries(values).forEach(([k,v])=>{if(v)p.set(k,v);});return p.toString();}
export const engineLabels:Record<string,string>={EGRESOS:'Egresos',BANK:'Bancos',IVA:'IVA',DOCUMENTOS:'Documentos',OTROS:'Otros'};
export const stateLabels:Record<string,string>={RECORDED:'Ejecución registrada',CURRENT:'Actualizado',STALE:'La evidencia cambió',NOT_STARTED:'Sin ejecución',OPEN:'Abierto',REVIEWED:'Revisado',CLOSED:'Cerrado',FAILED:'Requiere atención',RUNNING:'En proceso',COMPLETED:'Procesado'};
export function engineState(e:{state:string;run_status:string|null}){return e.run_status==='FAILED'?'Requiere atención':e.run_status==='RUNNING'?'En proceso':stateLabels[e.state]||'Consultar detalle';}
export type Point={label:string;value:number};
export type Activity={id:number;date:string;employee:string;client:string;period:string;display_label:string;display_category:string;engine:string;raw_event_type:string;entity:string;status:string;period_id:number|null;employee_id:number;client_id:number;duration:null;href:string};
// El identificador de un pendiente lo nombra el motor que lo produjo: para IVA con alcance
// parcial es una referencia pública opaca (IVA-A-P1-05), no una clave numérica. Se usa
// sólo como clave de fila; nunca se ordena ni se opera con él.
export type Pending={id:number|string;client:string;period:string;engine:string;label:string;code:string;description:string;reason:string;required_action:string;responsible:string;status:string;status_label:string;age_days:number;href:string;document_id:number|null;movement_id:number|null};
export type Employee={id:number;name:string;role:string;activities:number;clients:number;assigned_cases:number;open_pendings:number;resolved_pendings:number;last_activity:string|null};
export type ClientRow={id:number;name:string;periods:number;pending_count:number;current_period:string|null;responsibles:string[];state:string;last_activity:string|null};
export type Period={id:number;client_id:number;client:string;label:string;status:string;status_label:string;responsibles:string[];pending_count:number;cases:number|null;completed_cases:number;updated_at:string|null;href:string;engines:{engine:string;pending_count:number;state:string;changed:number;updated_at:string|null;run_status:string|null;href:string}[]};
export type Relation={employee_id:number;employee:string;client_id:number;client:string;period_id:number|null;period:string;period_status:string;activities:number;open_pendings:number;resolved_pendings:number;assigned_cases:number;active_assignments:number;last_activity:string|null;href:string};
export type ReportData={ranking:{available:boolean;metric:string;label:string;population:number|null;notice:string;options:{value:string;label:string}[];rows:(Employee&{position:number|null;value:number;periods_worked:number})[]};analytics:{employees:(Employee&{role_label:string;is_active:boolean;periods_worked:number;assigned_clients:number;active_periods:number;active_assignments:number})[];employee_clients:{client_memberships:number;id:number;name:string;activities:number;periods_worked:number;open_pendings:number;resolved_pendings:number;last_activity:string|null;active_assignments:number}[];employee_periods:Relation[];matrix:(Relation&{periods_worked:number})[];workload_available:boolean;workload_notice:string;active_assignments:{id:number;client_id:number;client:string;period_id:number|null;responsible:string;employee_id:number;title:string;status:string}[];pending_distributions:Record<string,Point[]>;metrics:{active_employees:number;activities:number;clients:number;periods_worked:number;assigned_clients:number;active_periods:number;active_assignments:number;last_activity:string|null};unknown_period_activities:number};type:string;generated_at:string;range:{from:string;to:string};scope:{full:boolean;employee_id:number|null};coverage:string;time_notice:string;pending_notice:string;metrics:{activities:number;clients_worked:number;open_pendings:number;resolved_pendings:number;cases:number|null;completed_cases:number;periods:number;recorded_minutes:number|null;time_records:number};series:{granularity:string;temporal:Point[];daily:Point[];clients:Point[];types:Point[]};activity:{count:number;page:number;page_size:number;results:Activity[]};pendings:{count:number;page:number;page_size:number;results:Pending[]};attention:{client:string;period:string;reason:string;href:string}[];clients:ClientRow[];periods:Period[];employees:Employee[];assignments:{id:number;client:string;period_id:number;responsible:string;title:string;status:string}[];capabilities:{documents:boolean;general_team:boolean};documents:{count:number;scope:string}|null};
export const reportingViews=['Resumen','Equipo','Empleados','Clientes','Periodos','Actividad','Pendientes'];
export const employeeViews=['Resumen','Actividad','Clientes','Periodos','Pendientes','Asignaciones','Reportes'];
export function reportLink(path:string,query:string,values:Record<string,string>={}){const [base,own]=path.split('?');const p=new URLSearchParams(query);['page','view','format','mode','sections','tab'].forEach(k=>p.delete(k));new URLSearchParams(own).forEach((v,k)=>p.set(k,v));Object.entries(values).forEach(([k,v])=>v?p.set(k,v):p.delete(k));return base+(p.size?'?'+p:'');}
