export type Team = {role: string; name: string; ref: string};
export type Spec = {source_types: string[]; conditional: boolean; external: boolean; manual: string};
export type FieldSpec = {procedure: string; type: string; automatic: unknown; required: boolean};
export type Procedure = {ref: string; code: string; target: string; complete: boolean; completion: string; outcome: string; pending?: string; evaluation: {state: string; value: unknown; reason: string}; assertion?: {fields?: Record<string, unknown>; timestamp?: string; reason?: string}};
export type Evidence = {ref: string; execution_ref: string; key: string; kind: string; source_ref: string; purpose: string; evaluation: {state: string; reason: string}};
export type Finding = {ref: string; execution_ref: string; evidence_ref: string; condition: string; criterion: string; amount?: string; currency: string; status: string; comment: string; history?: {kind?: string; status?: string; timestamp: string; actor: string; base_revision_ref?: string; material_fingerprint?: string; comment?: string}[]};
export type Sample = {ref: string; key: string; coverage: Record<string,string|number|null>; items: {ref: string; source_ref: string; selected: boolean; reason: string}[]};
export type Paper = {pending_reasons:string[];ref: string; context_ref: string; engagement_ref: string; code: string; name: string; variant: string; fund: string; section: string; instance: string; revision: number; revision_ref: string|null; status: string; state: string; ready?: boolean; actions: Record<string,boolean>; team: Team[]; preparer: string; samples?: Sample[]; procedures?: Procedure[]; procedure_specs: Record<string,Spec>; evidence?: Evidence[]; findings?: Finding[]; conclusion?: string; content?: Record<string,unknown>; items?: {ref: string; source: {reference: string; title: string; date: string; amount: string|null}}[]; item_checks?: {ref: string; fields: Record<string,{state:string; values?: {value:unknown; origin:string}[]}>}[]; vertical?: {assessment:string; conclusion_mode:string; draft:{text:string}; field_contract:Record<string,FieldSpec>; observations:Finding[]}; events?: {ref:string; decision:string; actor:string; reason:string; timestamp:string; current:boolean}[]; parents:{paper_ref:string; revision_ref:string; version:number; status:string}[]; related:{ref:string; code:string; name:string}[]};
export type Context = {ref:string; period_start:string; period_end:string; fiscal_year:number; status:string; team:Team[]; roles:string[]; papers:Paper[]};
export type Engagement = {ref:string; name:string; client:string; start:string; end:string; can_manage:boolean; contexts:Context[]};
export type Source = {download_url?:string|null; ref:string; kind:string; metadata:{reference?:string; title?:string; date?:string; amount?:string; pbc_name?:string; mime?:string; size?:number; sha256?:string; fields?:{file_name?:string; issuer_name?:string; uuid?:string}; document?:{pbc_name?:string; sha256?:string}}};
export type Artifact = {ref:string; name:string; state:string; revision_ref?:string; download_url:string|null; sha256?:string; size?:number; manifest?:{format:string; generated_at:string; review_state:string; revision_ref:string}};

const labels: Record<string,string> = {
 NOT_EVALUATED:'Sin evaluar', DRAFT:'Borrador',CURRENT:'Vigente',STALE:'Desactualizado',NEEDS_REVIEW:'Necesita revisión',WITHHELD:'Acceso restringido',READY_FOR_REVIEW:'En revisión',RETURNED:'Devuelto para corrección',REVIEWED:'Revisado',AUTHORIZED:'Autorizado',ACTIVE:'Activo',CLOSED:'Cerrado',PREPARER:'Elaboró',REVIEWER:'Revisó',AUTHORIZER:'Autorizó',CANDIDATE:'Candidato · requiere reconsideración',CONFIRMED:'Confirmado',DISMISSED:'Descartado',HISTORICAL:'Histórico',VALUE:'Valor demostrado',UNKNOWN:'No se puede determinar',PROVEN_ABSENT:'Ausencia demostrada',NOT_APPLICABLE:'No aplica demostrado',CONFLICT:'Datos en conflicto',EXECUTED:'Ejecutado',INCOMPLETE:'Incompleto',NOT_STARTED:'Sin iniciar',NOT_APPLICABLE_DEMONSTRATED:'No aplica demostrado',NO_FINDING_DEMONSTRATED:'Sin observación demostrada',WITH_FINDING:'Con hallazgo',CLEAN_DEMONSTRATED:'Sin observaciones demostradas',OBSERVATIONS_CONFIRMED:'Con observaciones',INCOMPLETE_REVIEW:'Revisión incompleta',PENDING_EXTERNAL_CHECK:'Verificación externa pendiente',MANUAL_CONFIRMATION_REQUIRED:'Falta confirmación humana',EVIDENCE_MISSING:'Faltan datos o evidencia obligatoria',FINDING_REVIEW_REQUIRED:'Hallazgo pendiente de decisión',DRAFT_SYSTEM:'Borrador del sistema',HUMAN_EDITED:'Editada por el auditor',GENERAL_RF_PARTICIPACIONES:'General · RF / Participaciones',RF:'Recursos Fiscales',PARTICIPACIONES:'Participaciones Federales',GENERAL:'General',CASE:'Expediente operativo',DOCUMENT:'Documento',NORMALIZED:'Comprobante interpretado',REVISION:'Revisión exacta',SUBMIT:'Enviar a revisión',REVIEW:'Marcar revisado',RETURN:'Devolver para corrección',AUTHORIZE:'Autorizar',REOPEN:'Reabrir',SAMPLE_ITEM_MATERIAL_CHANGED:'Decisión retirada por cambio material de selección',
 DOCUMENT_SUPPORT:'Soporte documental',CFDI:'CFDI',PAYMENT_SUPPORT:'Soporte del pago',PAYMENT_ORDER:'Orden de pago',AUTHORIZATIONS:'Firmas y autorizaciones',EXTERNAL_CONFIRMATIONS:'Compulsa y 69-B',BOND_CONFIRMATION:'Fianza',SUPPORT_INVENTORY:'Inventario de soportes',BENEFICIARY_RECEIPT:'Recepción del beneficiario',BUDGET_CLASSIFICATION:'Clasificación presupuestal',ACCOUNTING_REGISTRATION:'Registro contable',APPLICATION_JUSTIFICATION:'Aplicación y justificación',A20_REFERENCE:'Referencia A-20',AUXILIARY:'Auxiliar contable',GENERAL_JOURNAL:'Libro diario',OBSERVATIONS:'Observaciones heredadas',
 POLICY_NUMBER:'Número oficial de póliza',CASE_REFERENCE:'Referencia interna CAROVA',CONCEPT:'Concepto',POLICY_TYPE:'Tipo de póliza',POLICY_DATE:'Fecha de póliza',AMOUNT:'Importe',SUPPLIER:'Proveedor',PAYMENT_REFERENCE:'Referencia del pago',PAYMENT_DATE:'Fecha de pago',PAYMENT_AMOUNT:'Importe pagado',BANK_ACCOUNT:'Cuenta bancaria',BANK:'Banco',FUND:'Fondo',ACCOUNT_OPENING_DATE:'Fecha de apertura de cuenta',FISCAL_REQUIREMENTS:'Requisitos fiscales',SUPPLIER_CONFIRMATION:'Compulsa del proveedor',ARTICLE_69B:'Verificación 69-B',SUPPORT_DOCUMENTS:'Documentos de soporte',REQUIRED_SIGNATURES:'Firmas requeridas',BUDGET_ITEM:'Partida presupuestal',ACCOUNTING_ACCOUNT:'Cuenta contable',ACCOUNTING_AMOUNT:'Importe contable',APPLICATION:'Aplicación (materiales / maquinaria)',
};
export function label(value?:string|null):string { return value ? labels[value] ?? (['A-20','A-21','PDF','XLSX'].includes(value)?value:'Sin clasificación disponible') : 'No informado'; }
export function errorMessage(status:number):string {return status===403?'No tienes permiso para realizar esta acción.':status===404?'El registro no está disponible en tu alcance.':status===409?'El papel fue modificado o su evidencia/dependencia dejó de ser vigente. Se actualizó la vista; revisa antes de continuar.':status===400?'Faltan datos o evidencia obligatoria, o los valores no cumplen el contrato.':'No fue posible completar la operación. Intenta actualizar.';}
export function sourceName(s:Source):string {return s.metadata.reference || s.metadata.pbc_name || s.metadata.fields?.file_name || label(s.kind);}
export function safeDownload(a:Artifact):string|null {return a.state==='CURRENT' && a.download_url && /^\/api\/carova\/audit\/artifacts\/[a-f0-9]{64}\/file\/$/.test(a.download_url)?a.download_url:null;}
export function inbox(papers:Paper[],tab:string):Paper[] {return papers.filter(p=>tab==='review'?['READY_FOR_REVIEW','RETURNED','REVIEWED'].includes(p.status):tab==='authorize'?p.status==='REVIEWED'&&p.state==='CURRENT':true);}
export function allowed(p:Paper,action:string):boolean {return p.actions[action]===true;}

export type ExactRevision = {ref:string;revision_ref:string;number:number;code:string;name:string;status_at_revision:string;current:boolean;historical:boolean;has_later_revision:boolean;snapshot:Record<string,unknown>;events:{decision:string;actor:string;reason:string;timestamp:string}[]};
