'use client';
import {useEffect,useState} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {apiFetch} from '../../lib/api';
import {usePanelUser} from '../../lib/PanelUserContext';
import {rangePreset,engineLabels,engineState,reportingViews,employeeViews,reportLink,type ReportData,type Pending,type Activity,type ClientRow,type Employee} from '../../lib/platform';
import PageHeader from './PageHeader';
import DataTable from './DataTable';
import StatusBadge from './StatusBadge';
import LoadingState from './LoadingState';
import ErrorState from './ErrorState';
import ChartCard from './ChartCard';
import ReportingPanels from './ReportingPanels';
import Ranking from './Ranking';
import {ResumeWork,workKey} from './WorkNavigation';
import DateRangeFilter from './DateRangeFilter';
import {apiErrorMessage} from '../../app/panel/carova/egresos/ux';

type Mode='home'|'clients'|'workspace'|'work'|'team'|'reports';
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('es-MX',{day:'numeric',month:'short'}):'Sin actividad registrada';
function Metric({label,value,note,href}:{label:string;value:string|number;note?:string;href?:string}){return <div className="platformMetric">{href?<Link href={href}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</Link>:<><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</>}</div>;}
function Pages({page,count,size,change}:{page:number;count:number;size:number;change:(n:number)=>void}){return <nav className="platformPages" aria-label="Paginación"><span>{count} registros · Página {page} de {Math.max(1,Math.ceil(count/size))}</span><button disabled={page<=1} onClick={()=>change(page-1)}>Anterior</button><button disabled={page*size>=count} onClick={()=>change(page+1)}>Siguiente</button></nav>;}
function ActivityTable({data,onDetail}:{data:ReportData;onDetail:(a:Activity)=>void}){return <DataTable rows={data.activity.results} getRowKey={r=>r.id} emptyMessage="No hay acciones humanas registradas en este rango." columns={[{key:'date',header:'Fecha',render:r=>new Date(r.date).toLocaleString('es-MX')},{key:'employee',header:'Persona / cliente',render:r=><><strong>{r.employee}</strong><small>{r.client} · {r.period}</small></>},{key:'activity',header:'Actividad',render:r=><>{r.display_label}<small>{engineLabels[r.engine]}</small></>},{key:'category',header:'Categoría / resultado',render:r=><>{r.display_category==='PENDIENTES'?'Pendientes':engineLabels[r.display_category]||r.display_category}<small>{r.status}</small></>},{key:'duration',header:'Duración',render:()=> 'No registrada'},{key:'detail',header:'Detalle',render:r=><button onClick={()=>onDetail(r)}>Ver detalle</button>}]}/>;}
function PendingTable({rows,onDetail}:{rows:Pending[];onDetail:(p:Pending)=>void}){return <DataTable rows={rows} getRowKey={r=>r.id} emptyMessage="No hay pendientes con estos filtros." columns={[{key:'client',header:'Cliente / periodo',render:r=><><strong>{r.client}</strong><small>{r.period} · {engineLabels[r.engine]}</small></>},{key:'description',header:'Atención requerida',render:r=><button className="platformTextButton" onClick={()=>onDetail(r)}>{r.description}</button>},{key:'responsible',header:'Responsable',render:r=>r.responsible},{key:'age',header:'Antigüedad',render:r=>`${r.age_days} días`},{key:'status',header:'Estado',render:r=><StatusBadge label={r.status_label} tone={r.status==='OPEN'?'yellow':'gray'}/>},{key:'action',header:'Acción',render:r=><Link href={r.href}>Atender →</Link>}]}/>;}

export default function Platform({mode,clientId,employeeId}:{mode:Mode;clientId?:string;employeeId?:string}){
 const {user}=usePanelUser(),router=useRouter(),path=usePathname(),search=useSearchParams();
 const [options,setOptions]=useState<{clients:{id:number;name:string}[];employees:{id:number;name:string}[];periods:{id:number;client_id:number;client:string;label:string}[]}>({clients:[],employees:[],periods:[]});
 useEffect(()=>{const c=new AbortController();setOptions({clients:[],employees:[],periods:[]});if(user?.organization_id)void apiFetch('/api/carova/reports/filters/',{signal:c.signal}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!c.signal.aborted)setOptions(d);}).catch(()=>{});return()=>c.abort();},[user?.organization_id]);
 const [data,setData]=useState<ReportData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [detail,setDetail]=useState<Pending|Activity|null>(null),[exporting,setExporting]=useState(false);
 const [sections,setSections]=useState(['summary','charts','clients','team','pendings','activity']),[reportMode,setReportMode]=useState('summary');
 const managed=user?.is_superuser||['manager','partner'].includes(user?.role||'');
 const params=new URLSearchParams(search.toString());
 if(clientId)params.set('client_id',clientId);if(employeeId){params.set('employee_id',employeeId);params.set('type','employee');}
 if(mode==='workspace'){params.set('type',params.get('period_id')?'period':'client');}
 if(!params.get('desde')||!params.get('hasta')){const r=rangePreset('month');if(!params.get('desde'))params.set('desde',r.desde);if(!params.get('hasta'))params.set('hasta',r.hasta);}
 if(mode==='work'&&!params.has('status'))params.set('status','OPEN');
 const requestParams=new URLSearchParams(params);if(requestParams.get('status')==='all')requestParams.delete('status');
 const individual=!!employeeId||params.get('type')==='employee',reportView=search.get('view')||'Resumen';
 const query=requestParams.toString(),page=Number(params.get('page')||1),tab=search.get('tab')||'Resumen';
 function update(values:Record<string,string>){const p=new URLSearchParams(search.toString());Object.entries(values).forEach(([k,v])=>{if(v)p.set(k,v);else p.delete(k);});if(!('page' in values))p.delete('page');router.replace(path+(p.size?'?'+p:''),{scroll:false});}
 useEffect(()=>{setData(null);if(!user?.organization_id)return;const c=new AbortController();setLoading(true);setError('');void apiFetch('/api/carova/reports/?'+query,{signal:c.signal}).then(async r=>{if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(apiErrorMessage(e,r.status));}return r.json();}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[query,user?.organization_id,refresh]);
 useEffect(()=>{if(!detail)return;const dialog=document.getElementById('platform-detail') as HTMLDialogElement|null;dialog?.showModal();return()=>dialog?.close();},[detail]);
 async function download(fmt:string){setExporting(true);setError('');try{const p=new URLSearchParams(query);p.set('format',fmt);p.set('mode',reportMode);p.set('sections',sections.join(','));const r=await apiFetch('/api/carova/reports/?'+p);if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(apiErrorMessage(e,r.status));}const b=await r.blob(),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`carova-${params.get('type')||'general'}.${fmt==='manifest'?'json':fmt}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'No se pudo descargar.');}finally{setExporting(false);}}
 const titles={home:'Tu mesa de trabajo',clients:'Clientes',workspace:data?.clients[0]?.name||'Espacio del cliente',work:'Pendientes',team:employeeId?data?.employees.find(u=>String(u.id)===employeeId)?.name||'Reporte de empleado':'Equipo',reports:'Reportes'};
 const isReport=mode==='reports'||!!employeeId||(mode==='workspace'&&tab==='Reportes');
 const range=`${params.get('desde')} — ${params.get('hasta')}`;
 const selected=data?.periods.find(p=>String(p.id)===params.get('period_id'));
 useEffect(()=>{if(mode!=='workspace'||!selected||!user?.id||!user.organization_id||loading)return;try{sessionStorage.setItem(workKey(user.id,user.organization_id),JSON.stringify({href:path+'?'+search,workspace:path+'?'+search,client:selected.client,period:selected.label,periodId:selected.id}));}catch{}},[mode,selected,user?.id,user?.organization_id,loading,path,search]);

 return <div className="platform"><div className="platformEyebrow">{mode==='workspace'?'CLIENTE Y PERIODO':mode==='home'?'OPERACIÓN DIARIA':'DESPACHO'}</div>
 <PageHeader title={titles[mode]} description={mode==='home'?`Buen día, ${user?.username||''}. Empieza por lo que necesita tu atención.`:mode==='workspace'?'Un solo contexto para revisar el trabajo, su evidencia y sus resultados.':mode==='reports'?'Información operacional con alcance y fuentes verificables.':undefined} actions={isReport?<button className="platformPrimary" disabled={!data||exporting} onClick={()=>void download('pdf')}>{exporting?'Generando…':'Descargar PDF'}</button>:<Link className={mode==='home'?'':'platformPrimary'} href={mode==='home'?'/panel/trabajo':mode==='work'?'/panel/carova/egresos':mode==='team'?'/panel/time-tracking/registros':mode==='workspace'&&selected?selected.engines[0].href:mode==='workspace'?reportLink('/panel/reportes',query,{type:'client'}):'/panel/reportes'}>{mode==='home'?'Revisar pendientes':mode==='work'?'Abrir operación':mode==='team'?'Registrar tiempo':mode==='workspace'&&selected?'Continuar trabajo':'Generar reporte'}</Link>}/>
 {mode==='workspace'&&<p className="uxLegacyNotice">Periodos y actividad del contrato histórico. Sus conteos no incluyen todos los módulos actuales. <Link href="/panel/clientes">Abrir pendientes transversales por cliente →</Link></p>}
 {mode==='workspace'&&<nav className="platformTabs" aria-label="Secciones del cliente">{['Resumen','Operación','Documentos','Pendientes','Actividad','Reportes'].map(t=><button aria-current={tab===t?'page':undefined} key={t} onClick={()=>update({tab:t})}>{t}</button>)}</nav>}
 {(mode==='reports'||employeeId)&&<nav className="platformTabs" aria-label={individual?'Secciones del empleado':'Ejes de reporting'}>{(individual?employeeViews:reportingViews).map(v=><button key={v} aria-current={reportView===v?'page':undefined} onClick={()=>update({view:v})}>{v}</button>)}</nav>}

 {isReport&&data&&!loading&&<section aria-label="Estadísticas del alcance"><div className="platformMetrics"><Metric label="Actividad efectiva" value={data.metrics.activities} href={reportLink(path,query,{view:"Actividad",...(mode==='workspace'?{tab:"Actividad"}:{})})}/><Metric label="Empleados activos" value={data.analytics.metrics.active_employees} note="Con actividad humana en el rango"/><Metric label="Clientes trabajados" value={data.analytics.metrics.clients}/><Metric label="Periodos trabajados" value={data.analytics.metrics.periods_worked}/><Metric label="Pendientes resueltos" value={data.metrics.resolved_pendings} href={reportLink("/panel/trabajo",query,{status:"RESOLVED"})}/><Metric label="Pendientes abiertos" value={data.metrics.open_pendings} note="Carga actual" href={reportLink("/panel/trabajo",query,{status:"OPEN"})}/></div><p className="platformMuted">{range} · {data.coverage}</p>{['Resumen','Reportes','Equipo','Empleados'].includes(reportView)&&<Ranking data={data} query={query} onMetric={v=>update({ranking_metric:v})}/>}</section>}
 {mode==='home'&&data&&!loading&&<ResumeWork periodIds={data.periods.map(p=>p.id)}/>}
 {mode==='team'&&managed&&<p><Link href={'/panel/configuracion/usuarios'+(employeeId?'?edit='+employeeId+'&return='+encodeURIComponent(path+'?'+query):'')}> {employeeId?'Editar usuario · Organización, rol y estado':'Administrar usuarios y organizaciones'} →</Link></p>}
 {mode!=='home'&&<nav aria-label="Volver al contexto"><button onClick={()=>router.back()}>← Volver</button> <Link href={reportLink('/panel/reportes',query,{type:'general',employee_id:''})}>Reportes del alcance</Link></nav>}
 <details className="platformFilterDetails" open={mode==='workspace'||mode==='work'||mode==='clients'}><summary>Filtros del alcance · {options.clients.find(c=>String(c.id)===params.get('client_id'))?.name||'Clientes autorizados'}{params.get('period_id')?' · '+(options.periods.find(p=>String(p.id)===params.get('period_id'))?.label||'Periodo seleccionado'):''}{params.get('employee_id')?' · '+(options.employees.find(e=>String(e.id)===params.get('employee_id'))?.name||'Empleado seleccionado'):''}{params.get('engine')?' · '+engineLabels[params.get('engine')||'']:''}</summary>
 <div className="platformFilters" role="search" aria-label="Filtros de trabajo y reportes">
 {!clientId&&<label>Cliente<select value={params.get('client_id')||''} onChange={e=>update({client_id:e.target.value,period_id:''})}><option value="">Clientes autorizados</option>{options.clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}
 {['workspace','reports','work','team'].includes(mode)&&<label>Periodo<select value={params.get('period_id')||''} onChange={e=>update({period_id:e.target.value})}><option value="">Periodos autorizados</option>{options.periods.filter(p=>!(clientId||params.get('client_id'))||String(p.client_id)===(clientId||params.get('client_id'))).map(p=><option key={p.id} value={p.id}>{clientId?'':p.client+' · '}{p.label}</option>)}</select></label>}
 {mode!=='home'&&mode!=='clients'&&<label>Origen<select value={params.get('engine')||''} onChange={e=>update({engine:e.target.value})}><option value="">Todos los orígenes</option>{Object.entries(engineLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}
 {managed&&!employeeId&&['team','reports','work','workspace'].includes(mode)&&<label>Empleado<select value={params.get('employee_id')||''} onChange={e=>update({employee_id:e.target.value})}><option value="">Equipo autorizado</option>{options.employees.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>}
 {managed&&['team','reports'].includes(mode)&&!individual&&<><label>Rol<select value={params.get('role')||''} onChange={e=>update({role:e.target.value})}><option value="">Todos los roles</option>{[['staff','Auxiliar'],['senior','Senior'],['manager','Gerencia'],['partner','Socio']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>Estado del usuario<select value={params.get('user_state')||'active'} onChange={e=>update({user_state:e.target.value})}><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select></label></>}
 <label>Buscar<input type="search" key={search.get('q')||''} defaultValue={search.get('q')||''} placeholder="Cliente, actividad o pendiente" onKeyDown={e=>{if(e.key==='Enter')update({q:e.currentTarget.value});}} onBlur={e=>{if(e.currentTarget.value!==(search.get('q')||''))update({q:e.currentTarget.value});}}/></label><button onClick={()=>{router.replace(path);setRefresh(n=>n+1);}}>Limpiar</button>
 </div>
 </details>
 {(isReport||mode==='home'||mode==='team'||mode==='workspace'&&tab==='Actividad')&&<div className="platformRange"><label>Rango<select value="" onChange={e=>{if(e.target.value)update(rangePreset(e.target.value));}}><option value="">Personalizado</option><option value="today">Hoy</option><option value="last7">7 días</option><option value="previous">Mes anterior</option><option value="week">Esta semana</option><option value="month">Este mes</option></select></label><DateRangeFilter desde={params.get('desde')||''} hasta={params.get('hasta')||''} onDesdeChange={v=>update({desde:v})} onHastaChange={v=>update({hasta:v})}/></div>}
 {isReport&&<div className="platformFilters"><label>Granularidad<select value={params.get('granularity')||'auto'} onChange={e=>update({granularity:e.target.value})}><option value="auto">Según rango</option><option value="day">Por día</option><option value="week">Por semana</option></select></label><label>Resultado de actividad<select value={params.get('result')||''} onChange={e=>update({result:e.target.value})}><option value="">Resultados cubiertos</option><option value="registered">Registrada</option></select></label></div>}
 {isReport&&reportView==='Pendientes'&&<div className="platformFilters"><label>Estado del pendiente<select value={params.get('status')||''} onChange={e=>update({status:e.target.value})}><option value="">Todos</option><option value="OPEN">Abiertos</option><option value="RESOLVED">Resueltos</option><option value="SUPERSEDED">Sustituidos</option></select></label><label>Antigüedad mínima<select value={params.get('age')||''} onChange={e=>update({age:e.target.value})}><option value="">Cualquier antigüedad</option><option value="7">7 días</option><option value="15">15 días</option><option value="30">30 días</option></select></label></div>}
 {error&&<ErrorState message={error} onRetry={()=>setRefresh(n=>n+1)}/>}{loading&&<LoadingState label="Consultando tu alcance autorizado…"/>}
 {data&&!loading&&<>
 {(mode==='home'||(mode==='workspace'&&tab==='Resumen'))&&<><div className="platformMetrics"><Metric label="Pendientes abiertos" value={data.metrics.open_pendings} note="Carga actual" href={reportLink("/panel/trabajo",query,{status:"OPEN"})}/><Metric label="Resueltos" value={data.metrics.resolved_pendings} note="Dentro del rango"/><Metric label="Acciones registradas" value={data.metrics.activities} note="Acciones humanas verificables"/><Metric label="Casos asignados" value={data.metrics.cases??'No atribuible'} note={data.metrics.cases===null?'Sin atribución fiable al filtro':`${data.metrics.completed_cases} terminados o cerrados`}/></div><p className="platformMuted">{data.pending_notice}</p></>}

 {isReport&&<details className="platformExport"><summary>Personalizar PDF</summary><div className="platformBuilder">{mode==='reports'&&<label>Tipo de reporte<select value={params.get('type')||'general'} onChange={e=>update({type:e.target.value})}>{[['general',managed?'Despacho general':'Mi alcance'],...(managed?[['team','Equipo']]:[]),['employee','Empleado'],['client','Cliente'],['period','Periodo']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}<label>Modo<select value={reportMode} onChange={e=>setReportMode(e.target.value)}><option value="full">Completo</option><option value="summary">Resumen</option></select></label><details><summary>Secciones del PDF</summary>{[['summary','Resumen'],['charts','Gráficas'],['clients','Clientes y periodos'],['team','Equipo'],['pendings','Pendientes'],['activity','Actividad y asignaciones'],['technical','Anexo técnico'],...(managed?[['employees_detail','Incluir detalle por empleado']]:[])].map(([v,t])=><label key={v}><input type="checkbox" checked={sections.includes(v)} onChange={e=>setSections(e.target.checked?[...sections,v]:sections.filter(x=>x!==v))}/>{t}</label>)}</details></div></details>}
 {(mode==='reports'||!!employeeId||mode==='workspace'&&tab==='Reportes')&&<ReportingPanels data={data} query={query} view={reportView} individual={individual} client={!!params.get('client_id')}/>}
 {mode==='home'&&<><div className="platformSectionHead"><h2>Requieren atención</h2><Link href="/panel/trabajo">Ver pendientes →</Link></div>{data.attention.length?<div className="platformAttention">{data.attention.slice(0,6).map((a,i)=><Link key={i} href={reportLink(a.href,query)}><span><strong>{a.client}</strong><small>{a.period}</small></span><span>{a.reason}</span><span aria-hidden="true">→</span></Link>)}</div>:<div className="platformEmpty">No hay pendientes abiertos en tu alcance.</div>}<div className="platformSectionHead"><h2>Periodos activos</h2><Link href="/panel/clientes">Ver clientes →</Link></div><div className="platformPeriodList">{data.periods.slice(0,6).map(p=><Link href={reportLink(p.href,query)} key={p.id}><strong>{p.client}</strong><span>{p.label}</span><StatusBadge label={p.status_label}/><span>{p.pending_count} pendientes →</span></Link>)}</div>{!data.periods.length&&<p className="platformEmpty">No tienes periodos asignados. La gerencia puede prepararlos en Operación.</p>}<p><Link href={reportLink("/panel/trabajo",query,{employee_id:String(user?.id),status:"OPEN"})}>Mis pendientes →</Link></p>{managed&&<ReportingPanels data={data} query={query} view="Empleados"/>}<div className="platformSectionHead"><h2>Actividad reciente</h2><Link href="/panel/reportes">Consultar reporte →</Link></div><ActivityTable data={data} onDetail={setDetail}/></>}
 {mode==='clients'&&<><DataTable<ClientRow> rows={data.clients} getRowKey={r=>r.id} emptyMessage="No hay clientes asignados con estos filtros." columns={[{key:'client',header:'Cliente',render:r=><Link href={reportLink(`/panel/clientes/${r.id}`,query,{client_id:String(r.id),type:"client"})}><strong>{r.name}</strong></Link>},{key:'responsible',header:'Responsables',render:r=>r.responsibles.join(', ')||'Sin paquete asignado'},{key:'period',header:'Último periodo',render:r=>r.current_period||'Sin periodo'},{key:'pending',header:'Pendientes',render:r=>r.pending_count},{key:'status',header:'Situación',render:r=><StatusBadge label={r.state} tone={r.pending_count?'yellow':'gray'}/>},{key:'activity',header:'Última acción',render:r=>date(r.last_activity)}]}/>{managed&&<p><Link href="/panel/clientes/administrar">Administrar catálogo de clientes →</Link></p>}</>}
 {mode==='workspace'&&<><div className="platformContext"><strong>{selected?selected.label:'Todos los periodos visibles'}</strong><span>{selected?.responsibles.join(', ')||'Responsables por paquete'}</span>{selected&&<StatusBadge label={selected.status_label}/>}<span>Último trabajo: {date(selected?.updated_at||null)}</span></div>{!selected&&<div className="platformPeriodList">{data.periods.map(p=><Link key={p.id} href={reportLink(p.href,query)}><strong>{p.label}</strong><StatusBadge label={p.status_label}/><span>{p.pending_count} pendientes →</span></Link>)}</div>}{['Resumen','Operación'].includes(tab)&&selected&&<><div className="platformEngineGrid">{selected.engines.map(e=><section key={e.engine}><h2>{engineLabels[e.engine]}</h2><StatusBadge label={engineState(e)} tone={e.state==='STALE'?'yellow':'gray'}/><p>{e.pending_count} pendientes abiertos</p><p>{e.changed?`${e.changed} resultados con evidencia modificada`:'Consulta las diferencias y evidencia del periodo.'}</p><small>{e.updated_at?`Última ejecución: ${date(e.updated_at)}`:'Todavía no hay una ejecución registrada.'}</small><Link href={e.href}>Revisar {engineLabels[e.engine].toLowerCase()} →</Link></section>)}<section><h2>Documentos</h2><p>{data.documents?`${data.documents.count} archivos del encargo autorizado`:'Recepción y evidencia del periodo'}</p>{data.documents&&<small>{data.documents.scope}</small>}<Link href={data.capabilities.documents?`/panel/carova/documentos?period_id=${selected.id}&client_id=${clientId}`:selected.engines[0].href.replace('Automatizaci%C3%B3n','Recepci%C3%B3n')}>Consultar documentos →</Link></section></div><p className="platformMuted">Los resultados son operacionales; no afirman que la contabilidad o el IVA sean correctos.</p></>}{tab==='Documentos'&&<div className="platformEmpty"><h2>Evidencia del cliente</h2><p>Consulta el original, su origen y las relaciones autorizadas en el expediente.</p>{selected?<Link href={data.capabilities.documents?`/panel/carova/documentos?period_id=${selected.id}&client_id=${clientId}`:selected.engines[0].href.replace('Automatizaci%C3%B3n','Recepci%C3%B3n')}>Abrir biblioteca del periodo →</Link>:<p>Selecciona un periodo para continuar.</p>}</div>}{tab==='Actividad'&&<ActivityTable data={data} onDetail={setDetail}/>}</>}
 {(mode==='work'||mode==='workspace'&&tab==='Pendientes')&&<><div className="platformFilters"><button aria-pressed={params.get('employee_id')===String(user?.id)} onClick={()=>update({employee_id:String(user?.id)})}>Mis pendientes</button><button onClick={()=>update({employee_id:''})}>Todo mi alcance</button><label>Estado<select value={params.get('status')==='all'?'':params.get('status')||''} onChange={e=>update({status:e.target.value||'all'})}><option value="">Todos</option><option value="OPEN">Abiertos</option><option value="RESOLVED">Resueltos</option><option value="SUPERSEDED">Sustituidos</option></select></label><label>Antigüedad<select value={params.get('age')||''} onChange={e=>update({age:e.target.value})}><option value="">Cualquier antigüedad</option><option value="7">7 días o más</option><option value="15">15 días o más</option><option value="30">30 días o más</option></select></label></div><p className="platformMuted">{data.pending_notice}</p><PendingTable rows={data.pendings.results} onDetail={setDetail}/><Pages page={page} count={data.pendings.count} size={30} change={n=>update({page:String(n)})}/></>}
 {mode==='team'&&!employeeId&&<ReportingPanels data={data} query={query} view="Empleados"/>}
 {isReport&&<><div className="platformReportHeading"><span>ALCANCE DEL REPORTE</span><p>{data.coverage}</p><p>{data.scope.full?'Visión gerencial del contexto seleccionado.':'Sólo información actualmente autorizada para tu asignación.'}</p></div>{['Resumen','Reportes','Clientes'].includes(reportView)&&<div className="platformCharts"><ChartCard title={`Actividad en el tiempo · ${data.series.granularity==='week'?'semanal':'diaria'}`} points={data.series.temporal} line range={range}/><ChartCard title="Actividad por cliente · hasta 20" points={data.series.clients} range={range}/><ChartCard title="Distribución por tipo" points={data.series.types} range={range}/><section className="platformChart"><h2>Tiempo declarado</h2><strong className="platformBig">{data.metrics.recorded_minutes===null?'Sin registro':`${(data.metrics.recorded_minutes/60).toLocaleString('es-MX',{maximumFractionDigits:2})} h`}</strong><p>{data.metrics.time_records} registros</p><p className="platformMuted">{data.time_notice}</p></section></div>} {['Resumen','Actividad','Reportes'].includes(reportView)&&<><div className="platformSectionHead"><h2>Actividad detallada</h2><label>Orden<select value={params.get('order')||'newest'} onChange={e=>update({order:e.target.value})}><option value="newest">Más reciente</option><option value="oldest">Más antigua</option></select></label><label>Tipo<select value={params.get('activity_type')||''} onChange={e=>update({activity_type:e.target.value})}><option value="">Todos</option><option value="EGRESOS">Egresos</option><option value="DOCUMENTOS">Documentos</option><option value="PENDIENTES">Pendientes</option></select></label></div><ActivityTable data={data} onDetail={setDetail}/><Pages page={page} count={data.activity.count} size={30} change={n=>update({page:String(n)})}/><details className="platformExport"><summary>Exportar tabla de actividad</summary><p>CSV/XLSX: todas las acciones del filtro, máximo 2000; si se supera, reduce el rango. El manifiesto contiene las fuentes y el alcance.</p><button disabled={exporting} onClick={()=>void download('csv')}>Descargar CSV</button><button disabled={exporting} onClick={()=>void download('xlsx')}>Descargar Excel</button><button disabled={exporting} onClick={()=>void download('manifest')}>Manifiesto de fuentes</button></details></>} {['Resumen','Pendientes','Reportes'].includes(reportView)&&<><h2>Pendientes</h2><PendingTable rows={data.pendings.results} onDetail={setDetail}/><Pages page={page} count={data.pendings.count} size={30} change={n=>update({page:String(n)})}/></>}</>}
 </>}
 <div className="platformTools"><details><summary>Herramientas del despacho</summary><Link href="/panel/encargos">Encargos</Link><Link href="/panel/pbc">Solicitudes PBC</Link><Link href="/panel/documentos">Documentos PBC</Link><Link href="/panel/carova">Operación documental</Link><Link href="/panel/time-tracking/registros">Registro de tiempo</Link><Link href="/panel/time-tracking">Control de horas</Link><Link href="/panel/time-tracking/reportes">Reportes de horas</Link>{managed&&<Link href="/panel/configuracion/usuarios">Usuarios y organizaciones</Link>}</details></div>
 {detail&&<dialog id="platform-detail" className="platformDialog" onCancel={()=>setDetail(null)}><div className="platformSectionHead"><h2>Detalle</h2><button autoFocus onClick={()=>setDetail(null)}>Cerrar</button></div>{'description' in detail?<><h3>{detail.description}</h3><p>{detail.reason}</p><p><strong>Siguiente acción:</strong> {detail.required_action}</p><p>{detail.client} · {detail.period} · {detail.responsible}</p><details><summary>Datos técnicos y evidencia</summary><p>{detail.code} · {detail.status}</p><p>Documento: {detail.document_id??'Sin archivo vinculado'} · Movimiento: {detail.movement_id??'Sin movimiento vinculado'}</p></details></>:<><h3>{detail.display_label}</h3><p>{detail.employee} · {detail.client} · {detail.period}</p><p>{new Date(detail.date).toLocaleString('es-MX')} · {detail.status}</p><p>{detail.display_category==='PENDIENTES'?'Pendientes':engineLabels[detail.display_category]||detail.display_category} · {engineLabels[detail.engine]} · Duración no registrada</p><Link href={reportLink(`/panel/clientes/${detail.client_id}`,query,{period_id:detail.period_id?String(detail.period_id):'',tab:'Actividad'})}>Ver cliente y periodo →</Link><details><summary>Evento original</summary><p>{detail.raw_event_type} · {detail.entity}</p><p>Actividad humana registrada; duración por evento no disponible.</p></details></>}<p><Link href={detail.href}>Abrir contexto de trabajo →</Link></p></dialog>}
 </div>;
}
