'use client';
import Link from 'next/link';
import {useState} from 'react';
import DataTable from './DataTable';
import ChartCard from './ChartCard';
import {reportLink,type ReportData,type Relation} from '../../lib/platform';

const stamp=(s:string|null)=>s?new Date(s).toLocaleString('es-MX'):'Sin actividad registrada';
export default function ReportingPanels({data,query,view,individual=false,client=false}:{data:ReportData;query:string;view:string;individual?:boolean;client?:boolean}){
 const a=data.analytics,[matrixMetric,setMatrixMetric]=useState<'activities'|'open_pendings'|'periods_worked'|'active_assignments'>('activities');
 const range=`${data.range.from} — ${data.range.to}`;
 const summary=view==='Resumen'||view==='Reportes';
 const employee=(id:number,cid?:number)=>reportLink(`/panel/equipo/${id}`,query,{type:'employee',employee_id:String(id),...(cid?{client_id:String(cid)}:{})});
 const customer=(id:number)=>reportLink(`/panel/clientes/${id}`,query,{type:'client',client_id:String(id),tab:'Reportes'});
 const team=(summary||['Equipo','Empleados'].includes(view))&&!individual;
 const customers=(summary||view==='Clientes')&&individual||view==='Clientes'&&!individual;
 const periods=view==='Periodos'||individual&&summary;
 return <>
 {individual&&<section className="platformEmployeeHeader" aria-label="Perfil operativo">{a.employees.map(u=><div key={u.id}><strong>{u.name}</strong><span>{u.role_label} · {u.is_active?'Activo':'Inactivo'}</span><span>Última actividad: {stamp(u.last_activity)}</span><span>{a.workload_available?`${u.assigned_clients} clientes asignados · ${u.active_periods} periodos activos`:'Carga actual no atribuible al filtro de actividad'}</span></div>)}</section>}
 {summary&&<>
 {!individual&&<section><h2>Clientes que requieren atención</h2><div className="platformAttention">{data.attention.length?data.attention.slice(0,6).map((p,i)=><Link key={i} href={p.href}><strong>{p.client} · {p.period}</strong><span>{p.reason}</span><span aria-hidden="true">→</span></Link>):<p>No hay pendientes abiertos en este alcance.</p>}</div>{data.attention.length>6&&<p><Link href={reportLink('/panel/trabajo',query,{status:'OPEN'})}>Ver los {data.attention.length} periodos con pendientes →</Link></p>}</section>}</>}
 {team&&<section><h2>{client?'Equipo que trabajó en este cliente':'Equipo · actividad y carga'}</h2><DataTable rows={client?a.employees.filter(u=>u.activities||u.active_assignments||u.open_pendings||u.resolved_pendings):a.employees} getRowKey={r=>r.id} emptyMessage="No hay actividad registrada en este rango." columns={[
 {key:'name',header:'Empleado / rol',render:r=><Link href={employee(r.id)}><strong>{r.name}</strong><small>{r.role_label} · {r.is_active?'Activo':'Inactivo'}</small></Link>},
 {key:'clients',header:'Clientes trabajados',render:r=>r.clients},{key:'periods',header:'Periodos trabajados',render:r=>r.periods_worked},{key:'activity',header:'Actividades',render:r=>r.activities},
 {key:'resolved',header:'Resueltos',render:r=>r.resolved_pendings},{key:'open',header:'Abiertos',render:r=>r.open_pendings},{key:'assigned',header:'Asignaciones activas',render:r=>a.workload_available?r.active_assignments:'No atribuible'},{key:'last',header:'Última actividad',render:r=>stamp(r.last_activity)}]}/>
 {client&&<ChartCard title="Actividad del cliente por empleado" points={a.employees.filter(u=>u.activities).slice(0,20).map(u=>({label:u.name,value:u.activities}))} range={range}/>}
 </section>}
 {customers&&<section><h2>{individual?'Clientes en los que trabajó':'Clientes · actividad y asignaciones'}</h2><p className="platformMuted">Tabla completa del alcance autorizado; la gráfica muestra hasta 20 clientes.</p><DataTable rows={a.employee_clients} getRowKey={r=>r.id} emptyMessage="No hay actividad ni asignaciones en este alcance." columns={[
 {key:'name',header:'Cliente',render:r=><Link href={customer(r.id)}>{r.name}</Link>},{key:'activities',header:'Actividades',render:r=>r.activities},{key:'periods',header:'Periodos trabajados',render:r=>r.periods_worked},{key:'resolved',header:'Resueltos',render:r=>r.resolved_pendings},{key:'open',header:'Abiertos',render:r=>r.open_pendings},{key:'last',header:'Última actividad',render:r=>stamp(r.last_activity)},{key:'assigned',header:'Asignación actual',render:r=>a.workload_available?`${r.client_memberships?'Miembro del cliente · ':''}${r.active_assignments} paquetes activos`:'No atribuible'}]}/></section>}
 {periods&&<section><h2>Actividad por periodo contable</h2><DataTable<Relation> rows={a.employee_periods} getRowKey={r=>`${r.employee_id}-${r.client_id}-${r.period_id}`} emptyMessage="No hay periodos con actividad ni carga en este alcance." columns={[
 {key:'client',header:'Cliente / periodo',render:r=><Link href={reportLink(r.href,query,{client_id:String(r.client_id),period_id:r.period_id?String(r.period_id):'',employee_id:individual?String(r.employee_id):'',tab:'Actividad'})}><strong>{r.client}</strong><small>{r.period} · {r.period_status}</small></Link>},{key:'employee',header:'Empleado',render:r=><Link href={employee(r.employee_id,r.client_id)}>{r.employee}</Link>},{key:'activities',header:'Actividades',render:r=>r.activities},{key:'resolved',header:'Resueltos',render:r=>r.resolved_pendings},{key:'open',header:'Abiertos',render:r=>r.open_pendings},{key:'last',header:'Última intervención',render:r=>stamp(r.last_activity)}]}/></section>}
 {(view==='Pendientes')&&<section><h2>Distribución de pendientes abiertos</h2><div className="platformCharts">{[['age','Antigüedad'],['client','Cliente'],['period','Periodo'],['engine','Origen'],['type','Tipo']].map(([key,title])=><ChartCard key={key} title={title} points={a.pending_distributions[key]} unit="pendientes" range="Carga actual autorizada"/>)}</div></section>}
 {(view==='Asignaciones'||summary&&individual)&&<section><h2>Trabajo asignado actualmente</h2><p className="platformMuted">{a.workload_notice}</p><DataTable rows={a.active_assignments} getRowKey={r=>r.id} emptyMessage={a.workload_available?'Sin asignaciones activas.':'No hay atribución de paquetes para este filtro.'} columns={[
 {key:'client',header:'Cliente',render:r=><Link href={customer(r.client_id)}>{r.client}</Link>},{key:'title',header:'Asignación',render:r=>r.title},{key:'responsible',header:'Responsable',render:r=>r.responsible},{key:'period',header:'Periodo',render:r=>data.periods.find(p=>p.id===r.period_id)?.label||'Sin periodo trazable'},{key:'status',header:'Estado',render:r=>r.status.replaceAll('_',' ').toLowerCase()}]}/></section>}
 {!individual&&(view==='Equipo'||view==='Clientes')&&<section><h2>Matriz equipo × cliente</h2><label>Métrica<select value={matrixMetric} onChange={e=>setMatrixMetric(e.target.value as typeof matrixMetric)}><option value="activities">Actividades humanas</option><option value="open_pendings">Pendientes abiertos</option><option value="periods_worked">Periodos trabajados</option>{a.workload_available&&<option value="active_assignments">Asignaciones activas</option>}</select></label><p className="platformMuted">Lectura por pares empleado–cliente, Sólo combinaciones con actividad, pendientes o carga autorizada.</p><DataTable rows={a.matrix} getRowKey={r=>`${r.employee_id}-${r.client_id}`} columns={[{key:'employee',header:'Empleado',render:r=><Link href={employee(r.employee_id,r.client_id)}>{r.employee}</Link>},{key:'client',header:'Cliente',render:r=><Link href={reportLink(customer(r.client_id),query,{employee_id:String(r.employee_id),client_id:String(r.client_id),tab:'Reportes'})}>{r.client}</Link>},{key:'value',header:'Total',render:r=>r[matrixMetric]}]}/></section>}
 </>;
}
