import type {CurrentUser} from '../roles';
export type Data = Record<string, unknown>;
export type Surface = 'home'|'employer'|'employee'|'period'|'run'|'social'|'import'|'reconciliation';
export const publicRef = (value: unknown): value is string => typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
export function object(value: unknown): Data {return value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Data : {};}
export function rows(value: unknown): Data[] {return Array.isArray(value) ? value.map(object) : [];}
export function text(value: unknown): string {return value === null || value === undefined ? '—' : typeof value === 'object' ? JSON.stringify(value) : String(value);}
export function allowed(user: CurrentUser|null) {return !!user && (user.is_superuser || ['staff','senior','manager','partner'].includes(user.role || '') && !!user.organization_id);}
export function privileged(user: CurrentUser|null) {return allowed(user) && !!user && (user.is_superuser || ['manager','partner'].includes(user.role || ''));}
export const captions: Record<string,string> = {
  EXACT_NO_TOLERANCE:'Comparación exacta, sin tolerancia automática',EMPLOYER_DECLARATION:'Declaración del empleador',APPROVED_PAYROLL_EXPLICIT_ROSTER:'Población explícita de la nómina aprobada', 'SBC_UNITS_RATES-1':'SBC declarado por unidades y tasas · versión 1',RUN_FROZEN:'Corrida cerrada; los resultados se conservan como historia',CURRENT_GENERATION:'Generación actual',FIXED:'Fijo',VARIABLE:'Variable',MIXED:'Mixto',ENDED:'Terminado',NOT_DECLARED:'Sin declarar',NO_EFFECT:'Sin efecto en esta regla interna',OFFICIAL_IMPORTED:'Fuente importada; sin certificación oficial',INPUT:'Dato declarado',ABSENCE:'Ausencia',DISABILITY:'Incapacidad declarada',VACATION:'Vacaciones',OVERTIME:'Tiempo extra',BONUS:'Bono',COMMISSION:'Comisión',ADJUSTMENT:'Ajuste',DISCOUNT:'Descuento',CONFIRMED:'Confirmada',COMPARED:'Comparada',MATCHED:'Coincide',VALUE_DIFFERENCE:'Diferencia de importe',MISSING_IN_EXTERNAL:'Falta en la fuente externa',MISSING_IN_CAROVA:'Falta en CAROVA',NOT_OFFICIAL_FORMAT:'Formato técnico interno',
  WEEKLY:'Semanal',BIWEEKLY:'Cada dos semanas',SEMI_MONTHLY:'Quincenal',MONTHLY:'Mensual',EXTRA:'Extraordinario',rfc:'RFC',curp:'CURP',nss:'NSS',
  ACTIVE:'Activo',INACTIVE:'Inactivo',COMPENSATION_UNITS:'Compensación por unidades',DECLARED_AMOUNT:'Importe declarado',QUANTITY_RATE:'Cantidad por tarifa',UNCONFIGURED:'Sin configurar',SBC_UNITS_RATES:'SBC declarado por unidades y tasas configuradas',PERCEPTION:'Percepción',DEDUCTION:'Deducción',OTHER:'Otro concepto',ADD:'Suma al neto',SUBTRACT:'Resta del neto',INFORMATIONAL:'Informativo',DAY:'Día',HOUR:'Hora',PERIOD:'Período',UNIT:'Unidad',AMOUNT:'Importe',INTERNAL_CONFIGURATION:'Configuración interna',DECLARED_VALUE:'Valor declarado',OFFICIAL_REFERENCE:'Referencia oficial sin cálculo implementado',DECLARED:'Declarado por el despacho',INTERNAL_ONLY:'Sólo preparación interna',
  DRAFT:'Borrador',CALCULATED:'Calculada',PENDING_REVIEW:'Pendiente de revisión',APPROVED:'Aprobado internamente',VOID:'Anulada',CURRENT:'Vigente',STALE:'Requiere actualización',SOURCE_CHANGED:'Evidencia retirada o alterada',NOT_CALCULATED:'Sin cálculo',FROZEN_HISTORY:'Historia congelada',HISTORICAL_GENERATION:'Generación histórica',READY_FOR_PREPARATION:'Lista para preparación interna',READY_FOR_REVIEW:'Requiere revisión',NOT_READY:'Falta material',IMPORTED:'Importado',OPEN:'Abierta',RESOLVED:'Resuelta',NOT_VERIFIED:'Sin verificación oficial',FORMAT_NOT_CONFIGURED:'Reglas oficiales no configuradas',INTERNAL_CONFIGURED:'Configuración interna',REGULATORY_PENDING:'Reglas oficiales pendientes',RULE_NOT_CONFIGURED:'Regla no configurada',MISSING_COMPENSATION:'Falta compensación vigente',PERIOD_SPLIT_REQUIRED:'El periodo requiere separación por cambio de vigencia',CALCULATION_STALE:'El cálculo requiere actualización',SOCIAL_NOT_READY:'Falta material para calcular seguridad social',PAYROLL_NOT_READY:'Falta material para calcular la corrida',IDENTITY_AMBIGUOUS:'Identidad ambigua: requiere revisión',PERIOD_MISMATCH:'El periodo de la evidencia no coincide',BLOCKED_BY_MISSING_BUSINESS_RULE:'Falta una regla de negocio autorizada',ACTION_NOT_AUTHORIZED:'Tu acceso no permite esta acción',NOT_FOUND:'El recurso no está disponible',REVIEW_REQUIRED:'Falta revisión',SIDEIMSS_NOT_READY:'Falta evidencia vigente para el paquete',RECONCILIATION_STALE:'La conciliación requiere actualización',MISSING_EXTERNAL_EVIDENCE:'Falta evidencia externa',OPEN_MATERIAL_DIFFERENCES:'Hay diferencias abiertas',RESOLUTION_EVIDENCE_NOT_CURRENT:'La evidencia de la resolución ya no está vigente',CURRENTNESS_CHANGED:'El material cambió',CALCULATION_NOT_CURRENT:'El cálculo no está vigente',RUN_NOT_PENDING_REVIEW:'La corrida no está pendiente de revisión',PRIVILEGED_APPROVER_REQUIRED:'La aprobación requiere un responsable autorizado',PERIOD_ALREADY_APPROVED:'El periodo ya tiene una corrida aprobada',SOCIAL_ALREADY_APPROVED:'La nómina ya tiene seguridad social aprobada',IMPORT_TRANSACTION_BOUNDARY_REQUIRED:'La importación requiere una transacción propia',IMPORT_STORAGE_FAILED:'No se pudo completar la importación',PERSISTENCE_CONFLICT:'El material cambió; vuelve a consultar',INVALID_INPUT:'Revisa el dato declarado',UNKNOWN_FIELD:'El formulario contiene un dato no admitido',MISSING_INPUT:'Falta un dato requerido',INVALID_QUERY:'Revisa los filtros',VERSION_PREDECESSOR_CONFLICT:'Selecciona la versión precedente vigente',OVERLAPPING_VERSIONS:'La vigencia se cruza con una versión existente',RESOLUTION:'Resolución',CONFIRM_DOCUMENTED_VARIANCE:'Confirmar variación documentada',REQUEST_EVIDENCE:'Solicitar evidencia',ACCEPT:'Aceptar revisión',RETURN:'Devolver a borrador',WITHDRAWN:'Retirada',STRUCTURE_ONLY_NOT_SAT_OR_IMSS_VERIFIED:'Sólo estructura, sin validación SAT/IMSS'
};
export const label=(value: unknown)=>captions[text(value)] || text(value);
export type Option={value:string;label:string};
export type Field={name:string;label:string;type?:'text'|'date'|'textarea'|'select'|'list'|'refs'|'records'|'file';options?:Option[];required?:boolean;initial?:unknown;columns?:Field[];help?:string};
export type FormSpec={title:string;path:string;method?:'POST'|'PATCH';fields:Field[];fixed?:Data;confirmed?:boolean;kind?:'version'|'preview'|'download';previewPath?:string};
