'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {apiFetch,apiJson} from '@/lib/api';
import {usePanelUser} from '@/lib/PanelUserContext';
import {isPrivileged} from '@/lib/roles';
import {formErrorMessage} from '@/lib/formErrors';
import PageHeader from '@/components/panel/PageHeader';
import FormField from '@/components/panel/FormField';
import Modal from '@/components/panel/Modal';
import DataTable from '@/components/panel/DataTable';

type Account={id:number;code:string;name:string;active:boolean;normal_balance:string};
type ConfigRow={state?:string;provenance?:{source_reference?:string};id:number;active:boolean;version:number;name?:string;rule_key?:string;account_text?:string;code?:string;bank_name?:string;approved_by?:string;approved_at?:string;reason?:string;effective_from?:string;effective_to?:string;selector?:Record<string,string>;lines?:Line[]};
type Line={sequence:number;code:string;side:string;account_from:string;amount_basis:string;tax_selector:Record<string,string>;required:boolean};
type Config={accounts:Account[];rules:ConfigRow[];text_mappings:ConfigRow[];bank_mappings:ConfigRow[];bank_accounts:{id:number;name:string}[];notice:string};
type Option={id:number;name:string};
const initialLine=(n:number):Line=>({sequence:n,code:'',side:n===1?'DEBIT':'CREDIT',account_from:'CODE',amount_basis:'CASE_AMOUNT',tax_selector:{},required:true});
const bases:Record<string,string>={CASE_AMOUNT:'Importe de póliza',CFDI_TOTAL:'Total CFDI',CFDI_SUBTOTAL:'Subtotal CFDI',CFDI_TAX_AMOUNT:'Importe de impuesto CFDI',CFDI_TAX_BASE:'Base de impuesto CFDI',BANK_AMOUNT:'Importe bancario'};
const names:Record<string,string>={rule_key:'Clave estable de regla',name:'Nombre',code:'Código de cuenta',parent_code:'Cuenta superior (opcional)',normal_balance:'Saldo normal',external_system:'Sistema contable externo (opcional)',external_identifier:'Código externo (opcional)',account_text:'Cuenta según clasificación histórica',subaccount_text:'Subcuenta histórica (opcional)',detail_account_text:'Cuenta de detalle histórica (opcional)',effective_from:'Inicio de vigencia',effective_to:'Fin de vigencia (opcional)',issuer_rfc:'RFC emisor (opcional)',issuer_key:'Nombre de emisor demostrado (opcional)',tipo_comprobante:'Tipo CFDI (opcional)',metodo_pago:'Método de pago (opcional)',currency:'Moneda (opcional)',bank_account_id:'Cuenta bancaria',bank_direction:'Dirección bancaria (opcional)',source:'Fuente / criterio de aprobación',reason:'Motivo de aprobación o retiro'};
export default function AccountingConfiguration(){
 const {user}=usePanelUser();const [org,setOrg]=useState(''),[client,setClient]=useState(''),[eng,setEng]=useState(''),[orgs,setOrgs]=useState<Option[]>([]),[clients,setClients]=useState<(Option&{organization_id:number})[]>([]),[engs,setEngs]=useState<(Option&{cliente_id?:number;nombre?:string})[]>([]),[data,setData]=useState<Config|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[lines,setLines]=useState<Line[]>([initialLine(1),initialLine(2)]),[confirmed,setConfirmed]=useState(false);
 const allowed=isPrivileged(user);const root='/api/carova/workspace/accounting/configuration/';
 const scope=useCallback(()=>({organization_id:Number(org),...(client?{client_id:Number(client)}:{}),...(eng?{engagement_id:Number(eng)}:{})}),[org,client,eng]);
 const load=useCallback(async()=>{if(!org||!allowed)return;try{const q=new URLSearchParams(Object.entries(scope()).map(([k,v])=>[k,String(v)]));const r=await apiFetch(root+'?'+q);const d=await r.json();if(!r.ok)throw new Error(formErrorMessage(d));setData(d);setClients(d.clients);setEngs(d.engagements);setError('');}catch(e){setError((e as Error).message);}},[org,scope,allowed]);
 useEffect(()=>{if(!allowed)return;let live=true;Promise.all(['/api/organizaciones/'].map(async p=>{const r=await apiFetch(p);return r.ok?r.json():[];})).then(([o])=>{if(live){setOrgs(o);setOrg(String(user?.organization_id||o[0]?.id||''));}});return()=>{live=false;};},[allowed,user?.organization_id]);
 useEffect(()=>{void load();},[load]);
 function open(action:string,row?:ConfigRow){setMode(action);setError('');setConfirmed(false);setValues(row?{id:String(row.id),rule_key:row.rule_key||'',name:row.name||'',effective_from:row.effective_from||'',effective_to:row.effective_to||'',...row.selector}:{});setLines(row?.lines?.map(x=>({...x,code:x.code||'',tax_selector:x.tax_selector||{}}))||[initialLine(1),initialLine(2)]);}
 function field(k:string,required=true,options?:Record<string,string>){return <FormField key={k} label={names[k]||k} required={required}>{options?<select required={required} value={values[k]||''} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}><option value="">Selecciona</option>{Object.entries(options).map(([x,n])=><option value={x} key={x}>{n}</option>)}</select>:<input required={required} type={k.includes('effective')?'date':'text'} value={values[k]||''} maxLength={k==='reason'?2000:250} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/>}</FormField>;}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let payload:Record<string,unknown>={...scope(),...values,action:mode,confirmed};if(values.id)payload.id=Number(values.id);if(values.bank_account_id)payload.bank_account_id=Number(values.bank_account_id);if(mode==='rule_approve')payload={...payload,lines:lines.map((l,i)=>({...l,sequence:i+1,tax_selector:l.amount_basis.includes('TAX')?l.tax_selector:{}})),provenance:{kind:'MANUAL_APPROVAL',source_reference:values.source}};if(!payload.effective_to)delete payload.effective_to;const r=await apiJson(root,'POST',payload);const d=await r.json();if(!r.ok)throw new Error(formErrorMessage(d));setData(d);setMode('');setNotice('Configuración guardada. Las versiones anteriores y la procedencia se conservan.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!allowed)return <p role="alert">Esta administración requiere gerente, socio o administrador global.</p>;
 const activeAccounts=Object.fromEntries((data?.accounts||[]).filter(x=>x.active).map(x=>[x.code,`${x.code} · ${x.name}`]));
 return <><PageHeader title="Configuración contable" description="Catálogo, equivalencias y reglas aprobadas del contexto seleccionado."/><Link className="cc-btn cc-btn--ghost" href="/panel/configuracion">Volver a Configuración</Link><div className="panelCard twoCols"><FormField label="Organización"><select value={org} onChange={e=>{setOrg(e.target.value);setClient('');setEng('');setData(null);}}>{orgs.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></FormField><FormField label="Alcance de cliente"><select value={client} onChange={e=>{setClient(e.target.value);setEng('');}}><option value="">Global de la organización</option>{clients.filter(x=>String(x.organization_id)===org).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></FormField><FormField label="Alcance de encargo"><select value={eng} onChange={e=>setEng(e.target.value)}><option value="">Todos los encargos del alcance</option>{engs.filter(x=>client&&String(x.cliente_id)===client).map(x=><option value={x.id} key={x.id}>{x.nombre||x.name}</option>)}</select></FormField></div>{notice&&<p role="status">{notice}</p>}{error&&!mode&&<p role="alert">{error}</p>}
 {data&&<><p>{data.notice}</p><section className="panelCard"><h2>Catálogo</h2><button className="cc-btn cc-btn--solid" onClick={()=>open('account_create')}>Agregar cuenta</button><DataTable rows={data.accounts} getRowKey={x=>x.id} columns={[{key:'code',header:'Cuenta',render:x=>`${x.code} · ${x.name}`},{key:'active',header:'Estado',render:x=>x.active?'Activa':'Retirada'},{key:'action',header:'Acción',render:x=><button className="cc-btn cc-btn--ghost" onClick={()=>open(x.active?'account_deactivate':'account_activate',{...x,version:0})}>{x.active?'Desactivar':'Activar'}</button>}]}/></section>
 {[['text_mappings','Equivalencias de clasificación','text_mapping_approve','text_mapping_revoke'],['bank_mappings','Contrapartidas bancarias','bank_mapping_approve','bank_mapping_revoke'],['rules','Reglas versionadas','rule_approve','rule_revoke']].map(([key,title,create,revoke])=><section className="panelCard" key={key}><h2>{title}</h2><button className="cc-btn cc-btn--solid" onClick={()=>open(create)}>{key==='rules'?'Preparar y aprobar nueva regla':'Aprobar nueva equivalencia'}</button><DataTable rows={data[key as 'rules'|'text_mappings'|'bank_mappings']} getRowKey={x=>x.id} columns={[{key:'name',header:'Identidad / versión',render:x=>`${x.name||x.rule_key||x.account_text||x.bank_name} · v${x.version}${x.code?' → '+x.code:''}`},{key:'status',header:'Estado',render:x=>x.state==='ACTIVE'?'Activa / aprobada':x.state==='REPLACED'?'Reemplazada · historial conservado':'Revocada · historial conservado'},{key:'evidence',header:'Vigencia / procedencia',render:x=><>{x.effective_from} {x.effective_to&&`a ${x.effective_to}`}<br/>{x.approved_by} · {x.approved_at}<br/>{x.reason}<br/>Fuente: {x.provenance?.source_reference||'Aprobación humana registrada'}</>},{key:'action',header:'Acciones',render:x=><>{key==='rules'&&<button className="cc-btn cc-btn--ghost" onClick={()=>open(create,x)}>Crear nueva versión</button>}{x.active&&<button className="cc-btn cc-btn--ghost" onClick={()=>open(revoke,x)}>Revocar versión</button>}</>} ]}/></section>)}</>}
 <Modal open={!!mode} title={mode==='rule_approve'?'Borrador y aprobación de nueva versión':'Administrar configuración contable'} onClose={()=>!busy&&setMode('')} maxWidth={850}><form className="uploadForm" onSubmit={save}><p>Contexto: {orgs.find(x=>String(x.id)===org)?.name} · {clients.find(x=>String(x.id)===client)?.name||'Organización'}. Este formulario permanece como borrador hasta confirmar; no sobrescribe versiones aprobadas.</p>
 {mode==='account_create'&&<>{field('code')}{field('name')}{field('parent_code',false,activeAccounts)}{field('normal_balance',false,{DEUDORA:'Deudora',ACREEDORA:'Acreedora'})}{field('external_system',false)}{field('external_identifier',false)}</>}
 {mode==='text_mapping_approve'&&<>{field('account_text')}{field('subaccount_text',false)}{field('detail_account_text',false)}{field('code',true,activeAccounts)}</>}
 {mode==='bank_mapping_approve'&&<>{field('bank_account_id',true,Object.fromEntries((data?.bank_accounts||[]).map(x=>[String(x.id),x.name])))}{field('code',true,activeAccounts)}</>}
 {mode==='rule_approve'&&<>{field('rule_key')}{field('name')}{field('effective_from')}{field('effective_to',false)}{field('source')}{['issuer_rfc','issuer_key','tipo_comprobante','metodo_pago','currency'].map(k=>field(k,false))}{field('bank_direction',false,{DEBIT:'Cargo',CREDIT:'Abono',UNKNOWN:'Desconocida'})}<h3>Líneas de propuesta</h3>{lines.map((l,i)=><fieldset key={i}><legend>Partida {i+1}</legend><div className="twoCols"><FormField label="Origen de cuenta"><select value={l.account_from} onChange={e=>setLines(a=>a.map((x,j)=>j===i?{...x,account_from:e.target.value}:x))}><option value="CODE">Cuenta elegida del catálogo</option><option value="BANK_ACCOUNT_MAPPING">Contrapartida bancaria aprobada</option></select></FormField>{l.account_from==='CODE'&&<FormField label="Cuenta" required><select required value={l.code} onChange={e=>setLines(a=>a.map((x,j)=>j===i?{...x,code:e.target.value}:x))}><option value="">Selecciona cuenta</option>{Object.entries(activeAccounts).map(([c,n])=><option value={c} key={c}>{n}</option>)}</select></FormField>}<FormField label="Lado"><select value={l.side} onChange={e=>setLines(a=>a.map((x,j)=>j===i?{...x,side:e.target.value}:x))}><option value="DEBIT">Cargo</option><option value="CREDIT">Abono</option></select></FormField><FormField label="Fuente del importe"><select value={l.amount_basis} onChange={e=>setLines(a=>a.map((x,j)=>j===i?{...x,amount_basis:e.target.value}:x))}>{Object.entries(bases).map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></FormField></div>{l.amount_basis.includes('TAX')&&['scope','kind','impuesto','tipo_factor','tasa_o_cuota'].map(k=><FormField key={k} label={({'scope':'Ámbito: COMPROBANTE o CONCEPTO',kind:'Tipo: TRASLADO o RETENCION',impuesto:'Código de impuesto declarado',tipo_factor:'Factor declarado',tasa_o_cuota:'Tasa o cuota exacta'} as Record<string,string>)[k]||k} required={k==='scope'}><input required={k==='scope'} value={l.tax_selector[k]||''} onChange={e=>setLines(a=>a.map((x,j)=>j===i?{...x,tax_selector:{...x.tax_selector,[k]:e.target.value}}:x))}/></FormField>)}<button type="button" className="cc-btn cc-btn--ghost" disabled={lines.length===1} onClick={()=>setLines(a=>a.filter((_,j)=>j!==i))}>Quitar partida del borrador</button></fieldset>)}<button type="button" className="cc-btn cc-btn--ghost" onClick={()=>setLines(a=>[...a,initialLine(a.length+1)])}>Agregar partida</button></>}
 {field('reason')}<label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Revisé el contexto, la vigencia y la procedencia; confirmo este cambio.</label>{error&&<p role="alert" className="loginError">{error}</p>}<button className="cc-btn cc-btn--solid" disabled={busy||!confirmed}>Confirmar {mode.endsWith('approve')?'aprobación':'cambio'}</button></form></Modal></>;
}
