'use client';
import {useEffect,useState} from 'react';
import {request,rows,text,type Row} from './client';
import styles from './Books.module.css';
import {bookLabel,bookDisplay} from '../../lib/books-contract';
import FormDialog from '../billing/FormDialog';
export default function FiscalReturn({targetRef,kind}:{targetRef:string;kind:'invoice'|'payroll'}){
 const [client,setClient]=useState(''),[links,setLinks]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0),[withdrawRef,setWithdrawRef]=useState('');
 useEffect(()=>{const c=new AbortController();request(`${kind==='invoice'?'billing':'payroll'}-handoff/${targetRef}/`,undefined,c.signal).then(async info=>{const client=text(info.client_ref);const records=await request(`clients/${client}/fiscal/?${kind}_ref=${targetRef}`,undefined,c.signal);if(!c.signal.aborted){setClient(client);setLinks(rows(records.results));}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[targetRef,kind,reload]);
 return <section className={styles.card}><h2>XML timbrado externamente</h2><p>Vínculo de evidencia externa; CAROVA no timbra, certifica ni confirma vigencia SAT. Las diferencias requieren revisión.</p>{error&&<p role="alert">{error}</p>}{client&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');const f=new FormData(form);f.set(kind+'_ref',targetRef);try{await request(`clients/${client}/fiscal/`,f);setReload(v=>v+1);form.reset();}catch(ex){setError(ex instanceof Error?ex.message:'Revisa el XML.');}finally{setBusy(false);}}}><label className={styles.field}>XML original<input name="file" type="file" accept=".xml" required disabled={busy}/></label><label className={styles.field}>PDF externo opcional<input name="pdf" type="file" accept=".pdf" disabled={busy}/></label><button disabled={busy}>Verificar y vincular XML</button></form>}<ul>{links.map(row=><li key={text(row.ref)}><p>{text(row.uuid)} · {bookLabel(row.state)} · Diferencias: {bookDisplay(row.differences)||'Ninguna'}</p>{row.state!=='WITHDRAWN'&&<button disabled={busy} onClick={()=>{setError('');setWithdrawRef(text(row.ref));}}>Retirar vínculo y conservar historia</button>}</li>)}</ul>{withdrawRef&&<FormDialog title='Retirar vínculo fiscal' fields={[{key:'reason',label:'Razón documentada',type:'textarea'}]} busy={busy} error={error} onCancel={()=>setWithdrawRef('')} onSubmit={async values=>{setBusy(true);setError('');try{await request(`fiscal-links/${withdrawRef}/`,{reason:text(values.reason)});setReload(v=>v+1);setWithdrawRef('');}catch(ex){setError(ex instanceof Error?ex.message:'No se pudo retirar.');}finally{setBusy(false);}}}/>}</section>;
}
