'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {billing} from '../../lib/billing/client';
import {object,rows,text,fieldErrorAttributes,type Row} from '../../lib/billing/model';
import styles from './Billing.module.css';
export type Field={key:string;label:string;type?:string;options?:string[];source?:string;optional?:boolean;initial?:string;help?:string};
export function Picker({field,value,onChange,disabled}:{field:Field;value:string;onChange:(v:string)=>void;disabled:boolean}){
 const [page,setPage]=useState(0),[data,setData]=useState<Row>({}),[error,setError]=useState('');const id=useId();
 useEffect(()=>{let active=true;billing.read(`${field.source}${field.source?.includes('?')?'&':'?'}limit=20&offset=${page}`).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[field.source,page]);
 const choices=rows(data.results).filter(r=>field.key==='receiver_ref'?r.scope==='RECEIVER'&&r.active!==false:r.active!==false);
 return <div className={styles.field}><label htmlFor={id}>{field.label}</label><select id={id} required={!field.optional} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Selecciona explícitamente</option>{value&&!choices.some(r=>r.ref===value||r.client_name===value||r.code===value)&&<option value={value}>Selección conservada</option>}{choices.map((r,i)=>{const v=field.key==='requested_series_code'?text(r.code):field.key==='client_name'?text(r.client_name):text(r.ref);return <option key={v+'-'+i} value={v}>{[r.client_name,r.legal_name,r.internal_code,r.item_code,r.code,r.description,r.series_code,r.folio,r.balance,r.currency,r.amount].filter(v=>v!==undefined&&v!==null).map(text).join(' · ')}</option>;})}</select><div className={styles.pager}><button type="button" disabled={disabled||page===0} onClick={()=>setPage(Math.max(0,page-20))}>Anteriores</button><button type="button" disabled={disabled||!data.has_more} onClick={()=>setPage(page+20)}>Siguientes opciones</button></div>{error&&<p role="alert">{error}</p>}{field.help&&<small>{field.help}</small>}</div>;
}
export default function FormDialog({title,fields,notice,busy,error,fieldErrors={},onCancel,onSubmit}:{title:string;fields:Field[];notice?:string;busy:boolean;error:string;fieldErrors?:Record<string,string>;onCancel:()=>void;onSubmit:(v:Row)=>Promise<void>}){
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f.key,f.initial||''])));
 const root=useRef<HTMLDivElement>(null);const id=useId();
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;root.current?.querySelector<HTMLElement>('input,select,textarea,button')?.focus();return()=>previous?.focus();},[]);
 function trap(e:React.KeyboardEvent){if(e.key==='Escape'&&!busy)onCancel();if(e.key==='Tab'){const controls=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 return <div className={styles.backdrop}><div ref={root} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby={id} onKeyDown={trap}><h2 id={id}>{title}</h2>{notice&&<p className={styles.notice}>{notice}</p>}<form onSubmit={e=>{e.preventDefault();void onSubmit(object(values));}}>{fields.map(f=>f.source?<Picker key={f.key} field={f} value={values[f.key]||''} onChange={v=>setValues({...values,[f.key]:v})} disabled={busy}/>:<div key={f.key} className={styles.field}><label htmlFor={`${id}-${f.key}`}>{f.label}</label>{f.options?<select id={`${id}-${f.key}`} disabled={busy} required={!f.optional} {...fieldErrorAttributes(fieldErrors[f.key],`${id}-error`)} value={values[f.key]||''} onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="">Selecciona</option>{f.options.map(v=><option key={v}>{v}</option>)}</select>:f.type==='textarea'?<textarea id={`${id}-${f.key}`} disabled={busy} required={!f.optional} {...fieldErrorAttributes(fieldErrors[f.key],`${id}-error`)} aria-describedby={fieldErrors[f.key]||error?`${id}-error`:undefined} value={values[f.key]||''} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:<input id={`${id}-${f.key}`} type={f.type==='decimal'?'text':f.type||'text'} disabled={busy} required={!f.optional} {...fieldErrorAttributes(fieldErrors[f.key],`${id}-error`)} inputMode={f.type==='decimal'?'decimal':undefined} value={values[f.key]||''} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>} {f.help&&<small>{f.help}</small>}</div>)}{error&&<p id={`${id}-error`} role="alert" className={styles.error}>{error}</p>}<div className={styles.actions}><button type="button" className="cc-btn cc-btn--outline" disabled={busy} onClick={onCancel}>Cancelar</button><button type="submit" className="cc-btn cc-btn--solid" disabled={busy}>{busy?'Procesando…':'Confirmar'}</button></div></form></div></div>;
}
